### ISSUE TITLE
[Feature Request]: Tab/enter/arrows/etc for applying tags.

### ISSUE THREAD

**Issue by Innomen** [Jermolene/TiddlyWiki5#1555] opened 2015-03-06 03:13 UTC
Right now it's not possible to tag an entry with the keyboard. You must mouse click to confirm.

Everything should be possible via keyboard some people can't use a mouse. (I can but I prefer keyboard a lot of the time.)

Thank you for making this. My apologies if this is a duplicate or something, I couldn't find it.

(Firefox 36)

**Comment by pmario** [comment] 2015-03-06 13:13
imo there is a duplicate, but I can't find it either :)

You could create a new edit template and replace the click interface with a simple tag "edit text input" line. 

or you can change the content of `http://tiddlywiki.com/#%24%3A%2Fconfig%2FEditTemplateFields%2FVisibility%2Ftags` from "hide" to "show" as the fastest work around.

**Comment by Innomen** [comment] 2015-03-06 16:44
I don't understand your work arounds. I'm a writer not a coder.

I don't know what they would do, much less how to implement them. I'll just wait till the tagging system is upgraded to work like it does in wordpress and the like.

Like tab to tag field, hit "J", journal is the top choice, enter applies. Or tab to tag field, hit "p", psychology, is the third choice, arrow down to it, enter applies. Etc.

**Comment by Jermolene** [comment] 2015-03-11 19:01
Thanks @Innomen I think this is a dupe of #980

**Comment by Innomen** [comment] 2015-03-11 19:09
Ahhh indeed it is, thanks much, Sorry about that.

**Comment by Jermolene** [comment] 2015-03-11 19:18
No worries, it's helpful to get this sort of feedback; making an issue is a vote that can be clearly heard :smile:

**Closed by Jermolene** 2015-03-11 19:18 UTC
