### ISSUE TITLE
JS executable within iframes

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#2327] opened 2016-03-17 19:03 UTC
Putting the following straight into a tiddler "works", i.e triggers the js:

`<iframe srcdoc="Potentially-dangerous user content<script>alert('lol');</script>"></iframe>`

Note: as explained in the [webpage](https://bocoup.com/weblog/third-party-javascript-development-future#iframe-srcdoc) where I found this example, one major point with the `srcdoc` attribute (along with the `sandbox` attribute) is to **sandbox** the srcdoc value from the surrounding document - so that it is _not_ harmful.

I don't know what @Jermolene (or anyone else) has in mind to deal with this but I hope it will not prevent non-harmful use of what is enabled with iframe/srcdoc/...

**Comment by Jermolene** [comment] 2016-03-18 09:16
Hi @twMat in fact, the example you quoted is benign; we *want* iframes to be able to run JavaScript so that we can embed things like Google Docs. The issue is whether that JavaScript residing in an iframe can access any data outside the iframe. Sadly, as things stand, it is perfectly possible:

```
<iframe srcdoc="Potentially-dangerous user content<script>alert(window.frameElement.parentNode.parentNode.parentNode.innerHTML);</script>"></iframe>
```

Compare behaviour if you add a "sandbox" attribute:

```
<iframe sandbox srcdoc="Potentially-dangerous user content<script>alert(window.frameElement.parentNode.parentNode.parentNode.innerHTML);</script>"></iframe>
```

The iframes that TW creates do have the sandbox attribute. So the question is whether we should force the sandbox attribute on all iframes?

**Comment by twMat** [comment] 2016-03-18 10:59
>So the question is whether we should force the sandbox attribute on all iframes?

I'm not qualified to answer but will give some background to why I'm expermenting with this to begin with. It may be that iframes or its attributes are not the right way at all for this, I have no idea;

Currently, js code notes and snips, or even full code examples, must be put in quote blocks which obviously kills everything and no styling. And it's probably the same for snips of other code languages (e.g C#), i.e it's most safely put in quote blocks. For a note taking tool, and one that often turns to "code tinkerers", this is very limiting... or even outright; TW us probably unsuitable as a note tool for this huge subject. Which is ironic given the role js has in TW.

I hope TW could allow "semi-sandboxes", where you can put code that is "disarmed" but that at the same time can be styled and even interactive with the TW by use of a (subset?) of the standard TW features. 

It should also be very valuable for the _TW project itself_ if people can use TW itself to build js stuff for TW - compare it to how we mostly use HTML and CSS freely when building plugins.

I don't mean to start a discussion (as this is not the place for that) but feel compelled to give this background so any imposed restrictions will not eleminate eventual possibilities in this regard.
...assuming iframes are at all relevant for my fantasies...

**Comment by Jermolene** [comment] 2016-03-18 11:04
Hi @twMat there's a few things here:

* Currently the only way to style the content of an iframe is to insert style definitions into it (the text editor does this: it creates a dummy textarea and then reads the styles from it to squirt into the iframe). Eventually browsers may [support the "seamless" attribute](http://caniuse.com/#feat=iframe-seamless) which will allow direct styling of iframe content
* The concern I mentioned was about allowing JS code in an iframe to escape the sandbox. The examples you give would all work perfectly well in a sandbox.

**Comment by twMat** [comment] 2016-03-18 11:23
>The concern I mentioned was about allowing JS code in an iframe to escape the sandbox. The examples you give would all work perfectly well in a sandbox.

So it would _not prevent_ e.g a tw-link inside the iframe to open a tiddler that is outside of the iframe but in the TW? (I emphasize "so it would _not prevent_" because obviously it would not _enable_, that's another matter).

A use case to clarify could be an iframe with a code snip showing a _code keyword_ (surrounded by double brackets that aren't seen in view mode) which could be clicked on to go to a tiddler about that keyword.

**Comment by Jermolene** [comment] 2016-03-18 11:26
> So it would not prevent e.g a tw-link inside the iframe to open a tiddler that is outside of the iframe but in the TW?

That would be an example of the iframe busting out of its sandbox, because it would require the JS code within the iframe that is handling the click event to be able to reach out of the iframe to open the required tiddler.

The workaround would be to devise a protocol for code within a sandboxed iframe to be able to request to eg open a tiddler. The mechanism there is postMessage, as used by federation.

> A use case to clarify could be an iframe with a code snip showing a code keyword (surrounded by double brackets that aren't seen in view mode) which could be clicked on to go to a tiddler about that keyword.

That's pretty easy: don't put the code snippet in the iframe, just put the output of the code snippet in the iframe.

**Comment by twMat** [comment] 2016-03-18 12:59
Great, so things will still be doable. Thanks for clarifications.

**Comment by sukima** [comment] 2016-03-18 15:46
>Actually, TW is really unsuitable as a note tool for this huge subject. Which is ironic given the role js has in TW.

This confuses me a lot since I use TW for code snipit all the time! I wrap then in triple back ticks. Wth the highlight.js plugin it even get syntax highlighting. Win! if I wanted to provide an example of running code I'd embed a jsbin.com or jsfiddle.net or simply write a TW Widget to demonstrate.

Am I missing something?

**Comment by Jermolene** [comment] 2016-03-18 15:48
@sukima using jsbin/jsfiddle is a good approach if you don't mind the need to be online to use it.

In any event, I don't think there's any action indicated by this ticket so I shall close it.

**Closed by Jermolene** 2016-03-18 15:48 UTC

**Comment by tobibeer** [comment] 2016-10-01 00:47
He, funny... ;-)

```
<iframe srcdoc="""
<script>
window.frameElement.parentNode.parentNode.innerHTML="Where am I?";
</script>
""">
</iframe>
```
