### ISSUE TITLE
Inline markdown editor

### ISSUE THREAD

**Issue by siulung4073** [Jermolene/TiddlyWiki5#2310] opened 2016-03-01 01:40 UTC
Hi there. It would be great to have a markdown editor inline, something like gitbooks or https://stackedit.io/editor# or https://github.com/NextStepWebs/simplemde-markdown-editor

**Comment by sukima** [comment] 2016-03-01 03:37
You mean http://tiddlywiki.com/plugins/tiddlywiki/markdown/ ?

**Comment by siulung4073** [comment] 2016-03-02 17:39
No. Not the parser. A toolbar editor. Like the ones I share. Instead of
knowing the syntax of the markdown, having a toolbar with buttons to
implement the syntax

**Comment by Jermolene** [comment] 2016-03-03 17:02
Funnily enough, I'm just now working on an editing toolbar for the core.

<img width="991" alt="screenshot 2016-03-03 16 59 30" src="https://cloud.githubusercontent.com/assets/174761/13502077/508b6a6c-e161-11e5-8f0e-f972f03216a7.png">

I'll post more details and a prerelease over the next few days.

**Comment by siulung4073** [comment] 2016-03-03 17:05
Thats excellent!! Thanks!!

**Comment by Jermolene** [comment] 2016-03-07 17:09
Just noticed that this is a dupe of #1747; I'll close this and make updates there.

**Closed by Jermolene** 2016-03-07 17:09 UTC
