### ISSUE TITLE
Support global rename of tags

### ISSUE THREAD

**Issue by reflectionalist** [Jermolene/TiddlyWiki5#1614] opened 2015-03-26 11:22 UTC
## Summary

Currently it seems once a tag is created, it can not be modified, say, to be renamed.  Instead, one has to create another tag of a new name, and for each tiddler tagged under the old name, remove the old tag and apply the new one.
## Reproduction

Tag several tiddlers with a tag named `Foo`, and then try to change the tag name to `Bar`.
## Expectation

I expect an operation, possibly in the Tag Manager, that allows me to edit a tag and the editting ripples through all tiddlers tagged by the old name.
## Context

OS: Kubuntu 14.04 LTS (64bit)
Browsers: Firefox (36.0) and Chromium (40.0.2214.111)

**Comment by felixhayashi** [comment] 2015-03-26 12:42
Hi @reflectionalist 

I agree. In fact, this does not seem to be too complicated:

1. Iterate over all tiddlers
2. use a regex to replace the tag
3. save the tiddler again without updating the modified field

In the guy needs to be a textinput next to each tag with a "go" button that triggers the search'n'replace action (starting the replace on every keystroke is not good).

-Felix

Replace TEXTFIELD

**Comment by inmysocks** [comment] 2015-03-27 01:44
I made a thing that does this, once it is polished and I add a bit more to it i will make a pull request. http://ooktech.com/jed/ExampleWikis/Version518Fun/

**Comment by danielo515** [comment] 2015-03-28 11:53
I don't than that using regular expressions is a good idea. Tags are an important part of tiddlywiky and the core provides enough mechanisms to modify them. In my opinion this should be done by the use of core widgets.

**Comment by edrex** [comment] 2016-01-14 18:16
duplicate of #196

**Comment by twMat** [comment] 2016-01-14 22:32
@edrex 

>duplicate of #196

I'm guessing here but depending on implementation for a solution there migth be a diffeernce betwen renaming of *tags* (this OP) and *tiddler titles* (#196). On the other hand, hopefully both will be solved in one go.

**Comment by edrex** [comment] 2016-01-14 22:49
You're right, it might also be desirable to rename tags which don't have a companion tiddler.

**Comment by felixhayashi** [comment] 2016-01-15 11:02
Hi @edrex 

> duplicate of #196

What @twMat is right. This is not about fixing links after a rename but about updating the occurences where a tiddler is tagged. It is similar to #196 though.

---

By the way: @Jermolene introduced a new (hidden) feature that actually solves #1614.

**But note:**

> "tm-rename-tiddler" functionality isn't yet documented, nor is it used in the TW5 core UI (it is exposed in the text-slicer edition).

The `renameTiddler` function exists in `wiki-bulkops.js` module and can be used via `$tw.wiki.renameTiddler("old name", "new name");` In response to #1614 I once created a PR that added a replaceTag function but Jeremy's function is much better because it doesn't primarily/only aims at renaming a tag but at renaming a tiddler and everything that relates to it. @Jermolene I think this is also the right place to redirect links using regular expressions to solve #196!

**Comment by edrex** [comment] 2016-01-15 17:45
So, #196 covers tag renames where the tag has an eponymous tiddler (let's call them "instantiated tags"), but not for "bare tags".

I put up a patch #2223 implementing #196, which adds a new hook `th-renaming-tiddler` and extracts the reference updating code from `renameTiddler` into a new wiki method `retargetReferences(from, to)`. This new method can be called with a tag name to update references to a tag. See my comments on the PR for more on this and also a no-console way to update bare tag refs. :beers:

**Comment by heronils** [comment] 2018-09-07 23:26
Wait, before that link dies, lets put the code here (put it into a Tiddler):

```
Be careful. There is no undo.
<table>
<tr>
<td>
remove
</td>
<td>
<$select tiddler=<<currentTiddler>> field="tagtoremove" default='notset'>
<$list filter='[all[tiddlers]tags[]sort[]]'>
<option value=<<currentTiddler>> field="tagtoremove"><$view
field='title'/></option>
</$list>
</$select>
</td>
<td>
<$set name="oldTag" value={{!!tagtoremove}}>
<$button>
<$list filter="[all[shadows+tiddlers]tag{!!tagtoremove}]">
<$fieldmangler>
<$action-sendmessage $message="tm-remove-tag" $param=<<oldTag>>/>
</$fieldmangler>
</$list>
Click me!
</$button>
</$set>
</td>
</tr>
<tr>
<td>
</td>
<td>
<$list filter="[all[shadows+tiddlers]tag{!!tagtoremove}]">
<$link>{{!!title}}</$link>
</$list>
</td>
<td>
</td>
</tr>
</table>

```

**Comment by benwilson34** [comment] 2018-09-26 21:50
After checking that link and digging a little I found another Tiddler (also authored by RichardWilliamSmith) which will allow you to replace one tag with another - effectively the same as renaming. Just create the new tag first, then in this Tiddler, the "old" tag goes on the left and the "new" tag goes on the right. Be careful, you can't undo this, but it has been VERY useful (kudos again RWS).

```
Be careful. There is no undo.
<table>
<tr>
<td>
remove
</td>
<td>
<$select tiddler=<<currentTiddler>> field="tagtoremove" default='notset'>
<$list filter='[all[tiddlers]tags[]]'>
<option value=<<currentTiddler>> field="tagtoremove"><$view
field='title'/></option>
</$list>
</$select>
</td>
<td>
and add
</td>
<td>
<$select tiddler=<<currentTiddler>> field="tagtoadd" default='notset'>
<$list filter='[all[tiddlers]tags[]]'>
<option value=<<currentTiddler>> field="tagtoadd"><$view
field='title'/></option>
</$list>
</$select>
</td>
<td>
<$set name="newTag" value={{!!tagtoadd}}>
<$set name="oldTag" value={{!!tagtoremove}}>
<$button>
<$list filter="[all[shadows+tiddlers]tag{!!tagtoremove}]">
<$fieldmangler>
<$action-sendmessage $message="tm-add-tag" $param=<<newTag>>/>
<$action-sendmessage $message="tm-remove-tag" $param=<<oldTag>>/>
</$fieldmangler>
</$list>
Click me!
</$button>
</$set>
</$set>
</td>
</tr>
<tr>
<td>
</td>
<td>
<$list filter="[all[shadows+tiddlers]tag{!!tagtoremove}]">
<li><$link>{{!!title}}</$link></li>
</$list>
</td>
<td>
</td>
<td>
<$list filter="[all[shadows+tiddlers]tag{!!tagtoadd}]">
<li><$link>{{!!title}}</$link></li>
</$list>
</td>
<td>
</td>
</tr>
</table>
```

**Comment by flibbles** [comment] 2019-09-02 10:59
I think this issue is ready to be closed. Tiddlywiki does propagate tag name updates now.

For those looking for a more comprehensive solution, [the Relink plugin](https://flibbles.github.io/tw5-relink/) is now available, and is being maintained. It handles propagating renamed tiddler events to many other places, such as transclusion, links, widgets,...

**Comment by pmario** [comment] 2021-02-12 18:44
@Jermolene ... +1 for closing this issue. See flibbles comment!

**Comment by Jermolene** [comment] 2021-02-13 12:13
Thanks @pmario @flibbles

**Closed by Jermolene** 2021-02-13 12:13 UTC
Labels: improvement

**Comment by ozboomer** [comment] 2022-03-19 23:46
> I think this issue is ready to be closed. Tiddlywiki does propagate tag name updates now.

Admittedly, I'm new to using TW5... but I've been through the documentation and I can't find any mechanism for renaming tags... or any sort of 'search and replace'.

P'raps you could give an example of how tags can be renamed... or at least a pointer to where it's mentioned as a function in the docs...

Thanks.

**Comment by flibbles** [comment] 2022-03-20 01:05
You just rename the tiddler which has the tag's name. There'll be a little checkbox which'll pop up asking if you want to rename all tags and lists linking to this tiddler. Check it before you save and voila.

**Comment by ozboomer** [comment] 2022-03-20 03:22
> You just rename the tiddler which has the tag's name. There'll be a little checkbox which'll pop up asking if you want to rename all tags and lists linking to this tiddler. Check it before you save and voila.

@flibbles - Thanks for the clues.  However, in some cases, there are tags that are _just tags_ and have no tiddlers with the same name.

This has led me onto a (roundabout) method that seems to work:-

- Consider a tag: 'computer_gear' that is applied to a number of tiddlers.  

- Enter the tag 'computer_gear' in the sidebar's 'Speed Search' field... and a list of the number of matches is displayed near the right end of the 'Speed Search' field.  Selecting the pulldown there shows the 'Title matches' (for tiddlers) and 'All matches' (for tiddlers and tags).

- Depending on your conventions for describing/defining tiddlers and/or tags, you can go to each tiddler shown _(? or maybe a filter could be set-up to form a 'collection' of tiddlers with which you can work?  I still need to study how filters work)_ and add the new tag, 'computer', so the tiddler has both the 'computer_gear' and 'computer' tags.  At that time, you can delete the 'computer_gear' tag... and you've dealt with one tiddler.

- Repeat the above with each of the matching tiddlers... and when you remove the last occurrence of the 'old' tag from a tiddler, the old tag is gone.

Again, it's a roundabout way of doing things... and speaks volumes for ensuring you always create a tiddler when you create a tag...  for documentation and so your solution will always work :)

**Comment by flibbles** [comment] 2022-03-20 04:11
That works I suppose

OR

You can just create a "computer_gear" tiddler for a hot second, rename it to "computer", and then delete it. I do that sometimes.
