### ISSUE TITLE
[BUG] SideBar shadow widgets no longer rendered when open as a tiddler

### ISSUE THREAD

**Issue by fairplay** [Jermolene/TiddlyWiki5#6369] opened 2021-12-24 14:38 UTC
**Describe the bug**
Not sure if it is a bug, but it's rather strange for intended behavior.
When SideBar tiddler is opened (e.g. $:/core/ui/SideBar/Open) https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FSideBar%2FOpen it looks like code instead of execution result.

**Expected behavior**
Should be rendered the same way as in SideBar, as it works in 5.1.23

----

With bisection I found that this behavior was introduced in commit cce18d8e2e34e8334df30ed2ad6ff9f81311c6d4

**Comment by btheado** [comment] 2021-12-24 20:29
The change is related to the [cascade functionality](https://tiddlywiki.com/#Cascades) introduced in 5.2.1. In particular see
https://tiddlywiki.com/#View%20Template%20Body%20Cascade which has this:

> If the tiddler title starts with any of a list of known system tiddler prefixes, use the template $:/core/ui/ViewTemplate/body/code to display the body as preformatted code

I think the idea was that certain system tiddlers (i.e. the pagetemplate) cause trouble when viewed. Probably many system tiddlers like the one you mention are useful to see in view mode rather than code mode.

For your own TW instance you can remove the feature by removing the `$:/tags/ViewTemplateBodyFilter` tag from https://tiddlywiki.com/#%24%3A%2Fconfig%2FViewTemplateBodyFilters%2Fsystem. Or you can refine the filter in that tiddler to cause it to match fewer of the system tiddlers.

Yet another option is to create a new tiddler and transclude the system tiddler (i.e. `{{$:/core/ui/SideBar/Open}}`) you are insterested in seeing rendered. By transcluding it, it will no longer match the filter.

I wonder if it would be useful to add a button to the `$:/core/ui/ViewTemplate/body/code` template which will toggle between code and render mode.

**Comment by kookma** [comment] 2021-12-25 04:24
@btheado explained in details what is going one and explained the possible solution!
I want to add one more solution!
You can create your own cascade filter to display the content of sidebar tabs as before.

* download  [myconfig_ViewTemplateBodyFilters_sidebar.zip](https://github.com/Jermolene/TiddlyWiki5/files/7775453/myconfig_ViewTemplateBodyFilters_sidebar.zip) and unzip then drag and drop into https://tiddlywiki.com/ to give a try!

>  This solution tells Cascades to show rendered tiddler body as before (treat sidebar tabs like normal tiddler) for sidebar tabs when they are opened in the story river
> 
> ```
> [tag[$:/tags/SideBar]then[$:/core/ui/ViewTemplate/body/default]]
> ```
> 
> 

Note that,  your config tiddler has
* tag: `$:/tags/ViewTemplateBodyFilter`
* list-before `$:/config/ViewTemplateBodyFilters/system`

**Comment by fairplay** [comment] 2021-12-25 13:27
Thank you! Your config works great.

Without this functionality Krystal plugin was broken, and now it's restored.

**Comment by Jermolene** [comment] 2022-01-03 16:41
Thanks @fairplay. I'm reopening this because although you've got a workaround I think this is a problematic regression that would be worth a systematic fix if we can.

The motivation for the change was that prior to v5.2.1, viewing certain system tiddlers such as `$:/core/ui/PageTemplate` would cause confusing visual artefacts and many others would appear to be blank even though they contain significant content.

In v5.2.1, we use the cascade mechanism to force a raw code template for certain system tiddlers:

```
[prefix[$:/boot/]]
[prefix[$:/config/]]
[prefix[$:/core/]!field:title[$:/core/readme]!field:title[$:/core/icon]]
[prefix[$:/info/]]
[prefix[$:/language/]]
[prefix[$:/languages/]]
[prefix[$:/snippets/]]
[prefix[$:/state/]]
[prefix[$:/status/]]
[prefix[$:/info/]]
[prefix[$:/temp/]] +[limit[1]then[$:/core/ui/ViewTemplate/body/code]]
```

Line breaks added for readability.

The problematic part is `[prefix[$:/core/]!field:title[$:/core/readme]!field:title[$:/core/icon]]` which selects all tiddlers prefixed `$:/core/` apart from `$:/core/readme` and `$:/core/icon`. A narrow fix for this problem would be the following tweak, which excludes tiddlers starting `$:/core/ui/`

```
[prefix[$:/core/]!field:title[$:/core/readme]!field:title[$:/core/icon]!prefix[$:/core/ui/]]
```

However, that excludes `$:/core/ui/PageTemplate`, and some other tiddlers that are known to be problematic such as `$:/core/save/all`.

The best I can see at the moment is the following:

```
[prefix[$:/core/macros]]
[prefix[$:/core/save/]]
[prefix[$:/core/templates/]]
[prefix[$:/core/ui/]split[/]count[]compare:number:eq[4]]
```

The final line causes tiddlers of the form `$:/core/ui/*` to be displayed as code only if the `*` doesn't contain a slash.

**Comment by Jermolene** [comment] 2022-01-03 16:42
Note that at present, thanks to this same problem, v5.2.1 doesn't display the core images correctly when opened directly in the story river.

**Closed** 2022-01-03 16:42 UTC
