### ISSUE TITLE
System tiddler link parser should be more selective

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#1767] opened 2015-06-01 20:05 UTC
Some parsing error caused by this.  

```
^^$:/foo^^
```

Similar problems occur for subscript, strikethrough etc of "$:...".

I discovered it when putting a system tiddler title in superscript inside a table which caused more obvious consequences (the row after gets doubled etc)

**Comment by pmario** [comment] 2015-06-02 15:55
workaround: `asdf^^$:/foo ^^` add a space in front of the trailing `^^`

**Comment by Jermolene** [comment] 2015-06-02 16:00
Hi @twMat the problem is that `^^` is valid as part of a system tiddler title, and so is interpreted as such, rather than as the terminator of the superscript.

The best workaround is to use explicit double square brackets around the link:

```
^^[[$:/foo]]^^
```

**Comment by twMat** [comment] 2015-06-02 20:40
I was mostly reporting what I thought was an error, but thank you both for the workarounds.

Interesting to learn there are different rules for allowed characters in system tiddlers vs regular tiddlers. (I'm sure there are reasons tho, not asking for explanation.)

Issue closed.

**Comment by pmario** [comment] 2015-06-03 08:05
>... Interesting to learn there are different rules for allowed characters in system tiddlers vs regular tiddlers. (I'm sure there are reasons tho, not asking for explanation.)

:) It's not about characters allowed in tiddler names. It's about automatic SystemTiddlerLink detection. 

There is a rule [syslink.js](https://github.com/Jermolene/TiddlyWiki5/blob/master/core/modules/parsers/wikiparser/rules/syslink.js) that detects system tiddlers. It basically applies these rules: 

   1. starting with a literal `$:`
   2. then any number of character not a whitespace, `<` or  `|`
   3. closing with anything that is, again, not a whitespace, `<` or  `|`

As Jeremy wrote `^^` and basically everything except `whitespace < |` are allowed for system tiddlers to be recogniced as automatic WikiLinks.

--------

"Techy" details 

It was introduced in January 2015. see: https://github.com/Jermolene/TiddlyWiki5/pull/1341
The actual implementation is here: https://github.com/Jermolene/TiddlyWiki5/commit/b43d4a33d6408d1855d1b410195083062ac64e9f

**Comment by twMat** [comment] 2015-06-03 20:18
Thanks Mario! 

I'm thinking, perhaps the standard formatting characters should not be recognized as automatic WikiLinks then? Is there a greater need for those special characters to be allowed as systemTiddlerTitles? It is of course *less common* to want to format systemtiddlertitles than common tiddlerstitles, but not unlikely, especially in texts *about* TW.

Particularly, I think it is reasonable that if a string is prefixed with the first pair (the "opening pair") in a standard formatting (e.g ^^ or // and with no blankspace after), then it is very likely that any occurence of an *identical pair* of characters is in deed the closing pair. The idea to design these formatters as double+double to begin with is, I must presume, to make them distinguished and unlikely to be used for other things such as titles.

Further, I think that people creating system tiddlers, i.e not the typical noob, are familiar enough with TW to avoid using these double characters as part of a title.

Ok, I'm mostly reacting to the inconsistency - but there may well be reasons I don't know/understand. I've stated my case and will not push on the matter.

**Comment by Jermolene** [comment] 2015-06-07 12:48
> I'm thinking, perhaps the standard formatting characters should not be recognized as automatic WikiLinks then? Is there a greater need for those special characters to be allowed as systemTiddlerTitles? 

@twMat I think you're correct, the regexp for matching system tiddler titles is being too greedy. I've amended the title of this ticket accordingly

**Closed** 2015-06-24 08:25 UTC
Labels: bug
