### ISSUE TITLE
When editing a tiddler body, the focus is repeatedly moved to the tiddler title field

### ISSUE THREAD

**Issue by simonbaird** [Jermolene/TiddlyWiki5#1527] opened 2015-02-25 14:01 UTC
Here's my analysis:
While editing, when the body text is changed it triggers a re-render, I presume to update the preview panel. The re-render of the title widget hits `if(this.editFocus === "true")` in core/modules/widgets/edit-text.js and steals the focus from the content text area.

The title focus and select should be done only when the tiddler is first opened in edit mode, not every time it's re-rendered.

c0834583 is related, but I think something has changed after that to make it happen, since the problem seems to be not present in 5.1.7.

I'm seeing this in all browsers, (i.e. Chrome, Firefox & Safari on OSX).

**Comment by inmysocks** [comment] 2015-02-25 19:23
I just noticed this in the prerelease as well. It doesn't happen in the older versions of the prerelease I have sitting around.

**Comment by aelocson** [comment] 2015-02-26 20:01
I don't understand why, but this has been caused by the addition of a link widget to the edit template in commit fdc635007b70588fe17c06ff018e5bce824f4949.

**Comment by simonbaird** [comment] 2015-02-27 03:55
@aelocson Confirmed. With that commit reverted it works fine for me.

I made a pull request with the revert, but feel free to ignore if an actual fix is likely to come soon.

This issue is a major blocker I think since TW is essentially unusable until it's fixed.

**Comment by Jermolene** [comment] 2015-02-27 18:27
Fixed by #1533

**Closed by Jermolene** 2015-02-27 18:27 UTC
