### ISSUE TITLE
External links to local files with relative paths don't work on the server edition

### ISSUE THREAD

**Issue by hyphz** [Jermolene/TiddlyWiki5#2506] opened 2016-07-21 16:45 UTC
If the server edition is being used, then links to local files on relative paths using the [ext] syntax do not work.

Linking to a local file with (for example) [ext[..\filename.txt]] causes the clicked link to link to http://127.0.0.1/../filename.txt which the server does not serve up and thus gives a blank page.

Linking to a local file with [ext[file://..\filename.txt]] creates the file link, but the browser is not aware of the relative path TiddlyWiki is running from, so it attempts to read the local file /filename.txt .

**Comment by Jermolene** [comment] 2016-07-22 10:48
Thanks @hyphz -- I think this is a duplicate of #1000?

**Closed by Jermolene** 2016-07-22 10:48 UTC
