### ISSUE TITLE
Accessing NavigatorWidget by JavaScript

### ISSUE THREAD

**Issue by donmor** [Jermolene/TiddlyWiki5#6519] opened 2022-03-08 13:58 UTC
I'm trying to make draft tiddlers with some text content using JavaScript injecting. Current implementation is:
```
//                                                                                                                 /--- This widget node is NavigatorWidget, where the "tm-new-tiddler" listener is attached to
$tw.pageWidgetNode.children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].dispatchEvent({type: "tm-new-tiddler", paramObject: {text: "123456"}})
```
Now I wonder if there's a better implementation than this. At least a shortcut to that `NavigatorWidget` instead of a bunch of `.children[0]`s.

**Comment by pmario** [comment] 2022-03-08 15:51
Hi, I think you should describe your usecase in plain text. I'm not really sure, what you want to achieve.

**Comment by donmor** [comment] 2022-03-08 16:03
Oops. Basically I want to create a draft tiddler by running that script, just as if clicking the "+" button. And additionally, make it possible to create drafts from specific text.

**Comment by pmario** [comment] 2022-03-08 16:55
The code you are using is extremely error prone. If there would be any changes to the [PageTemplate](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FPageTemplate), which contains the navigator widget, the code will probably cause an exception. ... 

If we a user or core devs ever decide to add a new widget before the `<$navigator` widget as shown in the link, the code will fail. ... 

In which "context" is your js-code executed. How is your plugin / code activated?

Plugin authors usually implement new widgets, if we want to have access to the "widget tree", to send messages.

**Comment by donmor** [comment] 2022-03-08 17:01
Or is there another way to invoke "new tiddler" with custom text filled in?

**Comment by donmor** [comment] 2022-03-08 17:08
Hmmmmmmm.. I'll try it. Maybe more source-viewing needed XD

**Comment by pmario** [comment] 2022-03-08 17:13
I think, the mechanism you want to use is the right thing to do, because the tm-new-tiddler event will do _all the right things_ ... The only problem is, that it is a bit brittle at the moment.

**Comment by saqimtiaz** [comment] 2022-03-08 17:17
Adding a tiddler: 

`$tw.wiki.addTiddler(new $tw.Tiddler({title:"a",text:"b"}));`

Modifying a tiddler:
```

var storyListTiddler = $tw.wiki.getTiddler("$:/StoryList");
var storylist = storyListTiddler.fields.list;
<!--modify storylist--> 
$tw.wiki.addTiddler(new $tw.Tiddler(storyListTiddler,{list: newListValue}));

```

**Comment by pmario** [comment] 2022-03-08 17:18
>One option is to directly create the draft tiddler from JavaScript, add it to the wiki and then insert it into the storylist. Drafts are tiddlers with the draft.of field pointing to the tiddler they are a draft of.

I did think about that too.. But that's also kind of hacky. As I wrote, using the tm-new-tiddler message is the right thing to do. It's using the mechanism, that was designed to do exactly that. ... The problem is the "hacky" activation.

**Comment by Jermolene** [comment] 2022-03-08 17:20
As @donmor has found, it is not practical to send `tm-new-tiddler` messages from outside of the widget tree. The approach @saqimtiaz shows is the best way to go at the moment.

**Comment by saqimtiaz** [comment] 2022-03-08 17:20
> I did think about that too.. But that's also kind of hacky. As I wrote, using the tm-new-tiddler message is the right thing to do. It's using the mechanism, that was designed to do exactly that. ... The problem is the "hacky" activation.

Neither is a clean choice and it would depend on the details of the intended use case. However I would personally prefer directly creating the tiddler rather than trusting the brittleness of locating the navigator widget.

If adding a plugin to the wiki is acceptable:
* write a lightweight widget that saves a reference to itself at $tw.eventEmitter
* use this widget in a tiddler tagged to be included in the page template
* use $tw.eventEmitter to dispatch events to be intercepted by the navigator.

**Comment by pmario** [comment] 2022-03-08 17:22
>Neither is a clean choice and it would depend on the details of the intended use case. However I would personally prefer directly creating the tiddler rather than trusting the brittleness of locating the navigator widget.

That's right.

**Comment by saqimtiaz** [comment] 2022-03-08 17:34
> Will it be an easy approach to that NavigatorWidget in the $tw object tree in future versions? So that we can use that to push messages or manually add the draft if in previous versions.

I think we are more likely to end up with an alternative API rather than direct access to the NavigatorWidget. However, none of these changes should be expected in the near future.

**Comment by Jermolene** [comment] 2022-03-08 17:38
> Will it be an easy approach to that NavigatorWidget in the $tw object tree in future versions? So that we can use that to push messages or manually add the draft if in previous versions.

The design of TiddlyWiki allows for multiple navigator widgets to be active in different parts of the widget tree, so there is no singular navigator widget to locate.

**Comment by donmor** [comment] 2022-03-08 17:40
Or the children[0] hacks in a try-catch structure, then the manual fallback, i.e. new api in new version (if possible) >> direct access hack in try{} >> manual creating the draft tiddler, being fallback one by one.

**Comment by donmor** [comment] 2022-03-08 17:44
> > Will it be an easy approach to that NavigatorWidget in the $tw object tree in future versions? So that we can use that to push messages or manually add the draft if in previous versions.
> 
> The design of TiddlyWiki allows for multiple navigator widgets to be active in different parts of the widget tree, so there is no singular navigator widget to locate.

When I say the NavigatorWidget I actually means that one where the storylist was built.

**Comment by donmor** [comment] 2022-03-08 17:47
Currently it was a linkedlist-like structure from $tw.rootWidget to the "root" navigator I referred above.

**Comment by donmor** [comment] 2022-03-08 17:51
Or maybe an encapsuled function in somewhere under $tw that sends messages to the "root" navigator?

**Comment by Jermolene** [comment] 2022-03-08 18:14
Hi @donmor the trouble is that there isn't necessarily a single "root" navigator, because there can be multiple story rivers.

**Comment by donmor** [comment] 2022-03-08 23:05
Hmmmmmm so there could be multiple "+" buttons and corresponding story rivers?

**Comment by donmor** [comment] 2022-03-09 01:16
So is there a specific navigqtor that always exists and managed by $tw.wiki?

**Comment by donmor** [comment] 2022-03-09 03:13
I found this one: `new $tw.Story().stortNewTiddler(targetTitle)` but is TBD. So when will it be stuffed?

**Comment by saqimtiaz** [comment] 2022-03-09 15:30
@donmor we are likely moving towards the direction of deprecating a lot of logic in Story and Navigator in favour of wikitext affordances. As such, that method is more likely to be deprecated than it is to be implemented.

Here is another approach that you can consider, to invoke action strings and provide the navigator widget to handle them:
```
var actionString=`
<$navigator story="$:/StoryList" history="$:/HistoryList">
<$action-sendmessage $message="tm-new-tiddler" title="mytiddler" text="1234"/>
</$navigator>
`;
$tw.rootWidget.invokeActionString(actionString,$tw.rootWidget,null,{variable1: "a",variable2:"b"});
```

**Comment by donmor** [comment] 2022-03-09 16:58
I see... I'll try it out later.

**Comment by donmor** [comment] 2022-03-10 00:46
It works! THX a lot. BTW I found the way toperform this in TWC:
```
({fn: config.macros.newTiddler.onClickNewTiddler, getAttribute: function(attr){return this.sets[attr]}, sets: {"newTitle": "New Tiddler", "newTemplate": DEFAULT_EDIT_TEMPLATE, "newText": "123456"}}).fn();
```
It seems that TWC have no i18n stuff so it's ok to make `newTitle` hardcoded...

**Comment by donmor** [comment] 2022-04-10 06:34
Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler. It seems that attrs of a xml node can't accept those characters. Does anyone has workaround? Getting the WidgetNode and dispatch the event separately or try fetching from variables for example.

**Comment by pmario** [comment] 2022-04-10 06:48
>Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler.

That's not true. You only need to escape them in your js-function, if needed. But I'm not really sure what you do now. 

 > It seems that attrs of a xml node can't accept those characters. 

It seems you want to store something in a deprecated way. ... So again. please try to describe what you **want** to do and not how?

**Comment by saqimtiaz** [comment] 2022-04-10 06:51
> Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler. It seems that attrs of a xml node can't accept those characters. Does anyone has workaround? Getting the WidgetNode and dispatch the event separately or try fetching from variables for example.

If by XML node you mean the wikitext syntax for widgets, you can use triple quotes:

`<$action-sendmessage $message="tm-new-tiddler" title="""mytiddler""" text="""1234"""/>`

**Comment by donmor** [comment] 2022-04-10 07:31
> > Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler.
> 
> That's not true. You only need to escape them in your js-function, if needed. But I'm not really sure what you do now.
> 
> > It seems that attrs of a xml node can't accept those characters.
> 
> It seems you want to store something in a deprecated way. ... So again. please try to describe **what** you want to do and not how?

I want to create a draft tiddler with specific text by sending an event to the navigator widget, which is not accessible via $tw. Also, I want to import files by JS as if they were dran-n-dropped into the wiki, which also have to be triggered by a message to the navigator.

**Comment by donmor** [comment] 2022-04-10 07:32
> > Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler. It seems that attrs of a xml node can't accept those characters. Does anyone has workaround? Getting the WidgetNode and dispatch the event separately or try fetching from variables for example.
> 
> If by XML node you mean the wikitext syntax for widgets, you can use triple quotes:
> 
> `<$action-sendmessage $message="tm-new-tiddler" title="""mytiddler""" text="""1234"""/>`

Tried it out and it just drops all quots as if they haven't ever exist.

**Comment by donmor** [comment] 2022-04-10 07:40
Tried unwrapping the invokeActionString() and found that it created a `Widget` but not `NavigatorWidget`. `dispatchEvent` doesn't work on it.

**Comment by saqimtiaz** [comment] 2022-04-10 07:50
> Tried unwrapping the invokeActionString() and found that it created a `Widget` but not `NavigatorWidget`. `dispatchEvent` doesn't work on it.

As previously discussed, you need to wrap the actions in a navigator widget, see https://github.com/Jermolene/TiddlyWiki5/issues/6519#issuecomment-1063043078

**Comment by saqimtiaz** [comment] 2022-04-10 07:50
> > > Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler. It seems that attrs of a xml node can't accept those characters. Does anyone has workaround? Getting the WidgetNode and dispatch the event separately or try fetching from variables for example.
> > 
> > 
> > If by XML node you mean the wikitext syntax for widgets, you can use triple quotes:
> > `<$action-sendmessage $message="tm-new-tiddler" title="""mytiddler""" text="""1234"""/>`
> 
> Tried it out and it just drops all quots as if they haven't ever exist.

Can you please point me at your code?

**Comment by donmor** [comment] 2022-04-10 07:52
The `Widget` created by `invokeActionString()` does has a child (`widget.children[0]`), which is an `ElementWidget` but not `SendMessageWidget` from `$action-sendmessage`. But `widget.children[0].children[0]` IS a NavigatorWidget, weird enough...

**Comment by donmor** [comment] 2022-04-10 07:53
> > > > Guys here's a new problem: text containing quots(") and some other characters can't go into a new tiddler. It seems that attrs of a xml node can't accept those characters. Does anyone has workaround? Getting the WidgetNode and dispatch the event separately or try fetching from variables for example.
> > > 
> > > 
> > > If by XML node you mean the wikitext syntax for widgets, you can use triple quotes:
> > > `<$action-sendmessage $message="tm-new-tiddler" title="""mytiddler""" text="""1234"""/>`
> > 
> > 
> > Tried it out and it just drops all quots as if they haven't ever exist.
> 
> Can you please point me at your code?

```
tw.rootWidget.invokeActionString('<$navigator story="$:/StoryList" history="$:/HistoryList"><$action-sendmessage $message="tm-new-tiddler" text="""123""" /></$navigator>', $tw.rootWidget, null, {});
```

**Comment by saqimtiaz** [comment] 2022-04-10 07:55
So are you saying that the quotes are not present in the tiddler when running the following code?
```
$tw.rootWidget.invokeActionString('<$navigator story="$:/StoryList" history="$:/HistoryList"><$action-sendmessage $message="tm-new-tiddler" text="""This is some text with "quotes" 123""" /></$navigator>', $tw.rootWidget, null, {});
```
This works correctly for me in Chrome if executed from the browser console.

**Comment by saqimtiaz** [comment] 2022-04-10 07:57
Otherwise I suggest just directly creating the tiddler and then showing it in the story, see https://github.com/Jermolene/TiddlyWiki5/issues/6519#issuecomment-1062013859

**Comment by donmor** [comment] 2022-04-10 07:58
> Otherwise I suggest just directly creating the tiddler and then showing it in the story, see [#6519 (comment)](https://github.com/Jermolene/TiddlyWiki5/issues/6519#issuecomment-1062013859)

Not working for me, weird enough... BTW I'm using edge chromium 100 on ubuntu.

**Comment by saqimtiaz** [comment] 2022-04-10 08:08
> > Otherwise I suggest just directly creating the tiddler and then showing it in the story, see [#6519 (comment)](https://github.com/Jermolene/TiddlyWiki5/issues/6519#issuecomment-1062013859)
> 
> Not working for me, weird enough... BTW I'm using edge chromium 100 on ubuntu.

Can you please post a screenshot of the tiddler created when running this code in the browser console:
```
$tw.rootWidget.invokeActionString('<$navigator story="$:/StoryList" history="$:/HistoryList"><$action-sendmessage $message="tm-new-tiddler" text="""This is some text with "quotes" 123""" /></$navigator>', $tw.rootWidget, null, {});
```

The expected output is as follows, notice that the triple quotes are delimiters are not dropped by the quotes in the body of the tiddler are preserved:

![image](https://user-images.githubusercontent.com/68092/162608896-c621fae8-db51-418c-9e2f-08469cb67e8c.png)

**Comment by donmor** [comment] 2022-04-10 08:19
Hey I found a new way to get a `NavigatorWidget`:
```JavaScript
var w0 = $tw.wiki.makeWidget($tw.wiki.parseText("text/vnd.tiddlywiki", '<$navigator story=\"$:/StoryList\" history=\"$:/HistoryList\"></$navigator>', {parentWidget: $tw.rootWidget, document: document}), {parentWidget: $tw.rootWidget, document: document, variables: {}});
w0.render(document.createElement("div"),null);
w0.children[0].children[0].dispatchEvent({type: "tm-new-tiddler", param: {text: "\"123\""}});
```

**Comment by donmor** [comment] 2022-04-10 08:43
And this can add a png image to `$:/Import` tiddler using `w0` previously created:
```
w0.children[0].children[0].dispatchEvent({type: "tm-import-tiddlers", param: JSON.stringify([{title: "jojo_tbc.png", type: "image/png", text: "iVBORw0KGgoAAAANSUhEUgAAASAAAABJCAMAAACq0QuUAAAAA3NCSVQICAjb4U/gAAADAFBMVEX4APgA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wBCAACEAAC1AAD3hAD3tQCIupbuAAAAAXRSTlMAQObYZgAAAAlwSFlzAAASdAAAEnQB3mYfeAAAA5hJREFUeJztnOmWgyAMhfv+r5yIo7IlkLCop+3Y3B8tsgh8hADWmddLF0Aj0bTxMUAtwQ5oWT7djK8VGKCmNjorwGKANG18DFBDOx8DpOvgY4BUgQFqKvAxQJoCHwOkKPIxQLISHwMkCgxQU4SPAZJE+BggQZSPAarF+KzwJL3CA4ockJPL2IKPASpjG3yepMNbpBN41dGczCJLF/NcPgUggYUWufwGn1sAPZkPJSDBUOMYHwNUxy0/wuc0oB+ZYJyAQEOLWv49HxzMdxXQv+Uz2m5GoN4K1YD4JugdDsjpdeCoHVQabncFqMQhxixzfBDRhcIAITiqY+OuJ6Yq5gYK3wZorDFEnA9iq/+prN76OjSk8eycQMVDjjjNp5oRMaFRtmVwqSDWt25JaIme9TygmVFTbHrvf8OIelM4YW91WBiBiZafAnTGQdPZQMObgTjNI7hicnNrwtIs2TPfI+vuxAUbnTCgkkAJRLw+YUBkErD2+o4EEJUpAR+ag9Ae5YEivZFHkfoeAB0vmuwxLu6FDyc40/K3AYqtgtzDlQOqh5pfYOjwms2GO2mEZJ2pskCM1oDXAPGtkJR8cpPoczuPJANKWA5orjCaIuw77DHxDOEOe+9JQgIEsfgabjDR7KbJSJcnjxnJyFVAe4TrA/IzqcgQAQV/nSpLNfDYfFvk35W7vwhoaij8p8sX4Rvz8JZupwj7Dq8KoLCg0Zshm7hVqeT40wJQ7Ss665ZwxR8lzqyX6TNPpOidXTYmVxaRAYV+OZJMkrKdxiwuTUzHAQH9zoF7AE1MMpcH1eW1mYxpmAl0/GI273Vc+A7uNnSHrGvJ3UBMwGQSDqI/kt0c6SNv90VAw4TSXofvXRigqtCR0WF0O5AprPRu6AHlGpAeUYibi5VfcdJFTH1R/GA6OskcWdmJHyQuSboTm3ZiVcCBJWGuBumQQMA31Ghf4BqgCULS7pWsMUjCrJ/t49gpTZz9lQc+OqBXqam1vmopHd7O0f0z6jxFrMLCKwnf1qV7dQOgZxPq/JRRBsV3Wr5uWtypOwA9mtAtgJ48yTq/yBch9a2x5xK6DdBTCekvAEmAND4lIXiSDgJ6LA203ss0QB1A9WvAD9LWvVb0iwaGCBmgjhvqOKxfVSZkgGQZoJ7aD0ZM9ieZXQE5t326Ld8pA9TTyLnkt+V/oTBAqgDsn5u0FU9un27H98oA9WSAOjJAPRmgrgxQTwboD4uHvFZUepdZAAAAAElFTkSuQmCC"}])});

```

**Comment by donmor** [comment] 2022-04-10 08:46
So is this method to get `NavigationWidget`(`w0.children[0].children[0]`) stable?

**Comment by donmor** [comment] 2022-04-10 08:51
Now I found why `invokeActionString()` can work:
```
Widget.prototype.invokeActions = function(triggeringWidget,event) {
	var handled = false;
	// For each child widget
	for(var t=0; t<this.children.length; t++) {
		var child = this.children[t];
		// Invoke the child if it is an action widget
		if(child.invokeAction) {
			child.refreshSelf();
			if(child.invokeAction(triggeringWidget,event)) {
				handled = true;
			}
		}
		// Propagate through through the child if it permits it
		if(child.allowActionPropagation() && child.invokeActions(triggeringWidget,event)) {
			handled = true;
		}
	}
	return handled;
};

/*
Invoke the action widgets defined in a string
*/
Widget.prototype.invokeActionString = function(actions,triggeringWidget,event,variables) {
	actions = actions || "";
	var parser = this.wiki.parseText("text/vnd.tiddlywiki",actions,{
			parentWidget: this,
			document: this.document
		}),
		widgetNode = this.wiki.makeWidget(parser,{
			parentWidget: this,
			document: this.document,
			variables: variables
		});
	var container = this.document.createElement("div");
	widgetNode.render(container,null);
	return widgetNode.invokeActions(this,event);
};
```

**Comment by donmor** [comment] 2022-04-10 09:15
Now I'll try describing my version of code:
```JavaScript
var w0 = $tw.wiki.makeWidget($tw.wiki.parseText("text/vnd.tiddlywiki", '<$navigator story=\"$:/StoryList\" history=\"$:/HistoryList\" />', {parentWidget: $tw.rootWidget, document: document}), {parentWidget: $tw.rootWidget, document: document, variables: {}});
w0.render(document.createElement("div"),null);
w0.children[0].children[0].dispatchEvent({type: "tm-new-tiddler", param: {text: "\"123\""}});
```
The `$navigator` stuff creates an empty `NavigatorWidget` in `w0` > `ElementWidget`. Since we are going to call `dispatchEvent` directly on `NavigatorWidget`, the inner `$action-sendmessage` that used to create a `SendMessageElement` is useless and thus removed. Now that we have full access to `NavigatorWidget` via `w0.children[0].children[0]`, we can dispatch any event it can handle, not only `tm-new-tiddler` but also `tm-import-tiddlers`. Q.E.D.

**Comment by pmario** [comment] 2022-04-10 12:58
>So is this method to get NavigationWidget(w0.children[0].children[0]) stable?

I think it should be, since your function creates the whole "tree".

**Comment by saqimtiaz** [comment] 2022-12-26 14:57
@donmor @Jermolene I believe this issue can be closed.

**Comment by Jermolene** [comment] 2022-12-30 21:04
Thanks @saqimtiaz

**Closed by Jermolene** 2022-12-30 21:04 UTC
