### ISSUE TITLE
Trailing space character in title should be removed

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#3483] opened 2018-10-15 09:56 UTC
Serious issue: A suffixing space character in the title is apparently not removed when saving the tiddler. So "Foo " and "Foo" appear the same, both as titles in view mode and edit mode and also as tag pills.

**Proposal**: Automatic removal of trailing space characters in title when saving a tiddler and in tags when creating one.

----

Update based on discussion below: The proposal here concerns whether *tags* should be trimmed or not. The concern about *tiddler titles* turned out to be an edge case for #751 (albeit probably the most common one) 

My position regarding tags is that they should follow the same rules as titles... and IMO they should both have trailing space characters trimmed or at least marked out, e.g in pink, in edit mode.

**Comment by Jermolene** [comment] 2018-10-15 09:57
Hi @twMat I remember this coming up before -- @pmario do you recall the discussion?

**Comment by twMat** [comment] 2018-10-15 10:00
@Jermolene - You're not thinknig of #3368 are you? I don't think this is the same issue, but maybe it is? This case with a simple space character seems much more critical.

**Comment by Jermolene** [comment] 2018-10-15 10:10
I think that that is the same problem: the dangers of invisible characters in tiddler titles. 

I also found #1791 "TW overwrites existing tiddler without a warning -> data loss"

There are a lot of variants of this: there are Unicode characters that look the same but have different codes; in some situations one can't distinguish between two spaces or a single space.

Anyhow, I can't quite duplicate the problem you're seeing here. When I create a tiddler with a trailing space in the title it is automatically trimmed. Are you perhaps creating the tiddler programmatically?

**Comment by Jermolene** [comment] 2018-10-15 10:37
I think #751 does cover the same problem. It sounds like the new thing here is the discussion about tag entry, and whether they should be trimmed too.

**Comment by pmario** [comment] 2018-10-16 06:41
My opinion didn't change. see  #751, #2726, #1791,

I think the next version of TW should consistently remove whitespace,
We missed the opportunity for tw5.

**Comment by AnthonyMuscio** [comment] 2018-10-17 02:53
Regardless of core functions handling leading and trailing spaces could we not provide a mechanism to simply remove them from a given string?. I have had mysterious spaces appearing in macros and at the time would have being happy to just have a method to remove them.

**Comment by hoelzro** [comment] 2018-10-25 03:19
As long as we're gathering issues related to trailing whitespace, I reported and fixed #2850 last year.

**Comment by diego898** [comment] 2019-12-12 20:40
As tags are tiddlers too, Im reporting here that someone on the groups reported a problem where they accidently tagged their tiddler with a space before the correct string. 

I think trailing and leading white spaces should be removed!

**Comment by pmario** [comment] 2019-12-13 07:56
@diego898  This problem was fixed in a different way. see: remove &nbsp from tag pill in edit mode #4366

**Comment by diego898** [comment] 2019-12-13 13:41
hey @pmario, if I go to tw.com and remove `TableOfContents` tag from HelloThere, and add a new tag that is: ` TableOfContents` the tag dropdown behaves correctly, but I finish adding my new tag, I can successfully add a tag with space and HelloThere is removed from the ToC.

**Comment by pmario** [comment] 2019-12-13 13:52
I know, but that is a wontfix because of backwards compatibility. See my post above https://github.com/Jermolene/TiddlyWiki5/issues/3483#issuecomment-430119183

**Comment by kookma** [comment] 2021-03-13 05:07
Hi @Jermolene 
Working with Tiddlywiki on Node.JS I experienced creating tiddlers with leading and trailing space which cause several issues on Windows system for example you cannot delete them!

### Example

1. create a TW on Node.js
2. Open the wiki and create a sample tiddler as below

```
<$tiddler tiddler="  xx/temp/ExampleCodingMode  ">
  <$radio value="Completed">&nbsp;Completed</$radio>&ensp;
  <$radio value="New">&nbsp;New</$radio>
  <$radio value="All">&nbsp;Show all</$radio>
</$tiddler>
```
3. Save and click on one radio button! A new file with leading space will be created!

It is required to trim leading and trailing space before creating the tiddler

Note: The example provided by @pmario over the Google Forum!

**Comment by pmario** [comment] 2021-03-13 08:19
I'm sorry but the new forum doesn't allow to edit posts. I did immediately post a corrected version in a new post, https://groups.google.com/g/tiddlywiki/c/O1oylX4H97k/m/8T87g6_gAgAJ

**Comment by kookma** [comment] 2021-03-13 09:46
Thank you @pmario 
Yes I got the correct code! But please not TW shall trim trailing and leading spaces!
It is very common to pass such tiddler name by mistake! So TW core shall tale care of such spaces!

**Comment by kookma** [comment] 2021-03-13 09:50
> Serious issue: A suffixing space character in the title is apparently not removed when saving the tiddler. So "Foo " and "Foo" appear the same, both as titles in view mode and edit mode and also as tag pills.

No only trailing and leading spaces in title and tags but also in field name shall be trimmed!
This true for all widgets create such elements! e.g $action-setfield, ...

**Comment by pmario** [comment] 2021-03-13 10:56
see this and linked comments https://github.com/Jermolene/TiddlyWiki5/issues/3483#issuecomment-430119183 

> Working with Tiddlywiki on Node.JS I experienced creating tiddlers with leading and trailing space which cause several issues on Windows system for example you cannot delete them!

What does it mean: "You can not delete them?"  ... Delete with TW or deleting them with the file explorer?

**Comment by Jermolene** [comment] 2021-03-13 12:57
Thanks @kookma @pmario I think that this might be a regression from #5113 and subsequent fixes. @joshuafontany it seems reasonable for the system to trim spaces from generated filenames, what do you think?

**Comment by joshuafontany** [comment] 2021-03-14 03:54
@pmario @Jermolene Good catch! I agree, this is a bug that seriously affects filenames/disk-access on Win* systems. Let me catch up on the whole thread and I should be able to get a PR together this week.

**Comment by joshuafontany** [comment] 2021-03-25 02:33
@Jermolene I included these fixes alongside the fix for the OriginalFilesystemPath bugs.

https://github.com/Jermolene/TiddlyWiki5/pull/5504

Best,
Joshua F

**Comment by Jermolene** [comment] 2021-03-26 08:40
Thanks @joshuafontany

**Closed** 2021-03-26 08:40 UTC
