### ISSUE TITLE
How can I help to translate Tiddlywiki to Persian (Farsi)?

### ISSUE THREAD

**Issue by amirography** [Jermolene/TiddlyWiki5#2976] opened 2017-09-14 07:00 UTC
Hi. I see that there have been developments on **RTL**, and Hebrew. I'm a native **Persian** user. I would love to be able to help with translating TW. How can I help? Where can I start?

**Comment by amirography** [comment] 2017-09-14 09:19
Ok, I found the 5.1.14 version of translator file. I'm at 191 out of 859. I'm not sure how it works. But I hope I just can do a delta translation for the pre-release, if possible.

**Comment by pmario** [comment] 2017-09-14 09:24
Hi, ... Welcome to the club :)

There are 2 ways to create translations. 

 a) using the [translators edition](http://tiddlywiki.com/prerelease/editions/translators/)
 b) using a [developers workflow](http://tiddlywiki.com/dev/#How%20to%20create%20a%20translation%20for%20TiddlyWiki)

For option a) ... Just download the translators edition ... change the english texts ... save and send the result to Jeremy :)

If you are familiar with nodejs and github, you can use option b)

**Comment by pmario** [comment] 2017-09-14 09:26
... :) ... just saw your second post .... 

> I'm not sure how it works. But I hope I just can do a delta translation for the pre-release, if possible.

Just translate the english texts. ... When finished just zip the version and drop the zip file here

**Comment by amirography** [comment] 2017-09-14 09:42
Sure thing! I'm working fast. I think I can knock it off in two days. Maybe a day for proofreading is needed. 

How about the delta thing? Can I just translate the difference between pre-release and current versions? Or should I copy everything manually?

**Comment by pmario** [comment] 2017-09-14 10:01
>How about the delta thing? 
Deltas are easier. ... 

>Can I just translate the difference between pre-release and current versions? 

You should go with the prerelease now. .... There's a dropdown "Show all strings" which will let you go for the new texts

>Or should I copy everything manually?

no. .... When we have a Persian version you'll be able to select it from the language dropdown, and just change the new texts.

**Comment by pmario** [comment] 2017-09-14 10:05
If there are just a view changes, it may be even possible to edit them directly in guthub. You can directly change the  .multids files. 

example: 

core english version for button texts: https://github.com/Jermolene/TiddlyWiki5/blob/master/core/language/en-GB/Buttons.multids
german version, which I contributed: https://github.com/Jermolene/TiddlyWiki5/blob/master/languages/de-DE/Buttons.multids

With the next build, they will be implemented. ... If some texts are missing in the translation, the core texts are shown. ... So the wiki should be still usable.

**Comment by amirography** [comment] 2017-09-14 16:38
[MyTranslation.zip](https://github.com/Jermolene/TiddlyWiki5/files/1303719/MyTranslation.zip)
Ok, here is the translation for these prioritized sections:
* Buttons
* Control Panel
* Date
* Edit Template
* Getting Started
* Import
* Miscellaneous
* Search
* Sidebar
* Tiddler Info

For practical reasons I will not translate more for this version so that I can test the translated version and find the problems and inconsistencies first and then I will continue for the full translation. 
**Note:** RTL is vital.

**Comment by MoHD20** [comment] 2017-09-15 23:14
@pmario I've decided to translate Tiddlywiki to Arabic and chose the Github method but I'm kind of stuck at step 9. I can't find `quick-bld.sh` at all.. can you explain this step further?

**Comment by pmario** [comment] 2017-09-16 01:04
@MoHD20 
There's a second repo: https://github.com/Jermolene/build.jermolene.github.io that contains the quich-bld.sh

**Comment by pmario** [comment] 2017-09-16 01:06
>For practical reasons I will not translate more for this version so that I can test the translated version and find the problems and inconsistencies first and then I will continue for the full translation.
Note: RTL is vital.

cool! @Jermolene ... There's a Persian translation in the zip from amirography

**Comment by Jermolene** [comment] 2017-09-16 15:06
Hi @amirography thank you! I'm not an Arabic speaker, but the text *looks* great :)

What would be the correct country codes to use (ie the equivalent of "en-GB" or "us-GB")? It looks Persian is "fa", but what if any would be the appropriate country code? We also need an appropriate flag image; for the other languages I've used the SVG images available on Wikipedia. Could you point me at the appropriate one?

<img width="1318" alt="screenshot 2017-09-16 16 06 22" src="https://user-images.githubusercontent.com/174761/30513304-02e2f34a-9af9-11e7-8f23-f77f4c1fe2c5.png">

**Comment by Jermolene** [comment] 2017-09-16 15:07
Hi @MoHD20 thank you for the offer - I'll need the same country code and flag information for your translation as well.

**Comment by amirography** [comment] 2017-09-16 15:41
Hi @Jermolene. Thanks a lot! "fa-IR" is the standard. Also [this](https://upload.wikimedia.org/wikipedia/commons/a/a5/Flag_of_Iran_%281964%29.svg) is the most generally accepted flag which does not represent any particular regim and has been accepted by most people.

**Comment by amirography** [comment] 2017-09-16 16:59
BTW, The photo you sent @Jermolene is not RTL. 
A question, when will it be available to use?

**Comment by Jermolene** [comment] 2017-09-16 18:41
Apologies, I got interrupted, and will fix things up tomorrow.

**Comment by Jermolene** [comment] 2017-09-17 18:41
Thanks @amirography. I've committed the translation here 3c62ef0d71dac8a2167e22d0d389a972ea08cef8 and the errant RTL flag here 148a4eea4d58ed92daaf04ac47b0847888f3b562

I've also uploaded a new prerelease that includes the translation. You can try it out here:

http://tiddlywiki.com/prerelease/editions/full

The translators edition has been updated too, and is now preloaded with the Persian translation:

http://tiddlywiki.com/prerelease/editions/translators

If you have any updates, download that updated translators edition, make your changes while saving locally, and then resubmit it here (or you can upload it to TiddlySpot or somewhere).

Many thanks again for the contribution, much appreciated.

<img width="1385" alt="screenshot 2017-09-17 19 39 46" src="https://user-images.githubusercontent.com/174761/30523811-fc6f3dba-9bdf-11e7-8287-55fb06b6d532.png">

**Comment by amirography** [comment] 2017-09-17 19:31
Hi! Thanks a lot!
It works great!
There is a small problem with its rendering in Firefox 55.0.3. It seems like a counter-indent.  
![30](https://user-images.githubusercontent.com/28535608/30524204-50182c14-9c04-11e7-8aad-5098ea6960f1.PNG)
Also, the font that I specified for the editor does not load in the editor box. but loads everywhere else. 
These problems are specified to firefox. The chrome version does not manifest the same problems.

**Comment by Jermolene** [comment] 2017-09-17 20:04
Hi @amirography that looks like it might be an issue with the CodeMirror plugin; worth having a look at their repo to see if there are any known issues. The version of CodeMirror we're using is quite old so it may be time to upgrade...

**Comment by kookma** [comment] 2018-11-22 09:42
@Jermolene 
Just to note that, it would be essential to have the texteditor in RTL also!
Right now the the text editor direction is LTR.

One more point
In View mode, the title is displayed at left and close to tiddler control buttons! I recommend to move the control buttons to the left!

@amirography 
The open tab is "باز کن" while here it means the active tiddlers in story river!
Any way thank you for your efforts. TW in Persian :-)

**Comment by kookma** [comment] 2018-11-23 15:38
Thank you @Jermolene,
Yes it is in correct direction now!

Best
Mohammad

**Comment by Jermolene** [comment] 2018-11-23 15:40
Hi @kookma great stuff.

**Comment by kookma** [comment] 2020-03-30 21:16
> Hi @kookma
> 
> > Just to note that, it would be essential to have the texteditor in RTL also!
> > Right now the the text editor direction is LTR.
> 
> The "full" edition includes the CodeMirror plugin, which doesn't support RTL mode. If you load the Persian translation in a wiki without the CodeMirror plugin then RTL editing should work (see below).
> 
> <img alt="image" width="1056" src="https://user-images.githubusercontent.com/174761/48943370-eed62580-ef1a-11e8-9cd2-e671173d5cda.png">

RTL uses right side to start writing and absolutely uses right sidebar! Why sidebar is on the left!

**Comment by Jermolene** [comment] 2020-04-02 16:25
Hi @kookma the RTL support at the moment just sets the `dir` attribute on the document element to "rtl", thus applying to the entire page. We don't do anything special about the sidebar/story ordering, it just gets changed automatically because of the way that CSS works in RTL mode.

If we did want to manually reorder things we can, of course, write CSS that only kicks in when RTL mode is engaged.

**Comment by kookma** [comment] 2020-04-02 16:32
Thank you @Jermolene 

So, the RTL layout as you said does not work properly. I am ready to put time and create a real RTL layout! My question is do you recommend to go through a new theme or I should do something else?

I should note that, having an RTL TW does not mean to have both interface and tiddlers in RTL. For example we work in MS Word 2016 and the whole interface is in English but when preparing docs, you can develop in right-to-left, and MSWord shows docs in RTL, print and preview in RTL.

My proposal is to have the required elements in RTL first and NOT the whole interface.

I just want to be advised what is the correct approach to tackle?

**Comment by Jermolene** [comment] 2020-04-02 18:09
Hi @kookma that's great, I'd love to see the RTL support get better. It's important to me that we do our best to support the widest possible geographic and cultural audience, as an English speaking software developer it's the very least I can do.

Setting `dir=RTL` on the document element was really just an experiment, we definitely need more flexibility. Perhaps there are two separable problems:

* Adjusting the TW interface when the interface language is RTL
* Adjusting individual tiddlers when that tiddler is RTL (as we discussed on the mailing list)

I think you're proposing the second option. Are they mutually exclusive?

**Comment by kookma** [comment] 2020-04-02 19:04
Yes, I think the second approach is simpler and more efficient for now! I am not sure, but I thought a theme may help! 




In the first phase these elements may need to adjusted for RTL support

- Title and subtitle
- sidebar is fine and it is on the right
- Sidebar tabs contents need to be displayed right-to-left
- tiddler
- title /subtitle/tag pill
-edit and view toolbar
-textarea
-fields

So, for now, control panel and some other elements may remain intact

**Comment by Jermolene** [comment] 2020-04-02 19:08
Hi @kookma the current approach is that the document RTL setting is determined by the "text-direction" field of the currently selected language plugin. I think that makes sense: to me, every theme should be compatible with the RTL setting, I'd prefer to keep them independent, so that RTL users have the same selection of themes as LTR users.

For per-tiddler RTL settings, would the approach we discussed on the mailing list be a good start? (I can't find the link at the moment).

**Comment by kookma** [comment] 2020-04-02 20:05
The link is https://groups.google.com/d/msg/tiddlywiki/pCbeguJHusQ/rWKRYdSZBgAJ

The document RTL means both interface and tiddler. So, it seems one theme should cover both RTL and LTR layouts? a bit complex.

I know very little JavaScript! and I am not sure if the approach you propose need any JS programming or not!

**Comment by kookma** [comment] 2020-04-04 07:38
@Jermolene 
I appreciate to let me know how to start. It seems for now you prefer the second approach!

**Comment by Jermolene** [comment] 2020-04-04 08:24
Hi @kookma there seem to be two approaches because they serve different needs:

* If the user interface is translated into an RTL language then we need to set the document direction to RTL so that the interface displays correctly. This is what we have already, of course, and you've raised the additional question of whether the sidebar should be moved back to the right when in RTL mode
* Independent of the user interface language, if an individual tiddler is written in a language that requires RTL or LTR then we need to display that tiddler appropriately. There's a few different ways to do this. We used a special field in the prototype, but the trouble with that approach is that it doesn't work with transclusion: if an LTR tiddler transcludes a RTL tiddler as a block, then one would expect the transcluded content to be displayed RTL. Transclusions don't intrinsically generate any DOM elements, so there's nowhere to put the RTL attribute.

**Comment by kookma** [comment] 2020-04-04 12:07
@Jermolene 
I have reviewed in part the current RTL version comes from fa-IR translation. To reproduce
- create a new wiki using

`tiddlywiki test01 --init server`

- add the Persian language to tiddlywiki.info file

```
    "languages": [
        "fa-IR"
    ],
```
- start new wiki like below
`tiddlywiki test01 --server`




---

**Results**


**The whole view**
![Image 024](https://user-images.githubusercontent.com/830394/78446517-c45bb700-768e-11ea-8468-8e94287bc63e.png)

1. fine
2. not correct, the sidebar should be at the right, not to the scroll bar (vertical)
3. tiddler in RTL generally looks fine but title and viewt oolbar controls (see below)
4. English tiddler is also rendered RTL (not correct)

---

**Create new tiddler**

![Image 018](https://user-images.githubusercontent.com/830394/78449946-34b70800-7690-11ea-8f8d-64c412c8451d.png)


1. position of title not correct, it should be at right edge
2. view toolbar buttons shall be on the left
3. fine
4. fine
5. fine (but I recommend the LTR as they are in English)
6. Persian is appear RTL and it is okay
7. display of type is correct (see below)
8. looks fine (see below)
9. looks fine
10. Button should be one line


---


**RTL tiddler**

![Image 016](https://user-images.githubusercontent.com/830394/78449953-44365100-7690-11ea-8d7e-2ef0d6e9709c.png)

1. the buttons shall be moved to left
2. title shall be at the right
3. the date and time are mixed!! It needs to display first date and then time
4. fine


---

**The More button**

![Image 025](https://user-images.githubusercontent.com/830394/78449998-a000da00-7690-11ea-9043-0dbc84730439.png)

1. button itself works fine but position is wrong- move view toolbar buttons to left
2. icon is correct
3 the whole contents shall be moved to right (position of icon right-most)



---

**Type**

![Image 019](https://user-images.githubusercontent.com/830394/78450037-f1a96480-7690-11ea-86e3-7dcf6b81b519.png)

1. This fine, may be a translated content is more suitable here
2. Persian is accepted and error raised, but does TW can accept Persian type here?


---

**Adding field**

![Image 020](https://user-images.githubusercontent.com/830394/78450068-2b7a6b00-7691-11ea-9ef9-4a0de0366740.png)

The filed name seems has to be in English, Persian are not allowed, if so does we need this part like this or keep it LTR?


---

**The Sidebar**
 
![Image 017](https://user-images.githubusercontent.com/830394/78450164-dd199c00-7691-11ea-85ca-21f13d12ea79.png)

1. It is correct
2. It is correct
3. It is correct
4. -
5. The position is in question, where to put the scrollbar, but the right seems coorect! We need to test in action
6. It is correct
7. It is correct
8. It is correct but the margin to right edge seems to be adjusted

**Comment by kookma** [comment] 2020-04-04 12:09
> Hi @kookma there seem to be two approaches because they serve different needs:
> 
> * Independent of the user interface language, if an individual tiddler is written in a language that requires RTL or LTR then we need to display that tiddler appropriately. There's a few different ways to do this. We used a special field in the prototype, but the trouble with that approach is that it doesn't work with transclusion: if an LTR tiddler transcludes a RTL tiddler as a block, then one would expect the transcluded content to be displayed RTL. Transclusions don't intrinsically generate any DOM elements, so there's nowhere to put the RTL attribute.

This is hard to decide! Always there is mixed type of text e.g in an RTL tiddler you may have English paragraph! It is not true to say a Persian wiki only contains Persian text. Always you have both English and Persian, so, transclusion may be always a question how to do it

**Comment by Jermolene** [comment] 2020-04-04 15:37
Thanks @kookma I think many of the glitches you've cited might have the same fundamental cause: that we don't have a way to mark a tiddler as explicitly LTR or RTL and use that setting for display regardless of how the tiddler is transcluded. As discussed, there's no obvious way to fix that given the way that the transclude widget works.

So, one possibility might be (a) to nominate a system field to hold the RTL/LTR setting of a tiddler and (b) to create a new macro that transcludes the target tiddler while wrapping it in a DIV that respects the RTL/LTR setting.

Another option might be to introduce a shortcut markup for `<div direction="rtl">` that authors use directly. For example we could add a pragma `\dir rtl` that could be used at the top of a tiddler.

**Comment by kookma** [comment] 2020-04-04 20:22
> So, one possibility might be (a) to nominate a system field to hold the RTL/LTR setting of a tiddler and (b) to create a new macro that transcludes the target tiddler while wrapping it in a DIV that respects the RTL/LTR setting.

I think this is a simple approach and we can go through this. The solution provided in https://groups.google.com/d/msg/tiddlywiki/pCbeguJHusQ/rWKRYdSZBgAJ works! I have created an experimental wiki here: http://kookma.rtl.tiddlyspot.com/

The good point is your solution is similar the way MsWord works. MSWord has a button on the toolsbar lets you switch text direction while your typing inside your document (.docx file). If you see the example I can write both in English and Persian without problem.

I am studding other html5+css3 tools support both RTL/LTR and it seems there are other elements to be considered like paddings, margins, ...

**Comment by kookma** [comment] 2020-04-05 11:58
@Jermolene 

In https://tiddlywiki.com/prerelease/ creating a new tiddler with below content, render the div from right-to-left

```
<div dir="rtl">
این یک متن پارسی است
</div>
```
You Said it is possible to have a system field to set direction! Assuming Tiddlywiki stores a tiddler in a div, then does a system field cause to produce a similar div like above for a tiddler with a field called _dir_ and value equal to "rtl"?

**Comment by Jermolene** [comment] 2020-04-06 14:57
Hi @kookma 

TiddlyWiki does indeed display individual tiddlers within DIVs in the story river. The problem is that if one of those tiddlers transcludes another tiddler then there won't be a DIV wrapping the content, and so nowhere to attach the "dir=rtl" setting. Hence my suggestion of a new pragma that one would type at the top of a tiddler to switch it to RTL mode. It would work by wrapping the content in a DIV with the direction setting, and so when transcluding such tiddlers the setting would be respected. Typing the extra `\dir rtl` would be tedious, but one could switch the default by setting the direction on the document element.

**Comment by kookma** [comment] 2020-04-06 17:31
@Jermolene 
I got your point! I would appreciate if I can have the possibility to make some experiments on this approach.

**Comment by Jermolene** [comment] 2020-04-07 15:29
Hi @kookma I've created an experimental PR to explore some possible changes: see #4541

**Comment by kookma** [comment] 2020-04-07 15:51
Many thanks @Jermolene. I will follow the new PR https://github.com/Jermolene/TiddlyWiki5/pull/4541

**Comment by pmario** [comment] 2023-06-09 14:38
@Jermolene .. I think this issue can be closed. The contribution has been merged 

and the problems discussed later in the issue imo are superseeded by: **Bidirectional text improvements** #4541

**Closed** 2023-06-09 14:50 UTC
