### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hitam4450** [Jermolene/TiddlyWiki5#4806] opened 2020-08-11 18:19 UTC
Hi to All,

I just try to figure out, how to use the tiddlywiki5 !

After editing a Tidller i save the content by pressing Änderungen speichern, but it doesn't save the content at all!

I tried it over and over again! No changes are saved!

I think this is the worst piece of software I ever used!

i just deleted everything..not worth to spent a a single minute more !

beat regards, hitam 4450

**Comment by Jermolene** [comment] 2020-08-11 18:35
Hi @hitam4450 I'm sorry you've had a bad experience with TiddlyWiki so far. The way that it works is different from most other software and so the learning curve can be steep.

If you don't configure another saving technique, clicking "save changes" should download a fresh copy of the TiddlyWiki HTML file to your "downloads" folder. To see the changes you have to load the file into the browser; refreshing the original file will not show the changes.

There are much more convenient ways of saving changes, but they all require some degree of installation or setup. What OS/browser do you use?

**Comment by hitam4450** [comment] 2020-08-11 18:44
Hi, 

I am in UBUNTU 18.04 LTS and use FF  79!

**Comment by hitam4450** [comment] 2020-08-11 18:53
Before i used woas, which put everything in one single file and in 10 different files for a small piece of information !
what a waste of resources !

**Comment by adithya-badidey** [comment] 2020-08-12 10:06
@hitam4450 Please read this https://tiddlywiki.com/#GettingStarted. You will find a list of saving mechanisms. Pick up the saving mechanism which suits you and install. Timimi is what I use.

Also, please post further questions about TiddlyWiki at https://groups.google.com/g/tiddlywiki

**Comment by fkohrt** [comment] 2020-08-14 04:22
> I think this is the worst piece of software I ever used!
> 
> i just deleted everything..not worth to spent a a single minute more !

@hitam4450 Sorry to be the random person who won't provide an answer but still steps in.

For a moment, please imagine reading and digesting your frustration, being unable to help because there are not enough information. Maybe you lost information? Or spent quite some time you did not enjoy? That's unfortunate, and I'm truly sorry, because I know how that feels. But at the same time I am angry, because dealing with this kind of "feedback" eventually leads to nothing but exhaustion and harm (read on here: [The struggles of an open source maintainer](http://antirez.com/news/129)). This is a wonderful and extraordinary piece of software with a lovely community, so let's not forget that there are people on both ends :)

**Comment by hitam4450** [comment] 2020-08-16 11:31
Hi, it's good thing that you @fkohrt voiced your opinion !

However, for me it is the most user Unfriendly and most difficult software i ever used in my life !

I am in Software development for more the 30 years and appreciate very much with Open Source community and idea!

i know what i am talking about !

regards, hitam4450

**Comment by hitam4450** [comment] 2020-08-16 11:43
Now a new shit happens:

All German special characters and Umlauts appear several times in the description!

**Comment by dubiouscript** [comment] 2020-08-17 09:11
wrt : https://github.com/Jermolene/TiddlyWiki5/issues/4806#issuecomment-674516395

**Comment by twMat** [comment] 2020-08-17 18:35
@hitam4450 

based on that image of yours, it looks like you're using TiddlyWikiClassic rather than TiddlyWiki5. They are two different systems, not compatible. This repository is about TW5.

**Comment by hitam4450** [comment] 2020-08-18 06:46
@twMat Thanks for your feedback ! I Ia m very much sure, that i started with TW5 and NOT the classic version !

It remains the most disappointing and the most frustration piece of software  i ever used!

regards, hitam4450

**Comment by twMat** [comment] 2020-08-18 07:36
@hitam4450 

>It remains the most disappointing and the most frustration piece of software i ever used!

That's impressive. Considering that TW probably has thousands of happy users, they must either collectively succeed by pure luck - or it's you who are doing something wrong. As someone who [quote] "knows what you're talking about" you're not really showing it so far because you haven't detailed what steps you're taking to make the errors occur.

Here is my best recommendation if you actually want to succeed with this instead of whining unconstructively: Start with a new empty TW by downloading it from tiddlywiki.com (i.e by clicking the blue button in the GettingStarted tiddler - you've presumably already done this several times, of course.) If you **thereafter describe the steps you take**, we might be able to help you. **BUT** github is the wrong place for such a discussion so please close this thread here and instead start a thread in https://groups.google.com/forum/#!forum/tiddlywiki

Otherwise, I guess the conclusion simply would be that TW isn't for you. Luckily there are many "note taking/wiki/etc" alternatives.

**Comment by hitam4450** [comment] 2020-08-18 09:27
@twMat 
Thanks for repeated feedback ! 

I am discussing software issues and not personal liking's here !

regards, hitam4450

**Comment by twMat** [comment] 2020-08-18 10:01
So, after 30 years in software dev and participation in open source projects, the detailed description you give so others have a chance to reproduce your problem, is:

>I downloaded the empty.html file, installed Timimi saving extensions and started adding conten !
>That's all what i did !

OK, since I'm unable to help you based on those details, I'll avoid standing in the way of the flocks of developers who will surely jump in now.

@Jermolene - this is a troll IMO. Please close this thread.

**Comment by rmunn** [comment] 2020-09-02 06:51
@hitam4450 - After installing the Timimi extension, did you follow the instructions at https://ibnishak.github.io/Timimi/#Important%3A%20Post%20Update%2FInstallation%20instructions to install its native-host component? Because it won't work without the native host.

As for the repeating special characters, that's an encoding problem, where UTF-8 characters are read as Latin-1. What encoding is your browser set to? Mine is set to UTF-8 (which should be the default) and I can't reproduce the issue: accented characters work just fine for me with the Timimi extension. If you have changed your encoding to Latin-1 or Windows-1252 then that's the problem.

**Comment by pmario** [comment] 2023-12-10 01:19
@Jermolene -- IMO this issue can be closed. The feedback provided is not actionable.

**Comment by Jermolene** [comment] 2023-12-10 14:11
Thank you @pmario

**Closed by Jermolene** 2023-12-10 14:11 UTC
