### ISSUE TITLE
tabbing into inputs should close other popups

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#4076] opened 2019-07-07 15:12 UTC
if we tab into an input - like from the tags input to the editor - when the input gets focus it should close all other popups (before it eventually opens its own popup)

**Comment by twMat** [comment] 2019-07-07 17:00
dupe of #2959 ? ...in deed annoying. Ioften dont see any search results because there's apparently some popup open.

**Comment by pmario** [comment] 2019-07-07 17:02
@twMat #2959 can be closed if PR: cancel open popups when input gets focus #4078 is merged

**Comment by twMat** [comment] 2019-07-07 18:04
@pmario , yes if merged I'll close it, thanks.

**Comment by BurningTreeC** [comment] 2019-07-14 15:16
@twMat @pmario - #4089 is merged which is basically #4078 , please test on the current prerelease, I believe we can close the issue

**Comment by twMat** [comment] 2019-07-14 17:42
Thank you for this @BurningTreeC . I've closed #2959

**Closed** 2019-07-15 03:46 UTC
