### ISSUE TITLE
Editor dysfunction with Firefox when TW5 is hosted in an iframe

### ISSUE THREAD

**Issue by jeau** [Jermolene/TiddlyWiki5#2801] opened 2017-03-13 20:30 UTC
This bug appear with Firefox (OSX) when TW5 is hosted in an iframe. 

When editing, the tags generated by the editor buttons do not appear. However, they are present,  after the save action they are active to format text.

I had identified the problem when I worked on a TW5 application for sandstorm,
https://github.com/jeau/tiddlywiki-sandstorm
I thought it existed only in this context but it is not true

There is no problem with Chrome or Safari

**Comment by sukima** [comment] 2017-03-14 02:17
I am not sure if I'm able to reproduce. I'm using FireFox on OSX using [this JSBin][1].

And you either offer steps to reproduce using [the JSBin][1] and/or edit the HTML to make it happen?

[1]: http://jsbin.com/cuwecad/edit?output

**Comment by sukima** [comment] 2017-03-14 02:19
For more context I had difficulty understanding the followinf:

>tags generated by the editor buttons

And proceeded to try editing a tiddler and added tags which seemed to eork.

**Comment by jeau** [comment] 2017-03-14 07:39
Sorry. My English is bad.

I noticed the same bug with your JS Bin.

My version of Firefox is 52, OSX Sierra 10.12.2
I have disabled Firefox modules

- created a new Titddler
- edit it
- write a first title and I click the button H1 -> the ! don't appear
- then a first item of a list, I click on the list button, -> the * does not appear
- etc.
- save this new Tiddler, formatting is visible (title and list)

If I edit again, I see the tags, but I have the same problem with new editing

**Comment by pmario** [comment] 2017-03-14 10:48
@jeau 

I can confirm the behaviour, that you describe in https://github.com/Jermolene/TiddlyWiki5/issues/2801#issuecomment-286344454 with FF52 and windows 10 using jsbin from @sukima.

It seems to be a problem with an iframe inside an iframe. The new editor toolbar needs the textarea to be an iframe. So the nested iframe scenario may cause the trouble.

**Comment by twMat** [comment] 2017-03-15 07:35
On **Win10 FF52** I can **not** replicate the problem. Here is a (non-)demo: http://twiniframe.tiddlyspot.com/

To make sure I performed the correct test:

A tiddler shows an iframe with another TW.
In the iframed TW, I enter a tiddlers edit mode...
...and create a new tag (confirm by clicking "Add")
The OP says this tag is not visible in edit mode. But yes visible when saving the tid, i.e view mode.

**Comment by pmario** [comment] 2017-03-15 09:05
@twMat ... your example is not, what the OP describes. Sandstorm is a hosting platform, that works similar to JSBin. The example, that sukima posted.

**Comment by edrex** [comment] 2018-01-09 22:07
@jeau, it's really cool that you worked on packaging TW5 for @sandstorm-io! I can confirm this is still an issue with Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0.

It seem like this should be debugged further using a development-mode configuration of TW5 where the source files can be edited, served in an iframe. Can someone point the way to whatever documentation exists for how to debug/hack on the core?

**Comment by AlexCid** [comment] 2019-08-22 15:41
Hello,
The issue seems to be still there - I have the exact same problem with Firefox 68.0.2 on Linux, when using TiddlyDrive to save my wiki. Has there been any progress since this issue was first discovered ? Or any workaround (except using Chrome / Chromium) ?

**Comment by pmario** [comment] 2023-12-08 21:19
@jeau @AlexCid -- I did test the JSBin with FF 120 --  It seems the problem is gone. 

@jeau Can you please close the issue, **if it is also fixed for you**

**Comment by AlexCid** [comment] 2023-12-09 09:20
@pmario Thanks for the heads-up, the problem seems to be gone for me too (using FF 120). I haven't use TW in a while, I might come back to it now that this works better :)

**Comment by jeau** [comment] 2023-12-09 20:20
@pmario thanks, 

sounds good to me
I'm now closing this issue

**Closed** 2023-12-09 20:21 UTC
