### ISSUE TITLE
Plugin request: auto-complete for fields

### ISSUE THREAD

**Issue by giffmex** [Jermolene/TiddlyWiki5#1549] opened 2015-02-28 20:58 UTC
Hi guys 
I don't know if this is a place for plugin requests. If not, sorry. But I can't imagine this being a core feature. I use a number of fields in a few of my TWs where there is only one item (as opposed to the list field which can have multiple items). It would really be great to be able to type into these fields and have autocomplete options based on content that other tiddlers have in the same field.

Is this possible? Is this desirable for anyone else besides me? I would imagine it would be a popular feature for those of us who use fields.

**Comment by Spangenhelm** [comment] 2015-03-06 23:25
Hi @giffmex your idea makes totally sense to me (as the drag'n'drop and autocomplete for tags etc..) to make tiddlywiki even easier and more fun to work with ;-)

**Comment by tobibeer** [comment] 2015-09-21 12:37
I also think this is a worthy core enhancement

**Comment by pmario** [comment] 2015-09-21 18:38
I think it's implemented already. At least partly. If you select the field input you get a dropdown, which is not filtered.

**Comment by tobibeer** [comment] 2015-09-21 19:39
Ah, I misread. I was thinking of field values when writing ...looking up existing options for a field of the same name.

As a wee optimization for the current implementation for the fieldname, the options could be filtered by what's already entered in the field-name input, equivalent to tags.

**Comment by pmario** [comment] 2015-09-21 20:13
> equivalent to tags.

yes

**Comment by danielo515** [comment] 2016-09-06 15:07
There are two things from my point of view:

1. Filtering the current list of fields, which is very needed.
1. Provide suggestion with what other tiddlers **contain on that field**. So if you have a category field, show a list of already existing categories contained on other fields.

Both make a lot of sense to me.

**Comment by pmario** [comment] 2016-09-06 19:03
>Both make a lot of sense to me.

yes, but that's probably plugin territory, since it heavily depends on the usecase.

**Comment by tobibeer** [comment] 2016-09-06 19:08
> since it heavily depends on the usecase

Why? This is quite general for me. I can't find the reference, but I've been calling for global field configuration tiddlers for a long time. Another option would be "filter values in edit mode" which can be set for any field ...or filter defining field names.

Why would I want a plugin to replace a crucial core component, such as field editing? I think this is generally the least preferred way to go about it. But maybe I'm mistaken, and it really isn't.

**Comment by pmario** [comment] 2016-09-06 19:59
I probably did misread Danielos intention for 

>Filtering the current list of fields, which is very needed.

IMO with "filtering" he meant, that the list should get shorter "as you type". Similar to the tag field. I'm ok with this functionality.

**Comment by danielo515** [comment] 2016-09-06 20:44
> IMO with "filtering" he meant, that the list should get shorter "as you type". Similar to the tag field. I'm ok with this functionality.

That's exactly what I meant, and what I understood from the title of the issue. Then I realized about the other feature once I read the description. 

Maybe the second one is not so essential, but the filtering it's definetively a must have.

**Comment by pmario** [comment] 2017-05-17 15:44
@Jermolene  ... label: "improvement"

**Comment by tobibeer** [comment] 2017-12-01 12:21
After all, I think this is a duplicate of #1448?

**Closed** 2022-02-15 16:06 UTC
