### ISSUE TITLE
Do we really want $:/StoryList to be synced? 

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#1744] opened 2015-05-18 13:57 UTC
Hello,

I am wondering why do we need the tiddler $:/StoryList be synced through any sincadaptor. It is just an state tiddler, and if we do not sync state tiddlers, why should we sync this one? This only makes sense for the fylesystem adaptor, so it should be managed as a "particular case" within this sync adapter, and not the other way round.

This is a very important feature if we want to move to a multi-user environment. We have solved the problem of suddenly UI changes without saving the state tiddlers, why not do the same for this?

**Comment by pmario** [comment] 2015-05-18 15:16
Yes. because it makes it possible to set Default tiddlers to the last state of the wiki. `[list[$:/StoryList]]` which is extremely useful. 

See: ControlPanel: Info: Basics: DefaultTiddlers  ... the button below the input area. 

IMO removing it would be a regression.

**Comment by pmario** [comment] 2015-05-18 15:18
But as you say, for multi user environment this may be a problem.

**Comment by Jermolene** [comment] 2015-05-18 16:30
Hi @danielo515 as @pmario says, `$:/StoryList` is not excluded from syncing intentionally so that it's possible to reference it in `$:/DefaultTiddlers`.

I don't understand what you mean by "This only makes sense for the fylesystem adaptor"?

**Comment by danielo515** [comment] 2015-05-18 16:31
Hello @pmario ,

This is only useful for one thing in one particular scenario. In fact, as far as I know every syncadaptor claims that the DefaulTiddlers does not works due to lazy loading. So at the end, even that is not working. As I said, this is only useful for the local node.js edition.

It IS a problem. I'm making experiments and changes to the couchdb adaptor (getting very fun) and this is really annoying. First because it raises lots of "version collision" errors, and at the end, when you get synced every user has to have the same tiddlers opened.

**Comment by Jermolene** [comment] 2015-05-18 16:37
> In fact, as far as I know every syncadaptor claims that the DefaulTiddlers does not works due to lazy loading

I don't think that's quite right. Don't forget that the TW HTML file has the values of tiddlers like `$:/DefaultTiddlers` and `$:/StoryList` baked in so that they are available at startup, before the initial sync.

> when you get synced every user has to have the same tiddlers opened.

I think there you are seeing the main issue with multi-user support at the moment, which is that the state tiddlers that are synced are shared between all users. We hide the impact of it by avoiding syncing as many tiddlers as we can, but the real solution is to be able to store personal state tiddlers in a separate personal "bag" on the server.

**Comment by danielo515** [comment] 2015-05-18 16:42
> I don't think that's quite right. Don't forget that the TW HTML file has the values of tiddlers like $:/DefaultTiddlers and $:/StoryList baked in so that they are available at startup, before the initial sync

In which case? This is only for node.js edition, which "builds" the html file before serving it. But if you have a wiki on tiddlyweb for example, and you change the value of $:/DefaultTiddlers or $:/StoryList, this change is saved to the server. But when you load again the wiki you will have the "hardcoded" or default value of $:/DefaultTiddlers and $:/StoryList until you sync them.

**Comment by Jermolene** [comment] 2015-05-18 16:49
Hi @danielo515 indeed, if one isn't using a baked HTML file then user tiddler values are not available at startup; the biggest impact is that plugins cannot be loaded. There's some motivation to fix that so that plugins can be loaded lazily.

**Comment by danielo515** [comment] 2015-05-18 17:00
> indeed, if one isn't using a baked HTML file then user tiddler values are not available at startup;

Then what is the point/benefit about syncing `$:/StoryList` back to the server except for the local node.js version?

**Comment by Jermolene** [comment] 2015-05-18 17:21
> Then what is the point/benefit about syncing `$:/StoryList` back to the server except for the local node.js version?

The motivation was indeed to get `[list[$:/StoryList]]` working in the Node.js client-server configuration.

**Comment by danielo515** [comment] 2015-05-19 07:06
Hello @Jermolene ,

You have ended answering your own question:

> I don't understand what you mean by "This only makes sense for the fylesystem adaptor"?

> The motivation was indeed to get [list[$:/StoryList]] working in the Node.js client-server configuration.

So the storyList only works properly on the node.js configuration, which requires the filesystem adaptor. That's why I think the StoryList should be managed as an exception on that particular configuration, and not as default.

**Comment by Jermolene** [comment] 2015-05-20 08:11
Hi @danielo515 

Saying "this only makes sense for the filesystem adaptor" is not in my mind the same as "the motivation for this change was the needs of users of the client-server edition". Syncing the storylist is not a bug, it is intentional. The fact that it causes problems in the couchdb adaptor needs to be fixed in the couchdb adaptor. If we just do a hack to stop the storylist being saved you'll end up hitting the same problem with some other tiddler.

**Comment by danielo515** [comment] 2015-05-20 10:08
Hello @Jermolene 

I know it is intentional. But is not a problem with the couch adaptor, it is a problem with all the adaptors that are not the filesystem one. In fact, this is a problem for any multi user scenario. Do you want all the users to share the same story list?

Anyway, this can be fixed with my proposal at #1746 , so every plugin will be able to decide if they want to sync that tiddler or not.

**Comment by Jermolene** [comment] 2015-05-24 16:27
Hi @danielo515 

> In fact, this is a problem for any multi user scenario. Do you want all the users to share the same story list?

As I said above, the problem isn't the handling of `$:/StoryList`, it's the handling of all state information that should be individual to a user session. The real solution is to be able to store personal state tiddlers in a separate personal "bag" on the server.

**Comment by danielo515** [comment] 2015-05-26 07:08
Hello,

What I'm experiencing with StoryList is that, once it is loaded all the tiddlers included in the list are loaded also. No matter what is on "Default Tiddlers". Is this normal? Why don't we use HistoryList instead for remembering previously opened tiddlers?

**Comment by Jermolene** [comment] 2015-05-27 12:48
Hi @danielo515 what do you mean by "once it is loaded"? 

There's not much that is special about `$:/StoryList`; it may be interesting to search across the repo for the string to see.

**Comment by pmario** [comment] 2018-05-28 11:26
Started a new one here: SyncFilter should build from certain tags instead of hardcoded #1746

So this 1 may be closed too!

**Comment by Jermolene** [comment] 2018-05-28 11:50
Thanks @pmario

**Closed by Jermolene** 2018-05-28 11:50 UTC
