### ISSUE TITLE
[BUG] Procedure defaults to \whitespace trim when imported

### ISSUE THREAD

**Issue by flibbles** [Jermolene/TiddlyWiki5#7909] opened 2023-12-25 22:05 UTC
### Describe the bug

When you import procedures, they have whitespace trim enabled by default.

### Expected behavior

Expected: This is *fancy* content
Results: This is*fancy*content

Is this expected behavior?

### To Reproduce

```
title: Target

\procedure test()
This is //fancy// content.
\end
```

```
title: Test

\import Target
<<test>>
```

### TiddlyWiki Configuration

- TiddlyWiki v5.3.3

**Comment by CodaCodr** [comment] 2023-12-26 00:20
https://talk.tiddlywiki.org/t/announcing-the-release-of-tiddlywiki-v5-3-2/8661/14

@Jermolene  Is this the simple STR we need finally?

**Comment by Jermolene** [comment] 2023-12-26 08:25
Thanks @flibbles 

@CodaCodr – what is STR?

**Comment by pmario** [comment] 2023-12-26 09:32
If `\define` is used instead of `\procedure` it works as expected. I think "define" and "procedure" should create the same behaviour if possible

**Comment by Jermolene** [comment] 2023-12-26 10:10
> I think "define" and "procedure" should create the same behaviour if possible

There is one intentional difference here: procedures inherit the `\whitespace trim` setting from the tiddler in which they are defined. I suspect that it is the implementation of that behaviour that is causing the problem here.

**Comment by CodaCodr** [comment] 2023-12-26 15:08
STR - steps to reproduce.

**Comment by Jermolene** [comment] 2024-02-07 15:01
Hi @flibbles I do think this is a bug, but it fell off my (rather fallible) radar and I haven't had a chance to investigate. I'm pretty sure it will be an issue with the mechanism for inheriting whitespace trim settings from the containing tiddler into its procedure definitions.

**Comment by pmario** [comment] 2024-03-10 14:37
I'm changing the wikitext syntax for the docs-macros at the moment.

This issue prevents me from changing `\define` to `\procedure` for these examples: https://tiddlywiki.com/#Macro%20Calls%20in%20WikiText%20(Examples)

**Comment by Jermolene** [comment] 2024-03-10 15:03
It turns out that the fix for this is straightforward: the code for the import pragma was passing true for "configTrimWhiteSpace" when parsing the tiddlers, which meant that "whitespace trim" was being applied to all parsed tiddlers. That matters with procedure definitions because they inherit the whitespace trim setting from the parent parser.

**Closed** 2024-03-10 15:03 UTC
