### ISSUE TITLE
tiddler relations?

### ISSUE THREAD

**Issue by christophvarga** [Jermolene/TiddlyWiki5#1326] opened 2015-01-05 19:47 UTC
what about a feature to set relations between tiddlers? 

i think of a possibility to define to which tiddlers the actual one is **related** to **and how** (i mean some kind of quality information like 'parent-child', how strong the relation is, equality, following in a row,...)
this feature should be as integrated as tags are, maybe this function can be merged within the tag field.

**to get an 'neighborhood' view would be so useful!**   what do you think?

and there is this actual add-on where you can make a map for each tiddler but this is just visually and not a reliable information. in the classic version there was a tagglytaggin add-on where relations between tags could have been set in a hierarchy manner.

**Comment by pmario** [comment] 2015-01-05 21:34
@felixhayashi 
all your links to tiddlymap seem to be broken.

**Comment by felixhayashi** [comment] 2015-01-05 21:56
Hi Mario, I am reorganizing at the moment :) Also the name changed as you noticed.

The proxy is now: bit.ly/tiddlymap

**Comment by felixhayashi** [comment] 2015-01-05 22:05
Hi @christophvarga,

> this feature should be as integrated as tags are, maybe this function can be merged within the tag field.

I would not use tags for modelling relationships

> to get a 'neighborhood' view would be so useful!

I implemented this. You can make every graph display neighbours but as an example go the search and enter "utils" all neighbours are gray. Click on a neighbour, the tiddler opens and the current tiddler is focussed and so on... with some animations :)

> and there is this actual add-on where you can make a map for each tiddler but this is just visually and not a reliable information.

Not sure if you mean my plugin but all information for relations is stored in json files in a really structured manner. Double click an edge to get an idea how the store looks like. I also wrote an API where other developers can use javascript to manipulate graphs and graph elements: bit.ly/tiddlymap_api. My plan is to allow other plugins to use this API to build and manipulate graphs by calculation.

Demo is at bit.ly/tiddlymap.

Careful it's beta.

-Felix

**Comment by tobibeer** [comment] 2015-01-06 01:22
Not sure, but this might be related to / addressing the original issue...

https://github.com/Jermolene/TiddlyWiki5/issues/1324

**Comment by Jermolene** [comment] 2015-01-06 14:02
Hi @christophvarga 

> i think of a possibility to define to which tiddlers the actual one is related to and how (i mean some kind of quality information like 'parent-child', how strong the relation is, equality, following in a row,...)
this feature should be as integrated as tags are, maybe this function can be merged within the tag field.

There are several ways to model relationships in TW5:

* Tagging a tiddler with the title of another tiddler. This sets up an acyclic graph of relationships (not purely hierarchical), and is used extensively in TW5 (for example, it's how the table of contents is rendered)
* Storing the title of a tiddler in a field
* Storing a list of titles in a field (eg the core `list` field)

>  in the classic version there was a tagglytagging

The mechanism of TagglyTagging are present in TW5, albeit we don't have the same user interface.

**Comment by christophvarga** [comment] 2015-01-07 12:17
thanks for your quick reply :)

@felixhayashi 
i totally meant your plugin and in this demo i understood what it is and can do the first time. GREAT!
i really love it in terms of make the information well structured (following an associative brain structure).
it is like having an additional access on the already existing wiki pieces

>tags: i didn't mean to use tags, just the same input field for clarity reasons (design wise)

an idea: as you can input the neighborhood information through the map (view) it would be also good to 
see it represented on the classic tiddler side. maybe as a simple and clear list which is only visible through the pull down symbol.
and also to be able to edit the relations quick as setting tags:  
 '>add neighbour (search query)  >define edge/type/quality/predicate'

the map tool then should take the information and render it in the map view so that both sides are perfectly synced.

you store the relations as independent information, did you think about storing it to each tiddler? (where is the tiddler pointing to and how)
my feeling is that this would make it clearer in structure, right?

as i learned that there are fields and the idea to expand that functionality (#1324), isn't there a way to combine those things?
semantic information - neighborhood information - map view of all related things

(@tobibeer)
#1324 is about almost the same thing but more technical as i understand it. 
i have to say that i didn't get the whole effect of how it would look like when i am using it. 
(@Jermolene)
i can not verify if the use of fields can help here (since i have no technical experience and need visible examples some times)


the point for me is that the graphical interface of the 'edit tiddler' section start to be overwhelming right now (for me). so every new kind of meta info input should be considered very carefully. 
e.g. can there be an universal input field for tags, relations, fields?


_

@felixhayashi again
i like to have this 'TiddlyMap' tab to turn the map on/off.

what about making the map on the right side a view of all the opened tiddlers. 
i didn't think it through, but i imagine the map as an actual imprint of everything what happens on the left and vise versa. both sides are more one thing which make the same but in a different view (map and text). one problem would be if one will create a static permaview and while dynamically moving through the content the last viewed will get lost. maybe it is good to have two independent sides..
 
comment on graphic design (is it too early to talk about that?): i would prefere when all the control elements are hidden when the map is not active. 
and they could be more decent in size, and color i think 




[i am just a user without technical skills, so please don't take me to serious ;) ]

**Comment by tobibeer** [comment] 2015-01-07 15:40
> you store the relations as independent information, did you think about storing it to each tiddler? (where is the tiddler pointing to and how)
> my feeling is that this would make it clearer in structure, right?

We need to distinguish two fundamentally distinct use-cases...
(and so should TiddlyMap, also see: https://github.com/felixhayashi/TW5-TiddlyMap/issues/14)

1. We model graphs that relate tiddlers.
    * with such a **view**, we model entirely independent relationships
        * different views of that kind are entirely independent, both in terms of nodes and edges
        * view **foo** could thus display relationships that view **bar** would **never** display
    * therefore, an update to the graph never updates a represented tiddler

2. We define a graph that represents (inherent) tiddler relations.
    * such a graph is completely tied to the underlying (standard) wiki relations, e.g.
        * tagging to
        * tagged by
        * linking to
        * linked by
        * listed in
        * listing
        * custom foo
        * inverse of custom foo
        * etc...
    * therefore, if such a **view** was editable, it would **always** update the corresponding tiddlers and their relations (which will work for things like "tagged" and "listed", but not "linked")
    * **views** based on this paradigm are **not** independent
        * if view **foo** updated relations also displayed in view **bar**, both would reflect the changes

**Comment by felixhayashi** [comment] 2015-01-07 18:58
Yes. I call the first type of relations "global" or "shared" and the latter "private". TiddlyMap stores global relations in a central path "[...]/edges/" and local edges are stored in a subpath of each view like "[...]/view/exampleview1/edges/". This is a common approach used in unix (e.g. /usr/bin and /usr/local/bin). When using TiddlyMap, a user has to decide whether to use a global or private approach.

A use case for private edges is e.g. isolated mind maps: No global edges are displayed and on the other hand the private edges are nowhere else displayed (not spamming the global edge pool).

If the edges should be displayed everywhere because they, as tobi puts it, describe the "(inherent) tiddler relations", then a global mode should be used.

Only one addition:

> different views of that kind are entirely independent, both in terms of nodes and edges

The problem is that tiddlywiki cannot create nodes with the same name, so independence of nodes is hard to achieve as we cannot create nodes with the same name. Even when using captions, a node is bound to a tiddler and the tiddler is global so I cannot prevent that a tiddler appears in another graph context if it matches the views filter.

-Felix

**Comment by christophvarga** [comment] 2015-01-12 18:37
>If you have good suggestions for layout, I am always happy, just file an issue.
@felixhayashi i don't know it it is good but what do you thing about making the buttons more step in the background visually somehow in that direction:
![tiddlymap test style](https://cloud.githubusercontent.com/assets/653247/5708559/7646f012-9a92-11e4-8a14-7bfebbd433d1.gif)

?

**Comment by felixhayashi** [comment] 2015-01-12 18:48
Hi @christophvarga,

thanks for the suggestion. Please create a new issue at the right repo. TiddlyMap related stuff should be posted in at the [TiddlyMap repo](https://github.com/felixhayashi/TW5-TiddlyMap/). If your topic deals with an idea that hasn't been mentioned yet, please create a new issue.

This means:

# Copy your post above
# go to the TiddlyMap repo.
# Create an issue named something like "Layout suggestion - Button suggestion"
# Paste what you posted above
# Come back to [this topic](https://github.com/Jermolene/TiddlyWiki5/issues/1326) and remove your last post.

-Felix

**Comment by felixhayashi** [comment] 2016-01-09 14:06
Think this issue can be closed

**Closed** 2016-04-30 16:24 UTC
