### ISSUE TITLE
[highlight-boxes] improve documentation readability

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyWiki5#3291] opened 2018-05-17 09:07 UTC
Hi, I'd like to add some colored highlighting boxes to the documentation on tiddlywiki.com
I was thinking about something like those [w3schools boxes](https://www.w3schools.com/js/default.asp) which work very well to point to the very important notes and to distinguish the type of the note by its color or shape

**Comment by pmario** [comment] 2018-05-17 09:50
For me the most important things for readability and understandability is **simplicity** and consistency. 
Especially in formatting.  

IMO We should try to make the existing possibilities easier accessable for contributors. _We may have too many of them already!_

 - see: https://tiddlywiki.com/#Tutorials has
    - It's "kind of" hardcoded. 

 - HelloThere https://tiddlywiki.com/#HelloThere has: 
    - Image Link Buttons
    - Corored Link Buttons
    - Quote Box

 - GettingStarted https://tiddlywiki.com/#GettingStarted  has:
    - A Warning Info box
    - A Blue Box

 - https://tiddlywiki.com/#addprefix%20Operator has:
    - Operator Info box

 - https://tiddlywiki.com/#addprefix%20Operator%20(Examples) has:
    - Example Info box

TW5 doc macros are defined here: https://tiddlywiki.com/#%24%3A%2Feditions%2Ftw5.com%2Fdoc-macros

**Comment by BurningTreeC** [comment] 2018-05-17 10:01
Thanks @pmario 

for me, for tiddlers that are not part of a group (the various widget doc tiddlers for example are one group) inconsistent styling is ok

for tiddlers that are part of a group I'm proposing such consistent highlighting of the important **text** notes like "note: to use this you need that"

the boxes of your examples are ok in my eyes, I'm talking about the info text in between those boxes. There are notes that are very important but can be overseen because they are between less important ones. To make them stand out, they could be framed like in the w3schools example (they do it very right)

**Comment by pmario** [comment] 2018-05-17 10:15
>...To make them stand out, they could be framed like in the w3schools example (they do it very right)

I find them way to colorful and extremely distracting. ... Because I tend to read the boxes only. ... But if the boxes have all the important info. ... Why is there text in between? If it isn't imporant it shouldn't be there!

**Comment by pmario** [comment] 2018-05-17 10:17
>for tiddlers that are part of a group I'm proposing such consistent highlighting of the important text notes like "note: to use this you need that"

Do you have an example? ... I'm pretty sure, it can be fixed with "text only" changes or restructuring and removing text.

**Comment by Jermolene** [comment] 2018-05-17 12:25
I think @BurningTreeC  OP is about highlighting the background of notes and callouts in the docs. The docs macro `<<.tip>>` provides an opportunity to experiment with it. There's an example at https://tiddlywiki.com/#TaskManagementExample. We could certainly explore colouring the background of those boxes; it's a very common approach.

I like @BurningTreeC's later observations about the formatting of the docs for ActionSetFieldWidget, and agree that things could be improved. Perhaps the next step might be a mockup?

**Comment by BurningTreeC** [comment] 2018-05-17 12:42
@Evolena @Jermolene 

thanks for supporting this :+1: 

> Maybe it could be achieved by simply improving the tip and warning doc macros

yes, that sounds like the right thing

> Perhaps the next step might be a mockup?

also yes, so future doc-additions would use the widget-mockup, the macro-mockup, the filter-mockup and so on? More like a template to copy and fill with the text or a template tiddler that's used to render the doc-tiddler that contains only text in fields or indices?

**Comment by Jermolene** [comment] 2018-05-17 12:45
> also yes, so future doc-additions would use the widget-mockup, the macro-mockup, the filter-mockup and so on? More like a template to copy and fill with the text or a template tiddler that's used to render the doc-tiddler that contains only text in fields or indices?

I was thinking more that you'd produce a mockup for discussion, and then eventually we'd roll the changes out through the existing widget docs. People adding a subsequent widget to the docs would probably just clone an existing widget and modify it, as we do at the moment.

Having said that, the operator docs are already quite automated, and there's a bunch of improvements that could probably be made without touching each operator doc tiddler individually.

**Comment by BurningTreeC** [comment] 2018-05-17 12:52
> I was thinking more that you'd produce a mockup for discussion

I can do that the next days, weekend maybe

> People adding a subsequent widget to the docs would probably just clone an existing widget and modify it, as we do at the moment

understood

**Comment by pmario** [comment] 2018-05-17 14:06
Just found this areticle: https://www.hobo-web.co.uk/best-screen-size/ ... 

So if we look at tiddlywiki.com with Ctrl-Shift-M on Firefox, and a resolution with 1280 x 900 up to 1440 x 900 we can see the page like a bit more than 50% of PC user base (worldwide).

**Comment by BurningTreeC** [comment] 2018-05-17 14:31
@pmario - impressive!

you would have a beautiful 40-inch-wide green box on that setup, wouldn't you like that? :grin: 

such an info box could also float right and be `@media min-width: half-a-million { float: right; width: 30%; text-align: justify; }`

fun aside: what are the concerns about "boxes with background color" in combination with screen sizes?

**Comment by pmario** [comment] 2018-05-17 15:19
My concern is, number of characters per line, in the tiddler body text. It should be around 80 characters for optimal human readability. 

With a width of 1280px the TW default setting is already 140 character, with a zoom level of 100% and a character hight of 15px. 

With 1024px width we are very close to ~80 char per line. ... And if I read the tiddler with this resolution, it actually looks really good. For me there is no "loss of importance" because the 1-liner (with 1920) becomes a pargraph with 3 lines. Very similar to my 2nd screen shot.

So if we add additional "attraction" to this line, it will help users with 1920px screens. But, I think it will be too much for a majority of our users. 

just some thoughts.

**Comment by BurningTreeC** [comment] 2018-05-17 15:26
I understand that point @pmario 
How about taking a look at a mockup when there is one and firing the browsers device-simulator from the dev-tools so that we can actually see it

About the colors, I think they don't need to be too catchy

**Comment by pmario** [comment] 2018-05-17 15:58
I'm ok with mochups :)

**Comment by BurningTreeC** [comment] 2018-05-18 06:51
Hi @twMat 

what I'm requesting here is a small change versus better readability of important notes
I think what you're talking about is a much bigger change of the documentation layout, where changes like highlighting certain notes may be part of it ... ?

How about a step-by-step approach to improve the layout one by one towards a common consensus?
I believe changing it all at once is a really big task

> Maybe one could create a kind of "tab-or-headlines" toggle? In a way it has similarities with story views.

That's a good idea

**Comment by BurningTreeC** [comment] 2018-05-24 08:21
Here's a Mockup

http://dochighlighting.tiddlyspot.com/

**Comment by Jermolene** [comment] 2018-05-24 09:26
Hi @BurningTreeC I really like the mockup, looks great.

To be effective, I think these boxes need to be used sparingly and consistently. @Evolena and others have put a lot of effort into making "meta-documentation" that describes how the TiddlyWiki docs are written (see "Improving TiddlyWiki Documentation" under "Community" in the TOC on tw.com). Our first step should be to update those instructions with good advice on how and when to use these new boxes. Then we need to retrospectively apply the boxes in the areas where they have the most impact.

**Comment by BurningTreeC** [comment] 2018-05-24 09:42
@Jermolene thanks, that's good. I'll take a look at the instructions and give it some thoughts

Especially for the ListWidget in the Mockup I've used too many boxes. The content is a bit all over the place in that tiddler, it maybe shows that it's also worth restructuring a bit like @pmario mentioned

**Comment by pmario** [comment] 2018-05-24 11:29
>Here's a Mockup

Most of the time those boxes are used to draw attention to some text, that is at the middle or lower end of the tiddler body. 

see: http://dochighlighting.tiddlyspot.com/#Editions:Editions%20HelloThere%20GettingStarted%20ListWidget

For me this shows, that the structure of the text needs improvement. 

As Jeremy points out, there is some "meta documentation" we should have a closer look at. I immediately found a statement there, that is simply wrong.

**Comment by BurningTreeC** [comment] 2018-05-26 08:31
>see: http://dochighlighting.tiddlyspot.com/#Editions:Editions%20HelloThere%20GettingStarted%20ListWidget
For me this shows, that the structure of the text needs improvement.

yes right, It should be on top and state something like "Editions are `<tell what they are here>`"

> Most of the time those boxes are used to draw attention to some text, that is at the middle or lower end of the tiddler body.

They should draw attention to information, that could be overseen - when the text is well-structured but there's still something to point out or to warn about - or something that doesn't fit somewhere else but is somehow related to the current stuff. Those things will happen with well-structured docs, too

**Comment by pmario** [comment] 2018-05-26 09:57
>They should draw attention to information, that could be overseen - when the text is well-structured but there's still something to point out or to warn about - or something that doesn't fit somewhere else but is somehow related to the current stuff. Those things will happen with well-structured docs, too

Yes, that's absolutely right, but it should be used rarely and only if there is no other way! Otherwise it looses it's "validity". 

If it is on every tiddler, users start ignoring the boxes, or worse!

Technical documentation is important, by design and having 2 or 3 more levels of important like: "more important" or "much more important" is only confusing for users. Either it is important or it is not. It's that simple. 

I did create technical docs and training material for 10+ years and we "drove" incredibly well with 3 text levels.

 - Logical structued text, with simple examples first and getting more complex down the line. 
 - Hint
 - IMPORTANT

eg:

```
Hint:
      If you do it that way, you'll save time in the long run.
```

```
IMPORTANT: 
     Using the browsre built in "File: Save" dialog, will result in a corrupted file!
```

 - I'm OK if "Hint" uses an unintrusive icon, as it is at the moment. eg: https://tiddlywiki.com/#Editions
 - IMPORTANT: Could be a little bit more "aggressive" https://tiddlywiki.com/#GettingStarted

That's it ... for "new box stuff"

We already have: 

 - Image buttons
 - Icon buttons
 - Colored buttons
 - Quotes
 - Example ... Show / Hide
   - Examples with copy to clipboard
 - Info boxes
 - Tag pills (+dropdowns)
 - Tabs
   - horizontal
   - vertical
 - .... and probably more,

see: https://tiddlywiki.com/#Community:Community%20Plugins%20%5B%5Baddprefix%20Operator%20(Examples)%5D%5D%20HelloThere

**Comment by pmario** [comment] 2018-05-26 10:03
All of those existing visual "differences" are able to overload new users. 

So in my opinion, we need to make it simpler and more consistent. 

I would be OK with a new pallete, similar to "high contrast" but "more colorful", for those users, that prefere or need more color. The color switcher can be made more prominent.

**Comment by BurningTreeC** [comment] 2018-05-26 10:11
> I did create technical docs and training material for 10+ years and we "drove" incredibly well with 3 text levels.

You also have 10+ years training in reading it, many users probably not

> All of those existing visual "differences" are able to overload new users.

Sure, it should all have a uniform look and structure. Consistency as you say. So how to get those who have written doc-tiddlers to make changes in favor of consistency and a uniform look and structure?

Should there be 3/4 templates on tiddlywiki.com that users can clone, fill in docs and see how they appear then copy them over?

**Comment by Jermolene** [comment] 2018-05-29 20:13
Hi @BurningTreeC if you're willing, I'm in favour of a PR for the styling updates for the existing macros, and then perhaps we might consider updating the usages and docs guidelines later.

**Comment by BurningTreeC** [comment] 2018-05-30 16:17
@Jermolene I'm actually not able to reproduce the same in the current prerelease, don't know why. When I find the reason, I'll make that PR

**Comment by BurningTreeC** [comment] 2018-05-30 16:22
Is editions/tw5.com up-to-date with tiddlywiki.com/prerelease (doc-styles & doc-macros)?

**Comment by Jermolene** [comment] 2018-05-30 16:24
Hi @BurningTreeC 

> Is editions/tw5.com up-to-date with tiddlywiki.com/prerelease (doc-styles & doc-macros)?

Yes, should all be up to date. What's going wrong?

**Comment by BurningTreeC** [comment] 2018-05-30 16:27
The svg icons don't show up if I use editions/tw5.com from a fresh clone, just copying the macros and styles over. Maybe I'm doing something wrong, I'll try again

**Comment by BurningTreeC** [comment] 2018-05-31 09:02
@Jermolene I've found my errors and made a PR #3317

**Closed** 2018-06-06 08:27 UTC
