### ISSUE TITLE
The Editor Toolbar Prevents Control Backspacing in Firefox

### ISSUE THREAD

**Issue by ghost** [Jermolene/TiddlyWiki5#2532] opened 2016-08-10 05:42 UTC
When the editor toolbar is open in a Tiddler hitting Ctrl+Backspace does nothing in the editor window. With the toolbar closed it deletes a whole word as expected. Checking the box in the settings menu immediately enables or disables use of Ctrl+Backspace.

Ctrl+Backspacing in other text fields, like TiddlyWiki search bar are unaffected.

Version: 5.1.13
Browser: Firefox (does not affect Chrome, other browsers are untested)
OS: Windows 7 x64

-TCJ

**Comment by nameanyone** [comment] 2016-08-12 18:07
Shift-Ins is another one: #2452.

**Comment by mdemoss** [comment] 2018-12-22 21:51
I have the same problem, and I'm using the CodeMirror plugin as a work-around.

**Comment by henrikh** [comment] 2019-01-30 07:39
I have just updated to Firefox 65 from the official release channel. The issue is no longer present at my end.

**Comment by Jermolene** [comment] 2019-01-30 08:45
Thanks @henrikh

**Comment by pmario** [comment] 2019-01-31 11:02
Hi, @ghost ... can you verify, that it works with latest FF 65. ... If yes please close the issue!

**Comment by pmario** [comment] 2019-02-01 13:06
@Jermolene ... can you please close this issue?

**Comment by Jermolene** [comment] 2019-02-01 16:56
Thanks @pmario @henrikh

**Closed by Jermolene** 2019-02-01 16:56 UTC
