### ISSUE TITLE
Hyperlinks in Markdown 

### ISSUE THREAD

**Issue by tucknology** [Jermolene/TiddlyWiki5#2476] opened 2016-06-07 00:20 UTC
# Issue Description
I am using the Markdown plug-in and I've noticed it doesn't convert simple URLs to hyperlinks. I do believe this is ordinarily supported by Markdown. For example, if I type `http://www.google.com` below, you'll see the URL is converted into hyperlink

http://www.google.com

(It is quite convenient that Github is using markdown so I can illustrate the intended behavior 😎 )

# Screenshot of Issue
![screen shot 2016-06-06 at 5 09 24 pm](https://cloud.githubusercontent.com/assets/19787615/15841928/aefa6376-2c09-11e6-8d43-3329cbc25f17.png)

# About Me and my Setup
I am a very new user of TiddlyWiki (32 hours of experience!) who is very appreciative of its authors. I've installed TW5 using Node.js on my home server. Thank you very much for considering this issue.

**Comment by Jermolene** [comment] 2016-06-07 06:37
Hi @tucknology and welcome to the project. I agree that it seems like a bug that URLs are not automatically hyperlinked. The behaviour is a function of the Markdown library that TiddlyWiki uses. I'll look into what's going on.

**Comment by Jermolene** [comment] 2016-06-07 07:35
Hi @tucknology I'm afraid that it turns out to be complicated....

The thing is that Markdown as [originally defined by John Gruber](https://daringfireball.net/projects/markdown/syntax#autolink) does **not** feature support for standalone links (ie without the bracket markup). It's only so-called [GitHub Flavoured Markdown](https://help.github.com/enterprise/11.10.340/user/articles/github-flavored-markdown/) that supports automatic links (and a bunch of other changes).

TiddlyWiki uses the parser https://github.com/evilstreak/markdown-js, which by default supports standard Markdown. Look in the "Usage" tab of the entry for the plugin in the TW control panel for information on how to configure it. I believe that the supported Maruku dialect does support autolinking, but you may need to experiment.

**Comment by tucknology** [comment] 2016-06-08 01:45
Hi @Jermolene thanks for the warm welcome and your support. I switched to Maruku following your suggestion, yet it seems this has the same result as standard markdown. 

As you point out, this is expected behavior, so perhaps I could submit a feature request for GFM support? I see there has been some discussion on this in the past, so I expect it is not trivial. I will learn & use the standard WikiText markup in the meantime.

I have no Javascript experience, most of my work is C/C++ on embedded systems, but if I can help with some testing or debugging I would be happy to contribute to this project.

**Comment by tucknology** [comment] 2016-07-07 19:23
I recently found the MarKed plugin at http://bjtools.tiddlyspot.com/ and it seems to support GFM, including automatic hyperlinks. I will continue to test and report back.

**Comment by sukima** [comment] 2016-07-07 19:49
This is supported in markdown with the [autolink](https://daringfireball.net/projects/markdown/syntax#autolink) feature. In other words I think this is by design and **not** a bug.

Per the docs AFAICT:

```markdown
http://example.com

<http://example.com>
```

should render to:

```html
<p>http://example.com</p>

<p><a href="http://example.com">http://example.com</a></p>
```

**Comment by Jermolene** [comment] 2016-07-11 09:57
Hi @tucknology I'm closing this issue for the moment as it is not currently actionable, the behaviour being per the spec. Please feel free to re-open if the anything changes.

**Closed by Jermolene** 2016-07-11 09:57 UTC
