### ISSUE TITLE
[BUG] $:/temp tiddlers should not be saved in single file

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#4933] opened 2020-10-28 23:18 UTC
As the [documentation ](https://tiddlywiki.com/#Naming%20of%20System%20Tiddlers )suggests, these are temporary tiddlers and should not be saved.

However, they are saved in the single file version and accumulate over time leading to clutter. In particular, the plugin library generates a lot of `$:/temp/RemoteAssetInfo` tiddlers that end up getting saved.

Suggest we modify $:/core/save/all to exclude all `[prefix[$:/temp/]]` tiddlers.

**Comment by kookma** [comment] 2020-10-29 13:28
@saqimtiaz  Also the behavior for TW+Node.js is different. I mean a plugin on single file Tiddlywiki has access to its $:/temp/... tiddlers but on TW+Node.js has not as the latter does not keep the temporary tiddlers, so your suggestion is valid and valuable to be applied!

**Comment by saqimtiaz** [comment] 2020-10-29 13:30
@kookma right, and this is problematic as a plugin writer can depend on $:/temp tiddlers not being saved on node.js, but they are saved in the single file TW.

**Comment by rmunn** [comment] 2020-10-30 08:59
This is a duplicate of https://github.com/Jermolene/TiddlyWiki5/issues/3375. Once this issue is fixed, #3375 should be closed as well.

**Closed** 2020-10-31 13:21 UTC
