### ISSUE TITLE
Support local authentication of access to encrypted tiddlers

### ISSUE THREAD

**Issue by reflectionalist** [Jermolene/TiddlyWiki5#1615] opened 2015-03-28 08:37 UTC
## Summary

If I understand the encryption mechanism of TiddlyWiki correctly, the encryption works globally.  It encrypts the whole file and decrypt it during bootup and hence authenticate access.  Interestingly, there is the encrypt widget which allows selectively encrypt tiddlers (if I understand its functionality correctly).  However, it seems the the authentication mechanism does not catch up.  It still guard the whole wiki globally.
## Reproduction
1. Set a password.
2. Use the encrypt widget to encrypt some filtered tiddlers.
3. Reload the wiki.
## Expectation

I expect the authentication dialog to pop up only when one tries to access an encrypted tiddler.  This allows me to publish my wiki (say the blogs part) with some contents (say, my todo lists) protected by a password.
## Context

OS: Kubuntu 14.04 LTS (64bit)
Browsers: Firefox (36.0.4) and Chromium (41.0.2272.76)

**Comment by danielo515** [comment] 2015-03-28 11:47
What kind of encrypt widget are you using? I created a plugin that allows you to encrypt tiddlers selectively. Tiddlywiky does not have this functionality as part of its core. I have plans to allow my plugin to encrypt a bunch of Tiddlers based on a filter. Maybe this is already possible with the use of action widgets and my plugin without any modification

**Comment by danielo515** [comment] 2015-03-28 11:50
Please take a look at braintest.tiddlyspot.com and check encrypt tiddler plugin

**Comment by sukima** [comment] 2015-03-28 23:04
I think this is a duplicate of #310 for which @Jermolene piped up to say:

>I did full file encryption first because it avoids a tricky UI problem: in an environment with selective encryption it can be hard for users to remain sufficiently aware of what's going to be encrypted. The consequences of inadvertent disclosure of content are pretty sever for many people, so the safest approach was to focus on encrypting the entire wiki.

**Comment by reflectionalist** [comment] 2015-03-29 06:11
Hi, **@danlelo515**,

Thanks for the answer and recommendation of your plugin, exactly what I am looking for.

The encrypt widget I mentioned was `<$encrypt>` which takes a filter as argument.

**Comment by reflectionalist** [comment] 2015-03-29 06:39
> Thanks for the answer and recommendation of your plugin, exactly what I am looking for.

**@danielo515**, sorry to retract.  Your plugin will be exactly what I am looking for if it gets combined with the functionality of the encrypt widget I mentioned.  :)

**Comment by danielo515** [comment] 2015-03-29 09:08
Hello @reflectionalist ,

Is that widget part of the core ? When I checked tiddlywiki encryption capabilities more than a year ago there was any way to encrypt tiddlers selectively. I'll check again. Meanwhile, could you let me know which functionality are you missing exactly ? So I can add it to my to do list

**Comment by Jermolene** [comment] 2015-03-31 12:30
> Is that widget part of the core ? When I checked tiddlywiki encryption capabilities more than a year ago there was any way to encrypt tiddlers selectively.

@reflectionalist @danielo515 the encrypt widget is used to encrypt the store area when saving an encrypted wiki. See:

https://github.com/Jermolene/TiddlyWiki5/blob/master/core/templates/store.area.template.html.tid#L11

**Comment by danielo515** [comment] 2015-03-31 15:32
Hello @Jermolene,

I checked the code of that widget, and it has a big drawback: it only encrypts the tiddlers if there is something stored on the passwordVault. If you clear the passwordVault, you clear the result of this tiddler. And if you leave something on the passwordVault the entire wiki will be encrypted and you will be prompted to input a password on file open. This makes impossible to take advantage of one of the documentation suggestions

> The $:/isEncrypted tiddler that contains "yes" or "no" according to whether there is a password in the password vault
The availability of this tiddler allows the RevealWidget to be used to selectively display user interface elements according to whether encryption is in force

The only way to encrypt a bunch of tiddlers would be using a temporary tiddler and a bunch of action-widgets

1. Raise the set_password message
2. Save the result of the encrypt widget to a tiddler
2. Clear the password vault.

Sadly there is no way to get the result of the encrypt widget because it creates a text node, but it does not return anything.

**Comment by reflectionalist** [comment] 2015-03-31 23:31
**@danielo515**:

> Meanwhile, could you let me know which functionality are you missing exactly ? So I can add it to my to do list.

Your plugin is already very close.  It can encrypt/decrypt tiddlers individually but (if I understand correclty) could not do batch encryption.  The functionality I request is batch encryption and individual decryption on access (say, when open a tiddler).  However, I am not quite sure how batch encryption should be offer to the user, as a widget or as an element in the user interface (like the search box).

**Comment by danielo515** [comment] 2015-04-01 06:07
Hello @reflectionalist ,

My idea is to provide a widget that gives the functionality, and then build the UI on top of it, as I did already.

Maybe we can discuss this on my plugin repo so we don't pollute this one?

https://github.com/danielo515/TIddlywiki5-EncryptTiddlerPlugin

**Comment by Jermolene** [comment] 2015-04-01 07:47
Hi @danielo515 

> I checked the code of that widget, and it has a big drawback: 

Well, the existing encrypt widget is just designed for encrypting the entire file. We'd need to extend it to use it for individual encrypted tiddlers. But as I pointed out above, the encrypt widget is a very thin layer over the underlying SJCL library. It wouldn't be a problem if we ended up with a different widget for single tiddler encryption.

**Comment by pmario** [comment] 2015-04-01 07:53
You are right. The issue to track this new feature is: "Introduce vocabulary parameter to wikitext content type" #345

**Comment by Jermolene** [comment] 2015-04-01 07:57
Ah, thank you @pmario

**Comment by pmario** [comment] 2015-04-01 08:06
Sorry folks, I did post a reference to the wrong issue. so I removed the post.

**Comment by tobibeer** [comment] 2015-09-21 09:23
Rather than (or perhaps in addition to) some tag flagging tiddlers for encryption I'd prefer some config tiddler holding a filter that defines what to encrypt and consequently what not to... if implemented at some point.

**Comment by danielo515** [comment] 2015-09-21 10:50
Hello @tobibeer, 

Since this was discussed a new version of my plugin has been released. It does implement the encryption based on a filter. Please check it and let me know if it fit your expectations. 

Regards

**Comment by tobibeer** [comment] 2015-09-21 10:57
@danielo515, will do. Thanks.

**Comment by pmario** [comment] 2015-09-21 11:06
@reflectionalist 
can you check this version too and close the ticket if it fits your needs?

**Comment by danielo515** [comment] 2015-09-21 23:32
I think some more improvements can be implemented on my plugin, specially for a better multi user support, but that could be discussed on it's own repo.

**Comment by pmario** [comment] 2017-05-17 21:09
@reflectionalist, @danielo515 ... is this issue resolved?

**Comment by danielo515** [comment] 2017-05-18 07:30
Since my plugin does meet most of the requirements and new features improvements can be discussed on its own repo for me this is closed

**Comment by pmario** [comment] 2018-05-28 11:03
@Jermolene .. please close as @reflectionalist didn't respond to the last "close-request" and there is a work-around as a plugin.

**Comment by Jermolene** [comment] 2018-05-28 11:59
Thanks @pmario

**Closed by Jermolene** 2018-05-28 11:59 UTC
