### ISSUE TITLE
"Sticky Titles" over-foregrounded?

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#2910] opened 2017-06-17 12:26 UTC
Has this come up before? Probably.

$:/themes/tiddlywiki/vanilla/options/stickytitles if set to "yes" can cause issues that look like "z-index" CSS issues to me? 

Here is an example I commonly encounter ...

![capture](https://user-images.githubusercontent.com/28830541/27252851-73402c3a-5368-11e7-8394-8ede7efc2fb8.PNG)

Sticky titles works excellently on Firefox apart from this inappropriate overlay issue.

**Comment by pmario** [comment] 2017-06-17 13:53
Dupe of #2747, which also proposes a fix. So this one should be closed.

**Closed** 2017-06-17 14:10 UTC
