### ISSUE TITLE
No plugins in library

### ISSUE THREAD

**Issue by midjji** [Jermolene/TiddlyWiki5#2948] opened 2017-07-22 13:24 UTC
Downloading the empty.html tiddlywiki from http://tiddlywiki.com and accessing the plugins library from the control panel does not show any plugins. I have tried several variants, it never works with the empty.html. Downloading the fullwiki does show the plugin library however.

**Comment by Jermolene** [comment] 2017-07-22 15:33
Hi @midjji what browser and operating system are you using?

**Comment by midjji** [comment] 2017-07-22 15:45
Chrome in windows and Linux it works in nighter. A new behaviour which
seems to happen about a fifth of the time is that it hangs on open instead.

Thr pluginslist loads in about 500ms on most other tiddlywikis.

**Comment by twMat** [comment] 2017-07-22 21:47
(Works fine on Win10+Chrome.)

**Comment by Jermolene** [comment] 2017-07-24 16:22
Hi @midjji 

Are you using any extensions that might be interfering with the operation of the plugin library? For example, an ad blocker?

Does the plugin library work if you navigate to http://tiddlywiki.com/empty.html and then try to install a plugin directly from the plugin library?

**Comment by Jermolene** [comment] 2017-07-24 16:23
@midjji are there any messages in the browser console? View -> Developer -> Developer Tools, then click the "console" tab.

**Comment by midjji** [comment] 2017-07-25 20:06
Ah that likely shows  the problem. 

Mixed Content: The page at 'https://candlekeep.se/tiddly/tiddlywiki1.html' was loaded over HTTPS, but requested an insecure resource 'http://tiddlywiki.com/library/v5.1.14/index.html'. This request has been blocked; the content must be served over HTTPS.

So some config error on my side makes it go for the http fallback and then refuses that?

**Comment by mklauber** [comment] 2017-08-15 18:45
Sounds like the root cause of this is the same as #2788

**Comment by midjji** [comment] 2017-08-15 19:55
Yes, i just changed the path and fixed the exception, with the other better
issue consider this one closed

**Comment by pmario** [comment] 2017-08-15 20:03
>issue consider this one closed

please close it. ... Only the creator of an issue and Jeremy can close it.

**Comment by tobibeer** [comment] 2017-12-08 06:50
@midjji: **ping**, pls close.

**Closed** 2017-12-08 12:53 UTC
