### ISSUE TITLE
Node.js TiddlyWiki logout 404

### ISSUE THREAD

**Issue by CaiBaoHong** [Jermolene/TiddlyWiki5#4297] opened 2019-10-09 16:31 UTC
Hi, I have a problem on the logout function.

I start the server following this steps:

~~~bash
caibh@home:~$ tiddlywiki --version
5.1.21
caibh@home:~$ tiddlywiki wiki --init server
caibh@home:~$ tiddlywiki wiki --listen username=caibh password=123456
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList 
~~~

then I access `http://127.0.0.1:8080` in the browser，and login with the `username` and `password`. then click `setting` -- `server`--`logout`，got and error message `404` :

![logout-404](https://user-images.githubusercontent.com/17343552/66500997-28912a00-eaf5-11e9-84d3-d9d4cca9ae74.png)

Please help me, I love TiddlyWiki so much!

**Comment by sukima** [comment] 2019-10-11 15:44
That logoutg is for a very specific server which is not the tiddlywiki Node.js server you are using. It makes sense that the Node server you are running via `tiddlywiki --server` does not know about the logout URL as it was designed for a different server (TiddlySpot).

The username/password you provided is to enable HTTP authentication which a very different mechanism than that of TiddlySpot. In HTTP Authentication there is no concept of logging out.

The error you receive is correct for the situation. However, it would be more helpful to have the backend server tell tiddlywiki that it does or does not support logging out so that tiddlywiki can hide that button.

**Comment by Jermolene** [comment] 2019-10-11 16:52
Hi @CaiBaoHong a small correction to @sukima's excellent answer: the logout button only works with [TiddlyWeb](https://github.com/tiddlyweb/tiddlyweb)'s cookie-based authentication. TiddlyWeb isn't much used these days so we should make things a bit clearer.

**Comment by CaiBaoHong** [comment] 2019-10-12 03:24
> That logout is for a very specific server which is not the tiddlywiki Node.js server you are using. It makes sense that the Node server you are running via `tiddlywiki --server` does not know about the logout URL as it was designed for a different server (TiddlySpot).
> 
> The username/password you provided is to enable HTTP authentication which a very different mechanism than that of TiddlySpot. In HTTP Authentication there is no concept of logging out.
> 
> The error you receive is correct for the situation. However, it would be more helpful to have the backend server tell tiddlywiki that it does or does not support logging out so that tiddlywiki can hide that button.

Thanks for your explanation in detail !

**Comment by CaiBaoHong** [comment] 2019-10-12 03:26
> Hi @CaiBaoHong a small correction to @sukima's excellent answer: the logout button only works with [TiddlyWeb](https://github.com/tiddlyweb/tiddlyweb)'s cookie-based authentication. TiddlyWeb isn't much used these days so we should make things a bit clearer.

Got it, Thanks !

**Comment by pmario** [comment] 2019-10-12 08:06
@CaiBaoHong  if the issue is resolved, please close it

**Closed** 2019-10-14 02:06 UTC
