### ISSUE TITLE
Meta: make dragging links do more #3132

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#3136] opened 2018-02-25 16:03 UTC
This is a follow up for:  #3132

- Check the existing behaviour 
   - Check behaviour for `$:/SystemTiddlers with spaces`
   - Check behaviour for `$:/SystemTiddlers`
- Define new behaviour
   - normal: [[tiddler title]]
   - with ctrl: {{tiddler title}}
   - with shift: your prefix - tiddler title - your suffix
- Check: I have spaces --> [[I have spaces]] ... and I'm a link
- ImACamel --> ImACamel ... and a link
- imlowercaseonly --> imlowercaseonly ... without [[ ]]
- Copy links to search input
- Copy links AS TEXT to text input .... 
- Check core utility functions for existing regexp's to use
   - create new utility functions if needed
   - check config.js
- Make core/modules/utils/dom/dragndrop.js code maintainable again 

@BurningTreeC if you have more just add them

**Comment by pmario** [comment] 2018-02-25 16:03
---

**Comment by BurningTreeC** [comment] 2018-02-25 16:38
thanks @pmario 
what's not clear to me is if there should be a combination (or default) where dragged links will always be plain text, or if now it should be checked if the target is an input (search) field

You mentioned earlier that dragging links normally should result in links, so I guess this should be the default when no modifier keys are pressed

I think input fields should have the plain string by default
I also think that an option to get the plain title string by dragging them into textareas should be implemented

I'm kinda blocked because I don't see a _decision_ for these two points

**Comment by BurningTreeC** [comment] 2018-02-25 16:53
For the other things I'm about to implement the core utils functions

I can't find a valid test for CamelCase inside the util functions, I mean one that doesn't accept TWCamelcase as valid but there should be one, I think I'm just looking in the wrong place or not seeing how it's done

**Comment by BurningTreeC** [comment] 2018-02-25 17:43
@pmario 
I cannot edit the checklist, but here I've all checks but these:

Copy links to search input **not clear how to proceed**
Copy links AS TEXT to text input .... **not clear how to proceed**
Make core/modules/utils/dom/dragndrop.js code maintainable again **not clear how maintainable looks like**

[dragndrop.js](https://github.com/BurningTreeC/TiddlyWiki5/blob/7e8239180cb08f96abd05d433f5c4100ccde17b0/core/modules/utils/dom/dragndrop.js)

**Comment by BurningTreeC** [comment] 2018-02-25 19:37
This is just a sidenote:

this gets shown as a system tiddler but doesn't produce a link

>  $:/你好这是个考验 

Is this wanted or should we try fixing it?

**Comment by pmario** [comment] 2018-02-26 08:29
>what's not clear to me is if there should be a combination (or default) where dragged links will always be plain text, or if now it should be checked if the target is an input (search) field

Is it possible to check the drop target?

**Comment by pmario** [comment] 2018-02-26 08:31
>This is just a sidenote:
this gets shown as a system tiddler but doesn't produce a link
>
>>    $:/你好这是个考验
>
>Is this wanted or should we try fixing it?

I think, this a new issue for the "system-link-parser"

**Comment by pmario** [comment] 2018-02-26 08:45
>Copy links AS TEXT to text input .... not clear how to proceed

I personally don't use d&d copy much. So I have to ask myself: "Would it speed up my workflow?" ... I'm not sure.

At the moment d&d "title with spaces" creates "[[title with spaces]]" ... 

IMO your proposal now is: "Let's add a key combination to suppress d&d default behaviour - to insert plain text". 

I'm in favor of such an option ... BUT ... I personally don't know atm, which keys to use, to suppress the behaviour. ... For me personally the CTRL-key feels natural. ... but that's the key, you wanted to use to add `{{transclusions}}` ...

**Comment by BurningTreeC** [comment] 2018-02-26 08:55
> Is it possible to check the drop target?

that was my underlying question, I didn't make that clear enough
I'm now trying to check that in dragndrop.js where it listens for the dragend event, should be possible there
  
>>  Copy links AS TEXT to text input .... not clear how to proceed
> I personally don't use d&d copy much. So I have to ask myself: "Would it speed up my workflow?" ... I'm not sure.

About if it speeds up workflows I'm not sure either to be honest - I would let that open and just don't do anything, still being able to add it if it comes up that it does indeed
But for dragging into input fields/search fields I'd change it to plain text if no modifier keys pressed

>IMO your proposal now is: "Let's add a key combination to suppress d&d default behaviour - to insert plain text".

>I'm in favor of such an option ... BUT ... I personally don't know atm, which keys to use, to suppress the behaviour. ... For me personally the CTRL-key feels natural. ... but that's the key, you wanted to use to add {{transclusions}} ...

I'm really not settled about which key should do what, my initial choice was instant
If ctrl should produce transclusion or if the shift key should do that ... the thing is, we either start a opinionated discussion about that or we say that someone who can decide says "this is how we do it"

I'd appreciate the second option

**Comment by pmario** [comment] 2018-02-26 09:02
I think the existing default behaviour is inconsistent. It tries to "guess" the users intentions. Which imo is always wrong. 

And the existing behaviour imo was implemented at a time, where we didn't have the edit-toolbar. right? 

For me SHIFT, CTRL, ALT and combinations are "modifiers" ... And only if those modifiers are pressed, something special should happen. 

IMO it may be: 

 - d&d always imports `plain text`
   - after the d&d action the text is sleected
   - selected text can be modified with the edit-toolbar
   - if `add [[]]` and `add {{}}` don't exist, they should be implemented
 - CTRL d&d always adds `[[]]` ... even if the text / link doesn't need it
 - CTRL-SHIFT always adds `{{}}`
 - ALT or ALT-GR ... adds `prefix - text - prefix`

I personally would consider this a consistent behaviour. ... BUT ... Only working with it would tell, if it feels right. 

So I think I would want to have it configurable. 

AND having a look at this proposal, I think it should be implemented as a plugin first. So we can test it and then decide who to move it to the core!

**Comment by pmario** [comment] 2018-02-26 09:08
>I personally would consider this a consistent behaviour. ... BUT ... Only working with it would tell, if it feels right.

... AND it should also feel right for your. .. If it doesn't, we are not done here!

**Comment by pmario** [comment] 2018-02-26 09:09
>I'd appreciate the second option

I think it needs to be "generic" otherwise, we will be always wrong for someone.

**Comment by BurningTreeC** [comment] 2018-02-26 09:25
>I think the existing default behaviour is inconsistent. It tries to "guess" the users intentions. Which imo is always wrong.

What do you mean with "existing default behaviour"? The one in the current master or the one I'm adding?

>d&d always imports plain text
>>    after the d&d action the text is sleected
the text isn't selected automatically right now, but I think that could be done, at least I hope I'm right
>>    selected text can be modified with the edit-toolbar
>>    if add [[]] and add {{}} don't exist, they should be implemented
you mean as toolbar buttons, right? I'd do that in another PR

>I personally would consider this a consistent behaviour. ... BUT ... Only working with it would tell, if it feels right.

Now this is an important question because of one thing:

tiddlywiki **has** different types of links:

- the [[ ]] links
- CamelCase links
- systemtiddlers as links

this already isn't very consistent. Now the question about what consistency means in this context: Should we follow the default wikilink-inconsistency or act as if there was none and add [[ ]] to all of them?
I would really like to mirror these subtle things of wikitext-links in the appearance of the dragged result. That would also perform as a small educational part, like "what? why does this have brackets and that not? oh wow, they're both links in the end. Ah I see, that's wikitext". As you can imagine, the latter would feel right for me because adding [[  ]] to all is like undoing the original wikilink-behaviour


>So I think I would want to have it configurable.
That'll be ok, what should then be configurable in addition?

>I think it needs to be "generic" otherwise, we will be always wrong for someone.
If the default behaviour how tw creates links is generic, then it's generic, too if we mirror that in the drag-result, that's my opinion but I think it follows the implemented logic

**Comment by pmario** [comment] 2018-02-26 09:36
>If the default behaviour how tw creates links is generic, then it's generic, too if we mirror that in the drag-result, that's my opinion but I think it follows the implemented logic

Not really. ... It has evolved that way. ... and now we see some inconsistencies.

**Comment by pmario** [comment] 2018-02-26 09:38
>tiddlywiki has different types of links:
>
>  -  the [[ ]] links
>  -  CamelCase links
>  -  systemtiddlers as links

That's right. ... And it turns out users don't like CamelCase links. Most of them want to switch them off. ... It is still default, because of historical reasons. ... IMO users "taste" has changed over the years.

**Comment by pmario** [comment] 2018-02-26 09:43
I personally could also live with: 

 - d&d links imports `[[links]]`
   - after the d&d action the text is selected
   - selected text can be modified with the edit-toolbar
   - if `add [[]]` and `add {{}}` don't exist, they should be implemented
 - CTRL d&d **suppresses** adds `[[]]` ... even if the text / link doesn't need it
 - CTRL-SHIFT always adds `{{}}`
 - ALT or ALT-GR ... adds `prefix - text - postfix`

As you see, we should try to extract the different functions and make them modules and configurable. So erveryone can do what they want.

**Comment by BurningTreeC** [comment] 2018-02-26 10:11
>That's right. ... And it turns out users don't like CamelCase links. Most of them want to switch them off. ... It is still default, because of historical reasons. ... IMO users "taste" has changed over the years.

If camelcase linking is switched off, CamelCase dragging results in [[CamelCase]] as of my last changes
Somehow I don't like it either, but since it's there it gets handled

I like your last combo-proposal, you'd stay with "always add [[  ]]" without distinguishing between camel case, system tiddler and so on, am I right?

I'll make a PR for the two toggle buttons. There is a button to add links, but with a dropdown and an input field, no toggling

ctrl for suppressing links is good
ctrl+shift --> {{ }} also

but I avoided alt because it didn't work consistently when I tried using it for a combo and I read somewhere that there may be browser inconsistencies

I'd also tend to avoid alt-gr because of only 15% of the people being left-handed, they could be the only ones to use it without doing acrobatics. I don't want to discriminate minorities but well ...

**Comment by BurningTreeC** [comment] 2018-02-26 10:29
my altKey problem may be because I'm a minority using i3 wm on linux, which uses alt and meta for its own combos... are you able to test event.altKey on your machine?

could also be that it's used somewhere else and that it prevents me from using it here

or better imo: why not use only ctrl and shift?

summary:

dragging without mods: always add [[  ]]
ctrl alone: suppresses adding [[ ]]   ... like you proposed, and I think it's good
shift alone: adds {{  }}  ... because easier to combine and more frequently used
ctrl + shift: adds prefix and suffix

**Comment by BurningTreeC** [comment] 2018-02-26 12:05
I've updated my fork to behave like my latest summary

**Comment by Jermolene** [comment] 2018-02-26 12:28
Hi @pmario @BurningTreeC

A couple of points to add:

* The automatic wrapping with double square brackets is also useful when one is dragging titles into the list field of a tiddler, or to a filter like $:/DefaultTiddlers
* TiddlyWiki's core drag and drop functionality has suddenly started working on iPads and iPhones with the latest iOS 11.3 beta. It's pretty nice: on an iPad, one can drag a calendar entry into TiddlyWiki and create a VCAL tiddler, or a contact and create a VCF tiddler. But the point I wanted to make was that most users will not have access to modifier keys on these devices, so we should at a minimum aim to make dropping without a modifier key be the most generally useful option. We might also want to consider having a config tiddler that controls the behaviour of behaviour of dropping without a modifier key, so that users can opt for any of the available options. I wouldn't think it necessary for the core, but one could easily create a toolbar button for switching between the different drop modes.

Overall, I'd be inclined to go with Mario's latest suggestion.

**Comment by BurningTreeC** [comment] 2018-02-26 12:58
@Jermolene 
the default behaviour to be configurable is cool, I'll do that

>so we should at a minimum aim to make dropping without a modifier key be the most generally useful option
It seems to me that the most generally useful option is transclusion.. ?

I'm ok with mario's suggestions but not the alt key

I've done it so that only ctrl and shift are used. Alt key doesn't work over here and why a third key if the two can cover all

**Comment by Jermolene** [comment] 2018-02-26 13:03
Hi @BurningTreeC
> the default behaviour to be configurable is cool, I'll do that
> 
Great
> so we should at a minimum aim to make dropping without a modifier key be the most generally useful option
> It seems to me that the most generally useful option is transclusion.. ?
> 
Not necessarily: for dragging into list fields and filters the current behaviour of wrapping titles containing spaces with double square brackets is probably best.

Thinking about it, adding the configurability we've discussed would enable us to make the default setting be the current behaviour of selectively wrapping with double square brackets.

> I'm ok with mario's suggestions but not the alt key
> 
> I've done it so that only ctrl and shift are used. Alt key doesn't work over here and why a third key if the two can cover all
> 
I agree that control and shift seem to be the most universal modifier keys.

Best wishes

Jeremy

**Comment by BurningTreeC** [comment] 2018-02-26 13:07
ok, yep, thanks @Jermolene

**Comment by BurningTreeC** [comment] 2018-02-26 15:12
@pmario @Jermolene 
I've [updated]() my dragndrop.js with

- configuration of default behaviour
-- can be plain, transclude or user, default is adding [[ ]]
--- this default is what Mario proposed as default and Jeremy confirmed to go with
--- but Jeremy also mentioned that the default behavior (status quo) is useful, too
--- I think I changed it in regards of maintainability so that this is no big deal
- maintainability in mind
- the config tiddler is now $:/config/DragDefaults not $:/config/DragShiftLink or however it was
-- its text field defines the default for no modifier ("user"|"transclude"|"plain") default is default
-- the fields "prefix" and "suffix" do what they describe

**Comment by BurningTreeC** [comment] 2018-02-26 15:49
@all 
the link in my last post is updated

**Comment by pmario** [comment] 2018-02-26 15:49
I don't understand this: 

> - the config tiddler is now $:/config/DragDefaults
>    - its text field defines the default for no modifier ("user"|"transclude"|"plain") default is default

Because having 4 different states with 1 option value imo is impossible. 

We need: 

 - d&d creates a `[[link]]` ... default atm ... no changes
    - modifier + d&d ... to disable default behaviour ... for search input area
 - `{{transclusion}}` ... new with modifier and / or new editor button
 - `prefix - text - postfix` ... new with second new modifier

**Comment by BurningTreeC** [comment] 2018-02-26 15:53
@pmario 
> Because having 4 different states with 1 option value imo is impossible.

if each single state should be user-defined then yes, if only the default for "no modifier dragging" and the prefix and suffix for the "user defined" should be configurable then it works over here or I'm missing something

**Comment by BurningTreeC** [comment] 2018-02-26 15:59
It's everything there that's needed

Just the default for how the normal links should be created should be modified by you if it isn't right, I'm not gonna touch it anymore because I think it should be tried out by someone else than me

**Comment by pmario** [comment] 2018-02-26 16:00
But we are loosing functionality. Your initial intention was to have links, transclusions and prefix/suffix ...
Is that different now? ... I want to have it all.

**Comment by BurningTreeC** [comment] 2018-02-26 16:03
No we don't loose anything, they're all there

**Comment by BurningTreeC** [comment] 2018-02-26 16:19
@pmario 

I only changed the config tiddler name
The tiddler $:/config/DragDefaults can be used to:

- define the default behaviour for dragging without modifiers
- define the prefix and suffix for the (default ctrl+shift) user drag in the fields "prefix" and "suffix"

what each combo does is defined in dragndrop.js
if a user-defined default exists the combos get swapped so that the user-defined default gets used for no modifiers and: if the userdefined default is "transclude" then shift+drag will be creating links because that was the original default and shift+drag was "transclude". same for all others: "user" and "plain"
I'm handling "create links" as default in switch statements
I think this is all fine

**Comment by BurningTreeC** [comment] 2018-02-26 16:31
@pmario 

[this is the code](https://github.com/Jermolene/TiddlyWiki5/commit/f23c41316c2472c96d22cfe0489498b73fa88812)

**Comment by BurningTreeC** [comment] 2018-02-26 18:57
It does this:

default:

- normal creates [[  ]]
- ctrl creates plain
- shift creates {{  }}
- ctrl+shift creates prefix-title-suffix

set $:/config/DragDefaults to "user":

- normal creates prefix-title-suffix
- ctrl creates plain
- shift creates {{  }}
- ctrl+shift creates [[  ]]

the config swappes the result for the modifiers

do you want them all to be configurable for each key-combo?

**Comment by BurningTreeC** [comment] 2018-02-27 06:15
**Tag-Pill** dragging: we could make it do the same for each title

**Comment by BurningTreeC** [comment] 2018-02-27 06:56
I didn't think about the possibility to configure it as a list what each combo should do

this is the default: [ "default", "plain", "transclude", "user" ]
( no modifier, ctrl, shift, ctrl+shift )

and we could configure it the same way in a config tiddler field:
transclude user plain default

and so each combo is configurable

**Comment by BurningTreeC** [comment] 2018-02-27 06:59
changed it to be all configurable here:

https://github.com/BurningTreeC/TiddlyWiki5/blob/d7c1eea5d9dd3688d23f8dbfb0e074681a457f7b/core/modules/utils/dom/dragndrop.js

**Comment by BurningTreeC** [comment] 2018-02-27 07:30
... and this now does the same if the title string contains more than one element, like dragging tag-pills:

https://github.com/BurningTreeC/TiddlyWiki5/blob/6fc7dfd4e2826d9a8a065de422c751666ae7f1de/core/modules/utils/dom/dragndrop.js

**Comment by BurningTreeC** [comment] 2018-02-27 08:19
for dragging tag-pills into droppables like the open tab or that one list in the control-panel, also for reordering lists by dragging, one has to keep in mind what the plain modifier is, that's uncomfortable

I guess the droppable widget needs to handle that

**Comment by pmario** [comment] 2018-02-27 08:30
hihi, ... you are much faster changing the stuff as I'm able to test it :) I think I would have been happy with: https://github.com/Jermolene/TiddlyWiki5/issues/3136#issuecomment-368609477

**Comment by pmario** [comment] 2018-02-27 08:43
I did test your patch-6 and there seems to be a problem: 

- The control keys are only active, if they are pressed before the d&d action happens. 
- For me that's an unexpected behaviour. 
- OS level modifier can always be changed. ... Is this possible for us too?

**Comment by pmario** [comment] 2018-02-27 08:51
>changed it to be all configurable here:

Can you tell, how the config tiddler should look like?

**Comment by pmario** [comment] 2018-02-27 08:53
line 78 contains some trailing whitespace. https://github.com/BurningTreeC/TiddlyWiki5/blob/6fc7dfd4e2826d9a8a065de422c751666ae7f1de/core/modules/utils/dom/dragndrop.js#L78 ... it would be nice if you could remove it too.

**Comment by pmario** [comment] 2018-02-27 08:54
I think I like the functionality now ;)

**Comment by BurningTreeC** [comment] 2018-02-27 09:26
Hi @pmario , 
hehe sorry for the rush but I'll have less time available soon as semster starts

> The control keys are only active, if they are pressed before the d&d action happens.

I think that's because it checks ON DRAGSTART for the keys
It's the same for all keys, the must be pressed at start
otherwise all this should be done on DRAGEND, too -> checking again for the keys and so on
I don't know about this

> Can you tell, how the config tiddler should look like?

keys: string1 string2 string3 string4
prefix: yourprefix
suffix: yoursuffix

string1 ... should be "user" "plain" "default" "transclude" in the order how you want it
the first entry is for dragging without modifiers, second for ctrl, third for shift, fourth for ctrl+shift

**trailing whitespace and other formatting issues**

I'll try to fix 'em all

> I think I like the functionality now ;)

thanks, I like it too, like this one knows where what is

**Comment by BurningTreeC** [comment] 2018-02-27 09:32
But try reordering the draggable list in the open tab

There are things missing for the droppable widget
I think the drop-target is only accessible from within droppable.js
And if the target is NOT an input field or a textarea then the plain title string should always be used
The check for textarea & input field is already inside droppable.js
What's missing is saving the plain string from within dragndrop.js to somewhere accessible for droppable.js

I'd appreciate some advice from a js veteran ;)

**Comment by pmario** [comment] 2018-02-27 09:56
>What's missing is saving the plain string from within dragndrop.js to somewhere accessible for droppable.js

I'm not sure, but I think that works already as expected. ... If I drag eg: link with spaces .. produced with `[[link with spaces]]`  with SHIFT-d&d to the Recent tab, it works as expected.

**Comment by BurningTreeC** [comment] 2018-02-27 10:07
> I'm not sure, but I think that works already as expected. ... If I drag eg: link with spaces .. produced with [[link with spaces]] with SHIFT-d&d to the Open tab, it works as expected.

Yes that's true, but what if you happen to forget that you have your prefix-suffix at default and drag a tag-pill into the open-tab list? A mess
A smaller mess when you drag links normally around in such a list, but still

That's why I think the additional handling is needed

**Comment by BurningTreeC** [comment] 2018-02-27 10:08
What I mean is the reordering in the Open SideBar tab for example

**Comment by BurningTreeC** [comment] 2018-02-27 10:57
I think it needs to be handled somewhere

In droppable.js in handleDropEvent it collects the dragData
If there was an option, a free drag Type,  to add the unmodified titles via dataTransfer.setData() in draggable.js in importDataTransfer I could check in handleDropEvent and use the modified strings if over a textarea or input field and the plain strings if not
But since [here](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types) it seems that the possible drag Types are already taken I'd need another approach

**Comment by BurningTreeC** [comment] 2018-02-27 11:54
The problem is I don't know how to make the plain title string without modifications, created in dragndrop.js, accessible in droppable.js

**Comment by BurningTreeC** [comment] 2018-02-27 14:28
@pmario @Jermolene 

I made a small change to droppable.js so that reordering links within a draggable list should work normally no matter what key is pressed:

https://github.com/BurningTreeC/TiddlyWiki5/blob/patch-6/core/modules/widgets/droppable.js

For that I set $tw.dragInProgress.plainTitles to the plain title string and use that as first option in droppable.js (line 120)
See in dragndrop.js lines 45 and 50:

https://github.com/BurningTreeC/TiddlyWiki5/blob/patch-6/core/modules/utils/dom/dragndrop.js

Whenever you have time

**Comment by BurningTreeC** [comment] 2018-02-27 14:41
And a question at this point:

The default drag behaviour like it was before was, that only tiddlers with spaces got the [[  ]]
Now they all get [[  ]] in the "default" setting
Do you want to drop the old behaviour or do you want a configurable switch to make default behave like the 5.1.15 default if one wants - keyword: backwards compatibility?

**Comment by BurningTreeC** [comment] 2018-02-28 06:48
Sorry for spamming the thread...

One problem with saving the plain titles at $tw.dragInProgress.plainTitles is dragging a plugin for example from one wiki to another, where those plainTitles won't be accessible
So what I'm doing right now is not reliable

How can I add the plain title to the dataTransfer, so that in droppable.js it will be accessible as fields.plaintitle or something like that?
It must somehow be done with $tw.utils.importDataTransfer or another magic that allows to bundle the plain string within the dragged data

**Comment by BurningTreeC** [comment] 2018-02-28 09:31
I found a way through adding the plain title string to the jsonData

https://github.com/BurningTreeC/TiddlyWiki5/blob/patch-6/core/modules/utils/dom/dragndrop.js

droppable.js then uses the plaintitle "field" if it exists, that assures that dragging plugins for example from one wiki to the other doesnt result in {{plugintitle}}
the downside is that both wikis need to have the new droppable.js - if not the result is the modified one

https://github.com/BurningTreeC/TiddlyWiki5/blob/patch-6/core/modules/widgets/droppable.js

cheers, Simon

**Comment by BurningTreeC** [comment] 2018-02-28 14:17
... and dropzone.js needs to use the plain titles if they are within the string (handleDropEvent): 

https://github.com/BurningTreeC/TiddlyWiki5/blob/patch-6/core/modules/widgets/dropzone.js

the dropzone and droppable widgets should now always use the plain titles
For me it works reliable now

Only, as said before, dragging something from a wiki with new d&d to one with old d&d must be handled by pressing the right key that creates the plain titles

**Comment by BurningTreeC** [comment] 2018-02-28 14:21
dragging links with modifiers works on both firefox and chromium

dragging tag-pills works on firefox with all modifiers but doesn't work on chromium using shift or shift+control

**Comment by BurningTreeC** [comment] 2018-03-01 10:49
@Jermolene @pmario 

this is the same issue for dragging in chrome/safari with shiftkey, which in our case works with links, but not with tag-pills. there are solutions that could be inspected adoptable (?) ... 
hammerjs could be inspected for how it's done, it works there

another issue found on github targeting the same with a (possible) solution:
https://github.com/RubaXa/Sortable/issues/964

anyway, apart that it's ready for reviewing and testing

I need to explain that I push the plain title strings to the jsonData array and the drop handlers in droppable.js and dropzone.js check for the plain title string and use that if it's there

that causes an unconsistency if one drags between wikis with this d&d and wikis without, dragging a link or tagpill to tiddlywiki.com results in an additional "Untitled" tiddler that contains just the field "plainDragInProgressTitle" ... 

maybe there's anything I could use instead of "plainDragInProgressTitle" so that it gets ignored? Some already-built-in? Adding an invalid character like "!plainDragInProgressTitle" still creates that field

**Comment by BurningTreeC** [comment] 2018-03-02 08:50
Hi everybody, an idea for the problem with dragging to other wikies:

is it possible to add an event listener for mouseout and mouseover to see if the drag leaves the window,
then change the dragged Data accordingly?

Another thing: Could we close this thread so that I can make a short summary of it?

best wishes, Simon

**Comment by pmario** [comment] 2018-03-02 09:14
If you start a new PR, where you reference this thread, I'll close it.

**Comment by pmario** [comment] 2018-03-02 09:15
Or you can start a new thread, if you don't want to make a PR yet.

**Comment by BurningTreeC** [comment] 2018-03-02 13:59
Thanks, I've started #3148

**Closed** 2018-03-02 14:39 UTC
