### ISSUE TITLE
Bug: renaming tag creates extra list fields in all children

### ISSUE THREAD

**Issue by twMat** [Jermolene/TiddlyWiki5#4120] opened 2019-07-21 16:21 UTC
To reproduce

1. Create a tiddler and tag it `aaa`. Save.
2. Create the tiddler `aaa`. Save.
3. Change the title of tiddler `aaa` and check the *"Update aaa to aaax in the tags and list fields of other tiddlers"*. Save.
4. Open your first tiddler in edit. It now has a unwanted `list` field.

**Comment by pmario** [comment] 2019-07-22 05:09
That seems to be a bug.

**Comment by AnthonyMuscio** [comment] 2019-07-26 01:32
mat,

The resulting list field is empty yes, but, 

I believe this is related to a feature, and an acceptable symptom, with no need to fix.

The list field in a tag tiddler will be populated if someone attempts to change the order of items using it as a tag. If in fact the tiddler is tagged by itself the "tags list field" must also be updated, or if the first tags the second and the second tags the first, the original tiddlers list field may need to be updated. In the example you show the result is an empty list field. Being empty is correct, as would it containing values, if the original were used as a tag.

I believe this symptom is the result of having to cater for complex tagging relationships that are possible.

Since the list field is reserved for this feature, there is no harm retaining the empty list field, in someways this is information in itself.

If my response makes sense and you consider this acceptable do close this issue!

**Comment by twMat** [comment] 2019-07-26 08:51
@AnthonyMuscio - I'm wondering if you understood the OP. It is not the "tag tiddler" that gets the extra field, it is all those tiddlers that were tagged with the tag. This makes no sense.

**Comment by AnthonyMuscio** [comment] 2019-07-26 22:34
Mat

I fully understand the OP and that this symptom occurs on the other tiddlers. I speculated why this happens and pointed out it possibly has no unwanted impact.

Perhaps populating one of the other tiddlers list fields to check it is not damaged would confirm this.

Tony

**Comment by twMat** [comment] 2019-07-27 22:20
Yeah, arbitrarily fields for everyone - [Yeee-haaaw!!!](https://www.youtube.com/watch?v=gDDguYksysk)

**Comment by AnthonyMuscio** [comment] 2019-07-28 00:04
Not at all. List is like the icon or caption field they are almost essential. I just wish they did not use such a generic name for a field most people never see.

**Comment by Jermolene** [comment] 2019-07-28 14:17
Hi @twMat @AnthonyMuscio @pmario I can confirm that this is a bug. I don't think it's a v5.1.20 regression, though.

**Comment by Jermolene** [comment] 2019-07-30 16:11
Hi @twMat I can confirm the problem in the OP, and have committed a fix; please try the prerelease in about 8 minutes when the build should have finished.

**Closed** 2019-07-30 16:11 UTC

**Comment by twMat** [comment] 2019-07-30 16:55
Great.

I do find a minor and, I guess, related bug: If tiddler X already has list field containing, say, "aaa bbb" and I rename a tiddler from "bbb" to "aaa" then the tiddler X will now have the list field "aaa aaa", i.e double instances.
