### ISSUE TITLE
[BUG] Corrupted tiddler on tiddlywiki.com

### ISSUE THREAD

**Issue by saqimtiaz** [Jermolene/TiddlyWiki5#6222] opened 2021-11-16 08:32 UTC
Please see https://tiddlywiki.com/#%2Fhome%2Frunner%2Fwork%2FTiddlyWiki5%2FTiddlyWiki5%2Feditions%2Ftw5.com%2Ftiddlers%2Fdemonstrations%2FCaruso%20-%20Ave%20Maria.tid

Seems like a build issue, this is the source for the tiddler:
https://github.com/Jermolene/TiddlyWiki5/blob/master/editions/tw5.com/tiddlers/demonstrations/Caruso%20-%20Ave%20Maria.tid

**Comment by Jermolene** [comment] 2021-11-16 08:48
The problem is here:

https://github.com/Jermolene/TiddlyWiki5/pull/6213/files#diff-5fd7f6d33de1ce71035cdec9f7fd95dc8410a4a1bd5b55352b2b2cd72477d629

Presumably the tooling hiccuped because its a canonical_uri tiddler?

**Comment by saqimtiaz** [comment] 2021-11-16 08:53
Hmm. That is very odd. I will investigate when I get the chance but might not be a for a few days, busy week. I'll drop a note on the forum not to use it for PRs for _canonical_uri tiddlers for the time being.

**Comment by Jermolene** [comment] 2021-11-16 09:25
No problem I've committed a fix to the broken tiddler in d98bfbde580bb93bebbe8c03010ace2d03d542e8

**Closed by Jermolene** 2021-11-16 09:25 UTC

**Comment by saqimtiaz** [comment] 2021-11-16 09:27
Thank you @Jermolene.

I assume that I probably need to use a different template to render the tid files for canonical URI tiddlers, probably worth comparing to see how the filesystem/adapter code handles it. Will investigate when I get the opportunity.
