### ISSUE TITLE
An Observation: Firefox & Drag-n-Drop Issue

### ISSUE THREAD

**Issue by TiddlyTweeter** [Jermolene/TiddlyWiki5#2960] opened 2017-08-21 09:21 UTC
Drag & Drop procedures in Firefox _look inelegant_. They usually leave an "apport" of the drag box after completion. The drag operation works, but visually its ugly and, for normal users who don't understand what is happening, it can be confusing.

This is putting me OFF using it for anything in TW that would be public.

**Comment by pmario** [comment] 2017-08-21 09:50
I can confirm this behaviour for FF on ubuntu too. ... basically the "placeholder" element isn't removed. To be exact: The following div isn't removed.

```
<div class="tc-droppable-placeholder">
&nbsp;
</div>
```

**Comment by Jermolene** [comment] 2017-08-21 11:00
Thanks @TiddlyTweeter. Sadly this is an old bug: #686, which at one point I thought I had fixed (39cdaeb34dfe58cfd4a31b1f9e340bc906a918f1), but it is definitely still present. I'll re-open #686 and then we can close this ticket.

**Comment by Jermolene** [comment] 2017-08-21 11:06
Apologies @TiddlyTweeter I realise now that you are referring to a different problem than #686, I think you mean the sort of thing shown here:


<img width="420" alt="dropzone problem" src="https://user-images.githubusercontent.com/174761/29516672-2795e3b8-8669-11e7-8dc2-5d04511be90f.png">

**Comment by TiddlyTweeter** [comment] 2017-08-21 11:07
YES. 

I had thought it was a FF problem. Not a TW issue?

**Comment by Jermolene** [comment] 2017-08-21 11:08
This is, along with #686, one of the problems caused by Firefox's slightly non-standard implementation of drag and drop.

**Comment by pmario** [comment] 2021-09-12 20:31
@Jermolene .. I think this issue _and_ #686 can be closed. The drop target is now much bigger that it was at the beginning

**Comment by Jermolene** [comment] 2021-09-13 16:49
Thanks @pmario I think this is indeed fixed

**Closed by Jermolene** 2021-09-13 16:49 UTC
