### ISSUE TITLE
Feature request: search and replace

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyWiki5#3803] opened 2019-02-25 19:18 UTC
With the advent of new string filters, it is time to add the search-and-replace filter too. Also see here

https://github.com/Jermolene/TiddlyWiki5/issues/3288

A proposal could be like below

`[searchreplace:filed:flag[<sVal>,<rVal>]`

This can be quite similar to current search filter operator.

- field: any filed, like text
- flag: words (for whole words), casesensitive,...
- sVal: search value
- rVal: replace value

This can also be used with diff widget to show the changes.

**Comment by twMat** [comment] 2019-06-12 10:57
Nit pick; instead of `searchreplace[]` I think `replace[]` is sufficient.

A question somewhat beyond your OP: I have a great need for replacing strings in *texts* so I'm curious to hear if you think yor OP would be a feasible solution for that? Specifically, the concern is that filters treat everything as *lists* so it is messy to feed it with a text and get the result back out as a text. Maybe a search and replace filter op could somehow treat and output text (...or is it the surrounding *listwidget* that listifies everything? Maybe there should be a *string* widget that also manipulates via a filter...?)

**Comment by kookma** [comment] 2019-06-12 19:36
Have you tried snr in Tiddler commander?

**Comment by twMat** [comment] 2019-06-12 20:15
Thanks for replying. I just tried Tiddler commander but I don't get it to work. In the SnR tab, under "Tiddler title" I only get `None` as an option so I don't know what to do. Filling in a "Search text" and "Replace with" doesn't seem to do anything.

Is this a *filter operator* there, as you propose in your OP, or is it some js-code? (It has a huge list of shadow tids so I don't know where to peek).

**Comment by Jermolene** [comment] 2019-06-12 20:21
>  Specifically, the concern is that filters treat everything as lists so it is messy to feed it with a text and get the result back out as a text

Filters do indeed work on lists, but there are no restrictions on the length or content of those lists. So, for example, we can apply URL encoding to the text field of a tiddler with `<$text text={{{ [[HelloThere]get[text]encodeuricomponent[]] }}}/>`.

(Perhaps the confusion is that there are some workarounds for search and replace which rely on splitting and then rejoining strings).

**Comment by twMat** [comment] 2019-06-12 20:40
>(Perhaps the confusion is that there are some workarounds for search and replace which rely on splitting and then rejoining strings).

Yes, this is how I've done SnR myself and it was pretty messy. A straight forward filter operator would be superior.

**Comment by kookma** [comment] 2019-06-14 11:00
> Thanks for replying. I just tried Tiddler commander but I don't get it to work. In the SnR tab, under "Tiddler title" I only get `None` as an option so I don't know what to do. Filling in a "Search text" and "Replace with" doesn't seem to do anything.
> 
> Is this a _filter operator_ there, as you propose in your OP, or is it some js-code? (It has a huge list of shadow tids so I don't know where to peek).

Look at https://kookma.github.io/TW-Commander/
To use snr, first you should tell commander where you want to make search!

So first select few tiddlers and then you will be able to choose tiddlers in snr tab!

To experiment with SNR. I suggest use commander and create few tiddlers and then make SNR in them

There is example and explanation the Google Forum

**Comment by twMat** [comment] 2019-06-14 16:52
>So first select few tiddlers 

Well, how? - But actually, before I take more of your time; Are you helping me to actually perform SnR? Because I don't need that. My need is the same as yours, i.e some filter operator or perhaps some widget that allows me to create macros that rely on SnR internally.

**Comment by kookma** [comment] 2019-06-14 19:09
@twMat 
 I think the shortest way is to use a Javascript code!
The code I have developed is a bit complex

**Comment by kookma** [comment] 2019-06-14 20:04
> > So first select few tiddlers
> 
> Well, how? - 
This is simple! For example you want make SnR in all tiddlers tagged with xxx. Use the filter search.
You can then select tiddlers among above results and then in the final set you want to make SnR!

That's simple

**Comment by twMat** [comment] 2019-06-15 09:50
> I tried to implement all parts using pure TW macros. I think using JS one can develop a simpler, easier to maintain code! 

That's exactly my situation too. 

OK, regarding the UI in your plugin - not that you've asked for feedback but if it is a public plugin I'm assuming it may be of use;
 
I propose that the search result is not hidden inside the "Select" dropdown. TW's native *advanced search* shows the reaults by default. And actually, it would be more easy to understand the UI if the search field etc was below the tabs. Currently, the tabs indicate a separation between the tab contents and the search part and because there are several tabs it is not obvious that what's in my particular tab of interest has anything to do with that is outside of that tab. It is also a bit illogical that one is supposed to select titles in that upper listing but then select them again in the SnR Tiddler Title dropdown.

I like the aesthetics. Nice visual "sectioning" inside the tabs. And super cool with the *diff* display.

Thanks for pointing to it.

**Comment by kookma** [comment] 2019-06-15 15:52
Mat,
 This is a public plugin and there was a quite lengthy discussion about it on GG.
By the way I would be happy to receive any feedback through raising issues, pull request and like that.

The two step selection was a feature request! If you work you may find it interesting!
SnR is one part of Commander and it has other features. The one dealing with tiddler title is a top wish list item

**Comment by kookma** [comment] 2019-06-15 19:07
> I propose that the search result is not hidden inside the "Select" dropdown. TW's native _advanced search_ shows the reaults by default. 

It is not hidden by default! Once you open it it will remain open and again if you close it, It will remain closed! There is no default value! It depends to user!

**Comment by Jermolene** [comment] 2019-06-20 09:27
I should have pointed out that one of the subtleties here is that filter operators only take a single operand. @kookma's OP suggests that both the search string and the replace string would be packed into the operand with a comma serparating them: `[searchreplace:filed:flag[<sVal>,<rVal>]`.

The trouble with that arrangement is that it doesn't allow transclusion to be used to obtain the values ie there would be no way to search for a string specified in a variable without using text substitution. Plus things would fail if the search string contained a comma.

While I was thinking about that, I realised that the new split and join operators actually already allow us to build search and replace operations. The idea is to split on the search string, and then join the fragments together with the replacement string:

```
[[The cat sat on the mat]split[at]join[ab]]
```

However, the above example actually returns `The cab sab on the m` because the search string is stripped from the start and ends of the string. This can be fixed by temporarily topping and tailing the string with a character that is guaranteed not to be used in the search string. I've used the bullet character:

```
[[The cat sat on the mat]addsuffix[•]addprefix[•]split[at]join[ab]removesuffix[•]removeprefix[•]]
```

**Comment by twMat** [comment] 2019-06-20 19:15
>[[The cat sat on the mat]addsuffix[•]addprefix[•]split[at]join[ab]removesuffix[•]removeprefix[•]]

How 'bout "the *s&r operator* - a *two step* operator" that performs this hack in the background?

`[[The cat sat on the mat]s[at]r[ab]]`

**Comment by kookma** [comment] 2019-06-21 07:09
@Jermolene 
The SnR plugin uses the idea you stated above!
By the way what if we use access directly to the replace function in JS through a wrapper in TW?

**Comment by Jermolene** [comment] 2019-06-21 07:14
Hi @twMat @kookma 

> How 'bout "the s&r operator - a two step operator" that performs this hack in the background?

Indeed, that's what I've been thinking about too.

> By the way what if we use access directly to the replace function in JS through a wrapper in TW?

The problem isn't the logic for doing the search and replace operation, rather it's how we pass the needed pair of parameters if it is implemented as a single operation.

**Comment by Jermolene** [comment] 2019-06-21 09:34
I've slightly changed the split operator so that it's no longer necessary to add the prefix/suffix, and one can just do `[[the cat sat on the mat]split[the]join[every]]` and things work as expected.

See 6582b106ee4d226d2f686b78b632eded44c1f07b

**Comment by twMat** [comment] 2019-06-21 09:45
>I've slightly changed the split operator so that

OOOH!!! Thank you @Jermolene ! this will be so much fun!

```
<$set name=a value={{{ [[the cat sat ##on the the mat## in a hat ]split[ ##]join[ <div class="foo">]split[## ]join[</div> ]] }}} >
<<a>>
</$set>

<style>
.foo {background:red; display:inline}
</style>
```

(yes, the `##` is inappropriate for other reasons)

**Comment by kookma** [comment] 2019-06-23 16:08
@Jermolene 
That's great! I did not check it with flag! 

But now it is kind of semantic and easy to understand.

**Comment by kookma** [comment] 2020-11-07 13:39
With the new search-replace filter operator in TW 5.1.23 I think this issue can be closed
See #4973

**Comment by saqimtiaz** [comment] 2020-11-07 13:56
@kookma you can close this issue.

**Closed** 2020-11-07 14:23 UTC
