### ISSUE TITLE
BUG? : Nested $reveal widget causing $edit-text focus issue from v5.18

### ISSUE THREAD

**Issue by 00SS** [Jermolene/TiddlyWiki5#3879] opened 2019-03-26 04:30 UTC
Nested **$reveal** widgets are causing a loss of focus in the **$edit-text** widgets within the nested widgets. Works fine from v5.1.13 to v5.1.17 but shows this problem from 5.1.18 onward.

It is still not fixed on the pre-release 5.1.20 (2019-03-24). I'm not sure if it's related to the closed Github issue #3874 : **Bug with stateTitle attribute of reveal widget**
 
I am attaching a tiddler that shows the fault when typing in the edit-text box.

[Separator Custom Settings.tid.zip](https://github.com/Jermolene/TiddlyWiki5/files/3006498/Separator.Custom.Settings.tid.zip)

**Comment by 00SS** [comment] 2019-04-06 04:37
Any possibility of this being fixed in 5.1.20?

**Comment by pmario** [comment] 2019-04-06 07:19
the edit input changes a field in the same tiddler it is shown.  so there must be a redraw..thats why the input looses the focus. imo thats a known inconvenience.

will be solved once BTCs focus changes will be merged

**Comment by pmario** [comment] 2019-04-06 07:20
imo has nothing to do with reveal widget

**Comment by Jermolene** [comment] 2019-04-06 08:04
Apologies @00SS I haven't had a chance to look at this yet, and can't easily check the ZIP file on this machine. @BurningTreeC -- might this be anything to do with our recent changes to the reveal widget?

**Comment by BurningTreeC** [comment] 2019-04-06 08:25
@Jermolene I've looked at this some time ago and couldn't reproduce a regression, what exactly is the problem here?

**Comment by BurningTreeC** [comment] 2019-04-06 08:29
I'll have another look at it

**Comment by Jermolene** [comment] 2019-04-06 08:31
Thanks @BurningTreeC

**Comment by BurningTreeC** [comment] 2019-04-06 08:44
Ok, @00SS @Jermolene @pmario , the attached example tiddler contains an edit-text widget that edits the `separator` field of the example tiddler. So the same tiddler that contains the input is being edited and it's a known issue that editing the current tiddler causes the loss of focus on an input field. If **that's** the issue, there's no regression.

The example tiddler only contains that single edit-text widget, that's why I assume that when testing with lower versions of TW, a different tiddler was used for that input field or it was tested through a transclusion or some random way that doesn't show this **known** problem. We can't call it a bug, it's an html-javascript weirdness :grin: ... but we could try forcing our discussions on a good workaround, @Jermolene , you once mentioned (or I understood it that way) that you have an idea how to preserve focus on refreshs, I don't have any better idea than those I came up with

**Comment by BurningTreeC** [comment] 2019-04-06 08:45
@00SS - are you sure that same tiddler you've attached works fine on 5.1.17?

**Comment by 00SS** [comment] 2019-04-06 08:53
@pmario @BurningTreeC @Jermolene 

Sorry for the confusing example.
The `separator` field of the current tiddler just  holds a default value.
The actual changes from the $edit-text widget are being made to the **$:/.settings/separator** tiddler whose title is listed in the current tiddler's `settings-tiddler` field.

When I don't nest the $reveal widgets, the problem goes away in 5.1.18
Before 5.1.18 it works perfectly.

Thanks for looking into it. I believe there has been some change between 5.1.17 and 5.1.18 that is affecting it.

 Meanwhile I put it as an **issue** in my [date Macro](https://groups.google.com/d/msg/tiddlywiki/_bbDpiiReic/ZgA1N6g9CQAJ) - saying to "copy and paste" into the edit boxes.

**Comment by BurningTreeC** [comment] 2019-04-06 08:53
@00SS , now I see it, too

**Comment by BurningTreeC** [comment] 2019-04-06 08:55
```
<$reveal type="match" state={{!!settings-tiddler}} text="created">
Change the present ''separator'' here:
<$edit-text tiddler={{!!settings-tiddler}} field="separator" default="-" size="1"/><small> ( Default is `-` )</small><br>
```

**Comment by BurningTreeC** [comment] 2019-04-06 08:59
Ok, the **reveal** widget probably refreshes because it detects a change in its state tiddler and that's a bug. It should detect when the title of the state tiddler changes, not when the state tiddler itself changes and the state doesn't match. I believe I did something stupid here ...

**Comment by BurningTreeC** [comment] 2019-04-06 09:14
@00SS @Jermolene @pmario I found the bug I've introduced and it's an embarrassing one. I think #3897  fixes it, please test

**Comment by BurningTreeC** [comment] 2019-04-06 09:15
I've tested it, I have no idea anymore why I added this line, I probably forgot to remove it before adding the PR

**Comment by Jermolene** [comment] 2019-04-06 09:26
No worries @BurningTreeC, and many thanks to @00SS who is rapidly becoming our premiere bug finder general :)

Seriously @00SS it must be disorientating encountering so many quirks, but I'm very grateful to you for your awesome track record.

**Closed by Jermolene** 2019-04-06 09:26 UTC

**Comment by 00SS** [comment] 2019-04-06 17:10
I can confirm that in the pre-release, the issue is solved in the example I provided.
Thanks @BurningTreeC 
Much appreciated!
