### ISSUE TITLE
[BUG] Tag assignment in $:/Manager not working

### ISSUE THREAD

**Issue by adithya-badidey** [Jermolene/TiddlyWiki5#4817] opened 2020-08-14 10:49 UTC
**Describe the bug**
Adding tags on the Manager page doesn't work

**To Reproduce**
- Open the $:/Manager page in your favourite TW : [$:/Manager on Tiddlywiki.com](https://tiddlywiki.com/#%24%3A%2FManager)
- Select any tiddly from the list
- Select a tag from the dropdown on the right side of the tiddly popup
- No change.

**Expected behavior**
When you select a tag from the dropdown, the tag should be added to the Tiddly. 

** Version 5.1.22

**Comment by Jermolene** [comment] 2020-08-14 11:28
Thanks @adithya-badidey this is a duplicate of #4673 and is fixed in #4674; the  fix is available in the prerelease at https://tiddlywiki.com/prerelease

**Closed by Jermolene** 2020-08-14 11:28 UTC
