### ISSUE TITLE
Links to tiddlers not working inside modals?

### ISSUE THREAD

**Issue by morosanuae** [Jermolene/TiddlyWiki5#3560] opened 2018-11-20 15:57 UTC
I don't know if this is by design or not but I discovered that links to tiddlers inside modals are not working. I mean when I press a link to a tiddler it doesn't open that tiddler. It would be a very helpful ability for me.

**Comment by Jermolene** [comment] 2018-11-20 16:48
Thanks @morosanuae that's a regression, links in modals should work, so something has broken them at some point. I'll investigate

**Comment by morosanuae** [comment] 2018-11-25 11:34
@Jermolene Shouldn't be a fix for this problem included in the v5.1.18 release? I don't have one, but I'll try to find out in what version of TiddlyWiki this bug appeared for the first time, if this will be useful in troubleshooting. I don't want a nice release like this one to carry such bugs with it.

**Comment by BurningTreeC** [comment] 2018-11-25 11:37
@morosanuae I believe it's the missing `navigator` widget instance in modals that causes navigation not to work. Inside a modal, you can wrap the content inside `<$navigator story="$:/StoryList" history="$:/HistoryList">` and `</$navigator>` and links should work

**Comment by morosanuae** [comment] 2018-11-25 11:42
@BurningTreeC thanks for the quick reply and for the solution, I'll try it out. But anyway, it shouldn't just work out of the box? Isn't this a complicated solution for an inexperienced user?

**Comment by morosanuae** [comment] 2018-11-25 11:43
And one more question: why @Jermolene said is a regression?

**Comment by BurningTreeC** [comment] 2018-11-25 11:52
@morosanuae I think it worked at some point. I looked up the history of `modal.js` and it appears as if it was handled differently some years ago. Now it's handled by the rootwidget and there's no navigator instance available

**Comment by morosanuae** [comment] 2018-11-25 11:59
@BurningTreeC ok, thanks for the info. I guess there is a reason for this change, but one that has caused unwanted side effects. Maybe @Jermolene can tell us more about it. It isn't hard for me to apply your solution, but maybe for others will be. IMHO we still need a proper solution for this.

**Comment by BurningTreeC** [comment] 2018-11-25 12:04
>IMHO we still need a proper solution for this

yes we do, you're right!

**Comment by Jermolene** [comment] 2018-11-25 14:32
I agree it would be good to fix this, but I think it predates v5.1.18 so I'd rather tackle it after the release.

**Comment by saqimtiaz** [comment] 2020-03-14 20:49
Bumping this as I think it would be good to get this resolved, or marked as something we wont fix and the solution (using a Navigator widget) documented accordingly.
 
The issue indeed seems to be that modals are handled by the root widget and there is no navigator widget available.

I've been getting around this issue with a modified copy of modal.js which wraps the transcluded tiddler with a Navigator widget, though this includes hardcoding the storylist and historylist which is not ideal. I realize I could also wrap my content in a Navigator widget each time but that isn't very convenient.

This issue appears to be a duplicate of #2188, however the discussion here is more informative.

**Closed** 2020-11-16 16:27 UTC
