### ISSUE TITLE
feature request: load user defined system tiddlers after core tiddlers

### ISSUE THREAD

**Issue by rubaboo** [Jermolene/TiddlyWiki5#1561] opened 2015-03-07 04:23 UTC
As discussed here: https://groups.google.com/d/msg/tiddlywiki/BPuuSkG6siU/7-o1ll2tPDkJ

**Comment by twMat** [comment] 2015-03-07 08:37
+1

**Comment by pmario** [comment] 2018-05-28 10:35
@rubaboo .. IMO can be closed!
@Jermolene 

The OP was about stylesheet sorting, which is now possible with every SystemTag: https://tiddlywiki.com/#SystemTags

**Comment by rubaboo** [comment] 2018-05-28 16:03
The issue was uncovered because of the order of stylesheets, but it can equally apply to any user-created system tiddler that wants to override something in the core.

As Mat said,
> IMO this problem should not be solved with something that demands the user to actively keep it in mind. Particularly since disregarding it *might* work, resulting in inconsistent behaviour. I'd prefer that any user defined system tiddlers are loaded after core tiddlers

 Sorting tiddlers in a tag would literally demand the user to actively maintain the order, as new core tiddlers might potentially appear and disrupt the order again.

The issue is not about stylesheets, and definitely not about different possible ways to set the story width, as discussed in the OP. It is about having a certain precedence rule for tiddler loading, rather than relying on a single overarching alphabetical order. Say, 1) core tiddlers > 2) plugin tiddlers > 3) user-defined system tiddlers. Then, within the last category, it would be quite reasonable to expect the user to maintain a list order, if alphabetical is not satisfactory.

I just wanted to express myself clearly. It is not my intention to have a protracted discussion. Please go ahead and close this issue if you don't think it deserves attention.

**Comment by pmario** [comment] 2018-05-28 16:10
Would [list-after](https://tiddlywiki.com/#Order%20of%20Tagged%20Tiddlers) field partially solve the problem?

**Comment by pmario** [comment] 2018-05-28 16:11
It was designed to solve problems you described now. ... But it still needs the user to define the `list-before` or `list-after` fields

**Comment by pmario** [comment] 2018-05-28 16:15
>I just wanted to express myself clearly. 

For me it's clearer now. 

>It is not my intention to have a protracted discussion. 

:) I just wanted to get rid of some long standing open issues, where it's not clear, if they are still valid, or new TW functions make them obsolete. 

I'm not usre if the "list-before/after" stuff will work here? 

>Please go ahead and close this issue if you don't think it deserves attention.

Only Jeremy or the creator of the issue can close it :) ... 

If it's still valid, it should stay **open**

**Comment by rubaboo** [comment] 2018-05-28 17:17
> Would list-after field partially solve the problem?

Even with the recently merged 7e58866, `list-after` would only make the problem less likely to surface, but not really solve it.

Also, I stopped relying on `list-before` and `list-after` because of the issues that @flibbles  describes in #3301 (and proposes to solve!). So, if I may, please be sure to green-light #3301, Jeremy seems to rely on your opinion when eye-balling the long list of PRs that he has to deal with. Thank you.

**Comment by Evolena** [comment] 2018-05-30 08:13
Does #3113 (merged in 1dc7647) about plugin priority help for this issue?

**Comment by pmario** [comment] 2022-08-28 21:06
@Jermolene ... This one can be closed. 

As shown in the screenshot. A custom stylesheet is definitely sorted after shadow stylesheets. No user intervention needed.
The sorting is still alphabetic, but if a user uses plugins they have to manage their styles manually, because plugins don't know each other. 

![image](https://user-images.githubusercontent.com/374655/187094425-a56cbd06-b0db-4ab0-ba3f-b5f3a1746f2f.png)

**Comment by Jermolene** [comment] 2022-09-05 22:10
Thanks @pmario

**Closed by Jermolene** 2022-09-05 22:10 UTC
