### ISSUE TITLE
Is the text formatting system a feature or a bug?

### ISSUE THREAD

**Issue by Innomen** [Jermolene/TiddlyWiki5#1577] opened 2015-03-14 16:20 UTC
In trying to find a way to easily format the text in a tiddlywiki entry I downloaded this plugin:

https://addons.mozilla.org/en-US/firefox/addon/text-formatting-toolbar/

But in using it I found that when I tried to bold or italics things I got '''this''' and ''this'' instead of ''bold'' for bold text and //italic// for italic text.

http://tiddlywiki.com/static/Formatting%2520in%2520WikiText.html

So I thought it was an error in the toolbar as it has been years since it was updated, but accord to wiki itself, the toolbar is the accurate one...

http://en.wikipedia.org/wiki/Help:Wiki_markup#Format

Can someone explain what's going on here? I'm clearly ignorant in the relevant areas.

If tiddly is going to use a unique formatting system has anyone made a plugin to have formatting buttons? Or could I shift the formatting to be html or bbcode instead of the custom system? Or is there some other solution that doesn't involve scrapping the toolbar or learning a new system?

When I compose posts in forums and wordpress and the like I use formatting buttons,  I do not want to have to type in code.

If this is a dupe, sorry again but there are like 20 different ways to say this hehe my search fu is weak :/

**Comment by Jermolene** [comment] 2015-03-14 17:48
I'm afraid that there is no real standardisation of wikitext across different wiki engines. The toolbar you've found looks like it was designed for MediaWiki syntax.

There was an attempt a few years ago to create a unified wiki syntax with http://www.wikicreole.org.

> If tiddly is going to use a unique formatting system has anyone made a plugin to have formatting buttons? 

There is a highly experimental formatting toolbar plugin you can try here:

http://tw5editor.tiddlyspot.com

**Comment by Innomen** [comment] 2015-03-14 19:05
Since as you say there's no standard and you've had to basically mix up your own. Then I guess this post is now a feature request that a tool bar like the one you linked to be included :) 

For the time being I can't figure out how to install it, The drag drop import only sorta worked. It looks empty to me, like if I follow the link itself it says missing.

I can use the generate empty button to create a tiddly wiki with the formatting bar baked in. I guess I can just export import to create a clone of my current wiki.

Thanks for the quick response :)

**Comment by Jermolene** [comment] 2015-03-14 19:36
> Then I guess this post is now a feature request that a tool bar like the one you linked to be included

Indeed, the plan is to integrate that functionality in the core - see #1537 for the main component. Then we'll have an extensible edit toolbar with operations that work on the current selection and/or the entire text box.

> For the time being I can't figure out how to install it, The drag drop import only sorta worked. It looks empty to me, like if I follow the link itself it says missing. I can use the generate empty button to create a tiddly wiki with the formatting bar baked in. I guess I can just export import to create a clone of my current wiki.

I think that the way that the editor is structured at the moment you're best advised to use the "generate empty" button to work with it. You can open the empty file and then drag you current wiki into it to import your existing tiddlers.

**Comment by Innomen** [comment] 2015-03-14 19:42
Sir, you are the man :)

Thanks again for making this and for your help, it is really appreciated :)

**Comment by tobibeer** [comment] 2015-09-21 12:16
@Innomen, I think this particular issue can be closed. Correct?

**Comment by Innomen** [comment] 2015-09-21 14:17
@tobibeer Not really until the new official version has a formatting toolbar? I'm still using the plugin, and when combined with the normal version I got a pretty substantial error. I have like a billion tags. I can live with it, but I'd still like to see some formatting options graphically built in to the default version.

Thank for asking :)

No rush, but I'd like it to stay on the long list of future features if that's ok :)

**Comment by tobibeer** [comment] 2015-09-21 14:22
Since the title of your issue and some of the discussion doesn't really reflect that, would you be fine with making #1747 the primary issue to track progress and close this one?

**Comment by Innomen** [comment] 2015-09-21 16:19
Ahh, yes I see your point now. Absolutely. Thanks again for asking :)

**Comment by Jermolene** [comment] 2015-09-22 11:25
Thanks @Innomen

**Closed by Jermolene** 2015-09-22 11:25 UTC
