### ISSUE TITLE
[BUG] Markdown plugin doesn't render html, & the wiki parser adds stray line breaks tags

### ISSUE THREAD

**Issue by af4jm** [Jermolene/TiddlyWiki5#4797] opened 2020-08-09 22:10 UTC
**Describe the bug**
adding line breaks in the middle of HTML blocks incorrectly changes the parsed output (on Dingus, it has no effect)

**To Reproduce**
1.  Create a markdown tiddler with the following content (and notice the correct rendering)...
`<h4>header</h4><ul><li>item 1</li><li>item 2</li></ul><ul><li>item 3</li></ul>`
(I know this can be done with plain Markdown, but in my case it's inside a table where Markdown doesn't render)
2. add a line break before one of the closing tags
3. notice that that closing tag now renders because the single line break is parsed as separating the raw html into 2 separate blocks

**Expected behavior**
HTML source should be able to have line breaks as in Dingus (in Dingus I can even add multiple consecutive line breaks and it still renders as a single HTML block)

**Screenshots**
![image](https://user-images.githubusercontent.com/849948/89742743-9cc89100-da6a-11ea-9ef5-21f212d8c4f1.png)

The preview windows should be identical since the html is identical

**Additional context**
Ran the wiki through upgrade to ensure everything was up to date.

I tried turning off "renderWikiText", but that output the raw HTML instead, which obviously is even more wrong... all 4 cases (my screenshot (which had renderwiktext true), and the same with renderwikitext turned to false, should all render as the top of my screenshot renders, but the other 3 are broken

**Comment by pagdot** [comment] 2020-08-25 13:33
This seems to be an issue with the Remarkable library used to render Markdown as it can be reproduced in it's [live demo](https://jonschlinkert.github.io/remarkable/demo/). I'd recommend filing a issue in the [Remarkable Repository](https://jonschlinkert.github.io/remarkable/demo/). If it gets fixed there maybe i is possible to update the embedded version of remarkable.

**Comment by af4jm** [comment] 2020-08-27 21:43
Actually, it can't be reproduced over there, unless you put the line break inside the html tag, which I would expect to give garbage output, because the input isn't valid

Here's [Markdown's live demo with the exact html from my second (broken) screenshot](https://jonschlinkert.github.io/remarkable/demo/#md64=JTdCJTIyc291cmNlJTIyOiUyMiUzQ2g0JTNFaGVhZGVyJTNDL2g0JTNFJTNDdWwlM0UlNUNuJTNDbGklM0VpdGVtJTIwMSUzQy9saSUzRSU1Q24lM0NsaSUzRWl0ZW0lMjAyJTNDL2xpJTNFJTVDbiUzQy91bCUzRSUzQ3VsJTNFJTVDbiUzQ2xpJTNFaXRlbSUyMDMlM0MvbGklM0UlNUNuJTNDL3VsJTNFJTIyLCUyMmRlZmF1bHRzJTIyOiU3QiUyMmh0bWwlMjI6dHJ1ZSwlMjJ4aHRtbE91dCUyMjpmYWxzZSwlMjJicmVha3MlMjI6ZmFsc2UsJTIybGFuZ1ByZWZpeCUyMjolMjJsYW5ndWFnZS0lMjIsJTIybGlua2lmeSUyMjpmYWxzZSwlMjJsaW5rVGFyZ2V0JTIyOiUyMiUyMiwlMjJ0eXBvZ3JhcGhlciUyMjpmYWxzZSwlMjJfaGlnaGxpZ2h0JTIyOmZhbHNlLCUyMl9zdHJpY3QlMjI6ZmFsc2UsJTIyX3ZpZXclMjI6JTIyaHRtbCUyMiU3RCU3RA==), and it renders correctly instead of treating every line break like it separates HTML blocks

**Comment by pagdot** [comment] 2020-08-28 06:57
Ok, sorry my bad 🤦

**Comment by Jermolene** [comment] 2020-08-28 11:43
I suspect that this behaviour may be an unexpected side effect of the wikitext processing that was added to the Markdown parser in #3876. @MidnightLightning do you have any thoughts?

**Comment by MidnightLightning** [comment] 2020-08-28 13:45
@Jermolene Yes, I'm able to reproduce this issue too, working off the version of the Markdown plugin that is as I merged it, however, it looks like https://github.com/Jermolene/TiddlyWiki5/pull/4684 will fix this issue, since looking at the parsed tree that Remarkable sends down:

```
[
  { "type": "text", "content": "<h4>header</h4><ul>", "level": 0 },
  { "type": "softbreak", "level": 0 },
  { "type": "text", "content": "<li>item 1</li>", "level": 0 },
  { "type": "softbreak", "level": 0 },
  { "type": "text", "content": "<li>item 2</li>", "level": 0 },
  { "type": "softbreak", "level": 0 },
  { "type": "text", "content": "</ul><ul>", "level": 0 },
  { "type": "softbreak", "level": 0 },
  { "type": "text", "content": "<li>item 3</li>", "level": 0 },
  { "type": "softbreak", "level": 0 },
  { "type": "text", "content": "</ul>", "level": 0 }
]
```
Which is marking those gaps between list elements as "soft" breaks (accurate), and that pull request strips out soft breaks when the `$:/config/markdown/breaks` config is `false` (the default). (Key code change [here](https://github.com/Jermolene/TiddlyWiki5/blob/master/plugins/tiddlywiki/markdown/wrapper.js#L174))

I've not upgraded myself to test that yet, but I think that should fix it!

**Comment by MidnightLightning** [comment] 2021-01-21 15:58
With the release of v5.1.23 (which includes #4684), I believe this issue should be fixed; can you still reproduce, @af4jm ?

**Comment by af4jm** [comment] 2021-01-21 16:05
sorry, I've had to move on from TW because accessing from anywhere became an issue (corp firewalls that block file sync sites, including Dropbox, which also blocks logging into TW in the Sky... and TW in the Sky wasn't reliable on mobile anyway, so I no longer have a TW handy to try with)... my current solution is just a private git repo with Markdown files, very similar to an Azure DevOps wiki

**Comment by Jermolene** [comment] 2021-01-21 16:55
Thanks @MidnightLightning @af4jm I think we can indeed close this.

**Closed by Jermolene** 2021-01-21 16:55 UTC
