### ISSUE TITLE
About existing TOC vs. prerelease TOC performance degrading

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#3517] opened 2018-11-06 14:57 UTC
I did some measurements with tiddlywiki.com and tiddlywiki.com/prerelease

 - Saved both full version which include: 995 tiddlers for tiddlywiki.com and 1100 for prerelease
 - Activated:  Enable performance instrumentation 

The following code was measured, which renders the full structure. 

```
<div class="tc-table-of-contents">
<<toc "TableOfContents">>
</div>
```

TW | from | to |
------|-----|-----
tiddlywiki.com | 1600ms | 1900ms
prerelease | 2300ms | 2900ms

IMO That's way too much!

My system: 

 - win 10 pro 64bit
 - intel core i5 3.4 GHz
 - 16 GB RAM
 - FF 63

**Comment by Jermolene** [comment] 2018-11-06 15:16
Thanks @pmario that's helpful. We should definitely aim to improve performance in cases like this.

**Comment by pmario** [comment] 2018-11-06 15:19
There have been some heavy improvements, to make the code more stable against "nasty titles". ... It can happen :)

**Comment by pmario** [comment] 2018-11-07 13:43
New test with a slightly modified version. All paths expanded and DOM structure retained. 

Steps to prepare measurement: 

 - checkout tag v5.1.17 ... `git checkout -b test v5.1.17`
    - or checkout master ... `git checkout -b test-master master`
 - open /core/wiki/macros/toc.tid
 - search and replace ALL `reveal ` -> `reveal default=open retain=yes`
 - create index.html `node tiddlywiki.js editions/tw5.com --build index`
 - open the file
 - enable " Enable performance instrumentation"
 - save
 - reload
 - test the following code: 

```
<div class="tc-table-of-contents">
<<toc-selective-expandable "TableOfContents">>
</div>
```

TW Version | from | to |
------|-----|-----
V 5.1.17 | 3700ms | 3990ms
prerelease latest | 5000 ms | 5400 ms

more to follow

**Comment by pmario** [comment] 2018-11-07 13:50
@Jermolene commit 587fe9d10 which contains wikify seems to be faster as the latest master branch :/ ... That's surprising

**Comment by pmario** [comment] 2018-11-07 13:52
zip file, that contains all 3 versions from above. 
[Downloads.zip](https://github.com/Jermolene/TiddlyWiki5/files/2557567/Downloads.zip)

**Comment by Jermolene** [comment] 2018-12-01 17:57
Hi @pmario I've been unable to duplicate these findings.

As a test rig, I turned on performance instrumentation, and replaced the inner list filter of `$:/core/ui/PageTemplate` with:

```
<div class="tc-table-of-contents">

<<toc "TableOfContents">>

</div>
```

Then I compared performance with the current version of `toc.tid` with the [v5.1.17 one](https://github.com/Jermolene/TiddlyWiki5/blob/0c3e549235913b94855424aadadfd18ca07b3746/core/wiki/macros/toc.tid). On my MacBook Pro I get virtually identical readings for both versions of the code: around 3s for the initial main render, and 0.6s for the initial main refresh.

**Comment by pmario** [comment] 2018-12-03 09:59
@Jermolene ... The toc macro doesn't use the reveal widgets. .. So there is basically no difference in timing. ... as you found out. 

the proper test is: https://github.com/Jermolene/TiddlyWiki5/issues/3517#issuecomment-436626603

The Downloads.zip file contains all 3 versions, that I used for testing. You could use them.

**Comment by Jermolene** [comment] 2018-12-03 10:08
Hi @pmario ah my apologies, I did indeed miss a crucial section of your original post:

> search and replace ALL reveal -> reveal default=open retain=yes

I'd missed that we were now retaining the hidden nodes. I'd expect that to cause recursion errors with some TOCs (e.g. I've know of a wiki with 1000 tiddlers but -- thanks to copious tagging -- 4 million entries in a fully expanded TOC).

@BurningTreeC are there are any other places where we've made this change?

**Comment by pmario** [comment] 2018-12-03 10:13
retain=yes ... imo is not needed for the test.

The recursion error was eliminated some time ago.

The "kin" filter may be able to help with multiple tags in the TOC, because it can eliminate dups ... which will need to "strange" behaviour for some users. ... 

The surprise for me was that the "wikify-version" was faster that the latest iteration. ... It seems to have a "caching" effect.

**Comment by pmario** [comment] 2018-12-03 10:16
To be honest. I could live with [commit 587fe9d10](https://github.com/Jermolene/TiddlyWiki5/commit/587fe9d10eaa1e837da02f3d8c5f885acef9da10)

-----

I was thinking about some "hardcoded" JS-toc-macros, which should be able to speed things up, quite a bit. ... may be :)

**Comment by pmario** [comment] 2018-12-03 10:17
just to be sure. ... The `reveal default=open retain=yes` where only made for testing, to get the whole tree expanded by default.

**Comment by Jermolene** [comment] 2018-12-03 10:18
> just to be sure. ... The reveal default=open retain=yes where only made for testing, to get the whole tree expanded by default.

Indeed I misread your message in haste, and deleted my subsequent comment.

Is 587fe9d10eaa1e837da02f3d8c5f885acef9da10 the commit where the performance regression was introduced?

**Comment by Jermolene** [comment] 2018-12-03 10:31
> Is 587fe9d the commit where the performance regression was introduced?

Just realised that that commit doesn't reflect the current code; we got rid of the wikify call since then.

This URL shows the changes to the TOC macro:

https://github.com/Jermolene/TiddlyWiki5/compare/v5.1.17...master#diff-76542ab9902926648b40dfa8e112bcb6

**Comment by BurningTreeC** [comment] 2018-12-03 10:43
@pmario, @Jermolene 

the toc macros use the `stateTitle` attributes now

there's this line in the reveal widget:

https://github.com/Jermolene/TiddlyWiki5/blob/018f7628f565269395950a0b94af7eadd05484c9/core/modules/widgets/reveal.js#L124

Could this be part of the slow-down?

**Comment by BurningTreeC** [comment] 2018-12-03 10:44
To above: I mean line 124 and the preceding lines

**Comment by Jermolene** [comment] 2018-12-03 10:51
Hi @BurningTreeC I'm not a fan of combining conditionals like that, but I don't think it's problematic from a performance perspective. I'm wondering if it's the switch from text substitution to a lot more filtered transcluded attributes (ie, `attr={{{ blah }}}`).

**Comment by BurningTreeC** [comment] 2018-12-03 11:00
@Jermolene, do we have an alternative for `{{{ blah }}}`?

**Comment by BurningTreeC** [comment] 2018-12-03 11:06
if we replace all `{{{ blah }}}` through wikify widgets that do:

```
\define toc-add-suffix(prefix,suffix)
$prefix$$suffix$
\end
<$wikify name="path" text="""<$macrocall $name="toc-add-suffix" prefix=<<__path__>> suffix=<<__tag__>>>
```

**Comment by Jermolene** [comment] 2018-12-03 12:21
I would expect a wikify widget to be a lot slower than a filter. The wikify widget parses it's text, and renders it to a widget tree and fake DOM before extracting the resulting text. The reason that I didn't implement the wikify widget for a long time was that I thought it absurdly inefficient.

Meanwhile, filter parsing and evaluation is heavily optimised, and so I'd expect it to be a lot faster.

**Comment by pmario** [comment] 2018-12-03 12:21
>Is 587fe9d the commit where the performance regression was introduced?

It was the first one, where I did measurements. ... I had concerns about the performance, that wikify may have introduced. ... 

As it turns out, removing wikify didn't fix it, but made it worse.

**Comment by pmario** [comment] 2018-12-03 12:23
The first changes, that where done was to from `"""$param"""` -> `<<__param__>>` ... which is still part of the code. (for a reason)

**Comment by BurningTreeC** [comment] 2018-12-03 12:30
To my idea above using the wikify widget, very bad idea, I tried -> more than 7 seconds

>The first changes, that where done was to go from """$param""" -> <<__param__>> ... which is still part of the code. (for a reason)

yes, we wanted to make it more robust for titles with quotes etc. which worked

@pmario do you think replacing the wikify widget that created the qualified state with the `<$qualify>` widget made it worse?

**Comment by pmario** [comment] 2018-12-03 13:17
>@pmario do you think replacing the wikify widget that created the qualified state with the <$qualify> widget made it worse?

The funny thing is. wikify wasn't the slowest solution. 

If you have a look at the download.zip file from https://github.com/Jermolene/TiddlyWiki5/issues/3517#issuecomment-436629312 you can see the differences with F12 console. If you switch between toc-tab and an other tab.

**Comment by BurningTreeC** [comment] 2018-12-03 13:18
>do you think replacing the wikify widget that created the qualified state with the <$qualify> widget made it worse?

I tried, it's not the case

**Comment by BurningTreeC** [comment] 2018-12-03 13:19
>If you have a look at the download.zip file from #3517 (comment) you can see the differences with F12 console. If you switch between toc-tab and an other tab.

Yeah I see, I'm just doing that right now

**Comment by pmario** [comment] 2018-12-03 13:21
open and close "New Tiddler" is also possible

**Comment by BurningTreeC** [comment] 2018-12-03 13:21
I've cloned the current prerelease, set every reveal widget in the TOC macro to open and retain to yes and enabled performance instrumentation. Testing with the latest tw5.com

**Comment by pmario** [comment] 2018-12-03 13:33
latest master FF64: 

performance: styleRefresh: 3.00ms 
performance: +filter: 0.00ms 
performance: mainRefresh: 4912.00ms 
performance: +filter: 687.00ms 

MS Edge 17.17134  / win 10 

 performance: styleRefresh: 14.60ms 
 performance: +filter: 3.40ms 
 performance: mainRefresh: 11772.50ms 
 performance: +filter: 2552.00ms

**Comment by BurningTreeC** [comment] 2018-12-03 13:45
I've merged the kin-filter pr locally into the current master, enabled performance instrumentation and changed the toc-macro reveal widgets to open and retained. there are two toc sidebar tabs, one the normal toc, one filtered by the kin filter

created a single html from it:

[tw5118kin.zip](https://github.com/Jermolene/TiddlyWiki5/files/2639630/tw5118kin.zip)

**Comment by BurningTreeC** [comment] 2018-12-03 14:05
another thing surely hitting performance is the amount of tiddlers

5.1.17 gives me 2908 tiddlers

5.1.18 gives me 3311

just counting them through
```
{{{ [all[tiddlers+shadows]count[]] }}}
```

**Comment by BurningTreeC** [comment] 2018-12-03 14:06
+ ~14%

**Comment by Jermolene** [comment] 2018-12-05 13:14
@BurningTreeC can you confirm you're seeing the same performance degradation reported by @pmario?

If so, does using the toc.tid from 5.1.17 with the latest prerelease take us back to 5.1.17 performance?

**Comment by BurningTreeC** [comment] 2018-12-05 13:56
Hi @Jermolene , what Ican confirm is that there's a difference in rendering time like @pmario describes when using the latest Firefox nightly on Linux (with its new webrenderer on)

**Comment by BurningTreeC** [comment] 2018-12-05 13:57
I haven't tested on more browsers and platforms, just couldn't find the time

**Comment by BurningTreeC** [comment] 2018-12-05 13:59
What I propose is that we give 5.1.18 a go and let this out to more systems and browsers. I think that working and playing with it we'll get more ideas

**Comment by BurningTreeC** [comment] 2018-12-05 14:01
We could also take the old toc- macros back in and name the new ones toc-solid, toc-selective-expandable-solid ...

**Comment by BurningTreeC** [comment] 2018-12-05 14:02
So for 5.1.18 this could be a temporary solution

**Comment by BurningTreeC** [comment] 2018-12-05 14:11
#3621 has the new toc macros renamed so that they all end with -solid and put the 5.1.17 macros back in with their original names

**Comment by Jermolene** [comment] 2018-12-05 14:32
Hi @BurningTreeC I think I'd rather go with the current version, improve it, or pull the changes entirely. #3621 could be a useful basis for a performance test rig though...

**Comment by BurningTreeC** [comment] 2018-12-05 14:38
Yes, @Jermolene ... I'd do the same

**Comment by BurningTreeC** [comment] 2018-12-05 14:39
I can just say that now testing on chrome and firefox, the results do vary a bit. we need more experience with this and should just go playing around :grin:

**Comment by BurningTreeC** [comment] 2018-12-05 14:43
To your question above, yes, the 5.1.17 macros are more performant in 5.1.18, too

But I believe the new ones are how they should work

So I don't know and decision is up to you

**Comment by BurningTreeC** [comment] 2018-12-05 14:46
For 5.1.18 let's launch a contest in the Google group who comes up with the most performant TOC macro that handles titles well

**Comment by Jermolene** [comment] 2018-12-05 15:03
I've been experimenting with a slightly different setup which you can see in the branch "toc-performance" - https://github.com/Jermolene/TiddlyWiki5/tree/toc-performance

As presently configured, the v5.1.17 macros are used (with the mods suggested by @pmario above). To test it with the v5.1.18 macros, change the tag on toc.tid to be `$:/tags/Macro" and change the tag on toc-5.1.17.tid to be `$:/tags/Macro2`.

In my tests on macOS Chrome, the main render times for 10 consecutive runs with the v5.1.17 TOC macro were (to 2 significant figures):

* 8900ms
* 6700ms
* 8800ms
* 8700ms
* 9000ms
* 8800ms
* 8800ms
* 8900ms
* 8900ms
* 9000ms

The same timings for the v5.1.18 TOC macros were:

* 6800ms
* 8800ms
* 9000ms
* 8700ms
* 9100ms
* 8800ms
* 9000ms
* 8800ms
* 9000ms
* 8800ms

So, on that basis, I'm going to conclude that @pmario's results were due to the test methodology, and proceed with the v5.1.18 release.

**Closed** 2018-12-06 21:45 UTC
