### ISSUE TITLE
[IDEA] move the sidebar's scrollbar under the tabs

### ISSUE THREAD

**Issue by tgirod** [Jermolene/TiddlyWiki5#5228] opened 2020-12-07 12:35 UTC
I have a wiki with a **lot** of tags, so the sidebar scrolls when the "More" tab is selected. When this happens, I get two scrollbars next to each other on the window side, which is inconvenient.

I think the scroll would be better off under the `Open | Recent | Tools | More` tabs, with the top of the column fixed. Anyway, that's just a thought!

**Comment by pmario** [comment] 2020-12-11 12:30
IMO duplicate of: Feature to consider: Sidebar scrolling limited to tabs #144

**Comment by tgirod** [comment] 2020-12-11 15:05
@pmario well spotted!

**Closed** 2020-12-11 15:05 UTC
