### ISSUE TITLE
TW5 can miss the signal to re-hide the drag-and-drop target in Firefox 31.0a2

### ISSUE THREAD

**Issue by ssokolow** [Jermolene/TiddlyWiki5#686] opened 2014-07-15 07:32 UTC
I've noticed that, sometimes (in hard-to-reproduce situations), dragging an entry from the Open tab but then letting go outside the drop target will leave the target stuck visible until another drag is performed.

It'd probably be a good idea to take a cue from imgur's "drag-and-drop to upload" support and put an × button on one end of it to allow users to manually address this case.

**Comment by Jermolene** [comment] 2017-08-21 11:07
This problem still exists.

**Comment by Jermolene** [comment] 2021-09-13 16:50
Closing because I believe that this has been fixed for some time.

**Closed by Jermolene** 2021-09-13 16:50 UTC
Labels: bug

**Comment by DemoniWaari** [comment] 2021-12-07 10:56
Is the issue back? The green bar does not go away when pressing escape. I have been having this problem for quite a while now, at least the entire year. Using Firefox 91.3.0esr.

**Comment by saqimtiaz** [comment] 2021-12-07 11:28
@DemoniWaari what TW version? 
It would be helpful if you also posted a screenshot, and if possible steps to reproduce the problem.

**Comment by DemoniWaari** [comment] 2021-12-07 11:48
@saqimtiaz Ah. Nevermind. I think the issue is just with my wiki, as it does not seem to happen with an empty wiki. Apologies about that.
