### ISSUE TITLE
[IDEA] Syntax Highlight for WikiText / Language Specification

### ISSUE THREAD

**Issue by MonaMayrhofer** [Jermolene/TiddlyWiki5#6368] opened 2021-12-23 19:37 UTC
I was getting frustrated by TiddlyWiki not having syntax-highlight for WikiText, as that would greatly improve developer experience when writing complex macro-calls or filters. That actually drove me to the point where I was thinking of creating a tree-sitter grammar myself, which enables vim and I believe other editors like VSCode to properly syntax highlight WikiText. Also, this could be reused to create a highlight.js grammar and enable TiddlyWiki itself to highlight WikiText.

But to do that in a proper way that can be given back to the community a language specification of WikiText would be of great help. But I could not find more than the occasional railroad diagrams in the docs (Which would suffice, but a complete specification would be neat)

Are there any ongoing efforts of going in that direction / explicit decisions to not go there, that I have overlooked? 
Would there be any interest in such a project?

**Comment by pmario** [comment] 2021-12-23 20:57
There is a plugin for VSCode such does syntax highlighting. You should be able to search forit in VSCode.

**Comment by MonaMayrhofer** [comment] 2021-12-25 16:23
Thanks, I seem to have overlooked that^^

I would leave this issue open nevertheless for now to encourage further discussion, as a unification of such extensions could be desirable (maybe pave the way to a full-blown LSP) - and in-app highlighting still would be sweet.

**Comment by pmario** [comment] 2021-12-25 17:49
You may have a closer look at: https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced

**Comment by twMat** [comment] 2021-12-28 23:37
>I would leave this issue open for now nevertheless to encourage further discussion

I'd suggest you open a discussion in the Discussion area instead, as we already have way too many issues and many just linger on forever.

**Comment by morosanuae** [comment] 2021-12-29 09:18
An open issue on this subject already exists for some time: "Code highlighting for TiddlyWiki5 syntax? #3685". We have many duplicates also. We are wasting valuable time and resources reinventing the wheel again and again.

**Comment by Jermolene** [comment] 2021-12-29 14:05
Thanks everyone. I think this is indeed a dupe of #3685

**Closed by Jermolene** 2021-12-29 14:05 UTC
