### ISSUE TITLE
Add special class to the first and last tiddler on the story river.

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyWiki5#2515] opened 2016-07-31 11:54 UTC
Every tiddler receives several classes that corresponds to the tags it has. This is a very smart and useful feature that allows you cool and powerful ways of customization.

A similar feature would be required for the first and the last tiddlers on the story river. This would allow more ambitious layouts and even more customization options. For example, the creation of a footer and a header and several others.

Regards

**Comment by pmario** [comment] 2016-07-31 14:38
just use: $:/tags/AboveStory and $:/tags/BelowStory tags. see: http://tiddlywiki.com/#SystemTags

**Comment by danielo515** [comment] 2016-07-31 15:36
That does not solves the problem. Because those tiddlers are going to be fixed. I want to be able to operate on the first or latest tiddler no matter which tiddlers are being displayed.

**Comment by pmario** [comment] 2016-08-01 13:15
IMO that's exactly, what it does. AboveStory and BelowStory are the first and the last tiddler. So it doesn't matter, what you display in between. IMO that removes a lot of complexity. ... It's just a different point of view of the problem.

**Comment by danielo515** [comment] 2016-08-01 14:02
@pmario , it is not just a matter of point of view. AboveStory and BelowStory are ALLWAYS sown. If you want to style the first tiddler of the story river, without having fixing it to all the views then you have no choice.

**Comment by pmario** [comment] 2016-08-01 14:29
Can you point out a usecase, where you need a different style for the first and last tiddler. I don't see the reason, why this should be in the core?

**Comment by danielo515** [comment] 2016-08-02 08:06
It's all about customization. What would you want to style a tiddler different based on it's tags? 
To see one example visit NoteSelf.github.io, it is actually a tiddlywiky. There are two fixes tiddlers (above and below story) and the first tiddler of every page needs an extra padding to not obscure the content because the header is fixed. This happens also to any tiddlywiky on mobile, the sidebar obscures the first tiddler.

**Comment by pmario** [comment] 2016-08-02 12:44
I made some test with tiddlywiki.com. Seems to be a pure CSS / implementation problem. 

Also made some tests with your page. Same thing here. IMO theme and CSS problems only. ... It seems you hardcoded the styles to remove the editing functionality. So it's really hard for me to debug the page. ... github repo is empty. 

There is CSS for `:first-child` and `:last-child` see: https://developer.mozilla.org/en/docs/Web/CSS/:first-child

----

I was experimenting with a menu like this one: http://jsfiddle.net/WDnyb/2/ ... Seems to be doable without any changes to the core.

-----

TW sidebar on mobile is also CSS only problem. ... We just need to implement a responsive CSS only menu. ... nobody did it. that's the problem.

**Comment by danielo515** [comment] 2016-08-02 14:45
>I made some test with tiddlywiki.com. Seems to be a pure CSS / implementation problem.
>
Also made some tests with your page. Same thing here. IMO theme and CSS problems only.

Which kind of test? Have you mark as position fixed a tiddler with the tag aboveStory? Does not obscure it the first tiddler in the story river?

>There is CSS for :first-child and :last-child see:

Trust me, I have fought with `:first-child` and `:last-child` a lot of time. The problem is that it does not limit itself to the first element, but for all the first elements below the parent, so if you have the styled element (let's say a div) several times inside several parents under the main parent, all of them get styled.

>github repo is empty.

Not for long. I want to upload it soon.

**Comment by twMat** [comment] 2016-08-03 01:00
I get it to work for first tiddler but not last. http://fordanielo.tiddlyspot.com.

**Comment by danielo515** [comment] 2016-08-03 07:54
Hello Mat. 

I totally forgot about nth child. I have to check how good cross browser support for it it. 

BTW I have you opened your example on mobile? looks like a real mess :smile:

**Comment by twMat** [comment] 2016-08-03 08:30
>BTW I have you opened your example on mobile? looks like a real mess

Hehe! An intentional mess, yes. Actually, I'm surprised that it looks //exactly// as intended (at least on my Android).

Note that the extra square is my SideEditor plugin and this, in mobile, apparently totally hides the sidebar. This matter has nothing to do with the actual topic we're discussing though.

**Comment by Jermolene** [comment] 2016-08-08 13:09
@danielo515 are you happy to close this? nth-child etc. in CSS seems the best solution here

**Comment by danielo515** [comment] 2016-08-08 17:41
Hello Jeremy,

I don't know how wide is the adoption of nth-child but seems that it gets the job done. If you don't find this useful, you can close the issue.

Regards.

**Closed** 2016-08-20 17:35 UTC
